import { commercialContextForBundle, getBriefBundle, ownsBrief, privateHtml } from "../api/location-brief-v2/_shared.js";
import universalIntelligence from "../../lib/intelligence/universal-space-type-intelligence.js";

const { projectUniversalIntelligence } = universalIntelligence;
const esc = (value) => String(value == null ? "" : value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
const label = (type) => type === "retail_service" ? "Retail / service" : type === "industrial_flex" ? "Industrial / Warehouse / Flex" : "Office";

function render(bundle) {
  const requirement = bundle.currentRevision.requirement;
  const context = commercialContextForBundle(bundle);
  const projection = projectUniversalIntelligence(requirement);
  const anchor = requirement.locationLogic?.marketAnchor || {};
  const market = anchor.displayName || anchor.marketName || anchor.city || context.marketId;
  const state = anchor.state || "";
  const propertyType = requirement.propertyTypes?.[0] || "office";
  const topics = projection.investigationTopics.slice(0, 6);
  const locations = context.guidanceDistricts || [];
  const size = requirement.sizeCapacity?.summary || "";
  const timing = requirement.timing?.summary || "";
  const briefUrl = `/location-brief/${bundle.brief.publicId}`;
  const requirements = [
    context.business ? `Business / use: ${context.business}` : "",
    size ? `Approximate need: ${size}` : "",
    timing ? `Timing: ${timing}` : "",
    locations.length ? `Locations worth investigating: ${locations.join(", ")}` : `Starting market: ${market}`,
    topics.length ? `Investigation topics: ${topics.join("; ")}` : "",
  ].filter(Boolean).join("\n");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Research spaces for my business | Rofo</title><link rel="stylesheet" href="/assets/requirement-prototype.css"><style>
  body{margin:0;background:#f5f8fc;font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#0f172a}.research{max-width:920px;margin:auto;padding:clamp(2rem,6vw,5rem) 1rem}.research__head{max-width:760px;margin-bottom:2rem}.research__head h1{font-size:clamp(2.2rem,6vw,3.8rem);line-height:1.04;letter-spacing:-.04em;margin:.5rem 0}.research__head p{font-size:1.08rem;color:#526076}.research__grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(260px,.8fr);gap:1.5rem;align-items:start}.research__card{background:#fff;border:1px solid #dbe6f1;border-radius:12px;padding:clamp(1.4rem,4vw,2.2rem);box-shadow:0 12px 26px rgba(15,23,42,.05)}.research__card h2{margin-top:0}.research__facts{display:grid;gap:.8rem}.research__facts div{border-top:1px solid #e2e8f0;padding-top:.75rem}.research__facts dt{color:#64748b;font-size:.78rem;font-weight:800;text-transform:uppercase;letter-spacing:.06em}.research__facts dd{margin:.2rem 0 0;font-weight:650}.research ul{padding-left:1.2rem}.research label{display:grid;gap:.4rem;font-weight:700;margin-bottom:1rem}.research input{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:9px;padding:.85rem;font:inherit}.research button{width:100%;border:0;border-radius:8px;padding:.9rem 1rem;background:#1746cc;color:#fff;font:inherit;font-weight:800;cursor:pointer}.research button:focus-visible{outline:3px solid #bfdbfe;outline-offset:3px}.research__note,.research__status{color:#526076;font-size:.92rem}.research__status[aria-live]{font-weight:700}.research__back{display:inline-block;margin-top:1.3rem}@media(max-width:700px){.research__grid{grid-template-columns:1fr}.research{padding-left:14px;padding-right:14px}}
  </style></head><body><main class="research"><header class="research__head"><p class="requirement-prototype__eyebrow">Continue your search</p><h1>Ask Rofo to research spaces for your business.</h1><p>Rofo will use the Location Brief you already created to investigate current and upcoming options, property fit, and local alternatives. This is a research request—not an instant inventory search.</p></header><div class="research__grid"><section class="research__card"><h2>Share this search with Rofo</h2><p>You will not need to repeat the Business Profile.</p><form data-research-form action="/api/leads/submit" method="post">
    <input type="hidden" name="lead_type" value="location_profile"><input type="hidden" name="source" value="rofo-vnext-research"><input type="hidden" name="page_type" value="research_search"><input type="hidden" name="page_url" value="/research-search/${esc(bundle.brief.publicId)}"><input type="hidden" name="rofo_source" value="${esc(context.sourcePath || briefUrl)}"><input type="hidden" name="city" value="${esc(anchor.city || market)}"><input type="hidden" name="state" value="${esc(state)}"><input type="hidden" name="market" value="${esc(market)}"><input type="hidden" name="routing_market" value="${esc(context.marketId)}"><input type="hidden" name="requested_space_type" value="${esc(label(propertyType))}"><input type="hidden" name="space_type" value="${esc(label(propertyType))}"><input type="hidden" name="routing_space_type" value="${esc(propertyType)}"><input type="hidden" name="space_needed" value="${esc(size || "To investigate")}"><input type="hidden" name="timing" value="${esc(timing || "Flexible / to confirm")}"><input type="hidden" name="requirements" value="${esc(requirements)}"><input type="hidden" name="location_brief_v2_public_id" value="${esc(bundle.brief.publicId)}"><input type="hidden" name="investigation_requested" value="yes"><input type="hidden" name="investigation_status" value="requested"><input type="hidden" name="human_check" value="1">
    <label>Name<input name="name" autocomplete="name" required></label><label>Work email<input type="email" name="email" autocomplete="email" required></label><label>Phone <span class="research__note">optional</span><input type="tel" name="phone" autocomplete="tel"></label><p class="research__note">Rofo may use a local commercial real estate expert to review the search and follow up when useful. No response timing or specific availability is promised.</p><button type="submit">Share My Search with Rofo</button><p class="research__status" data-research-status aria-live="polite"></p></form><a class="research__back" href="${esc(briefUrl)}">← Back to my Location Brief</a></section><aside class="research__card"><h2>Your research context</h2><dl class="research__facts"><div><dt>Starting market</dt><dd>${esc(market)}</dd></div><div><dt>Space type</dt><dd>${esc(label(propertyType))}</dd></div>${context.business ? `<div><dt>Business / use</dt><dd>${esc(context.business)}</dd></div>` : ""}${size ? `<div><dt>Approximate need</dt><dd>${esc(size)}</dd></div>` : ""}${locations.length ? `<div><dt>Locations</dt><dd>${esc(locations.join(" · "))}</dd></div>` : ""}</dl>${topics.length ? `<h3>What Rofo will investigate</h3><ul>${topics.map((topic) => `<li>${esc(topic)}</li>`).join("")}</ul>` : ""}</aside></div></main><script>(function(){var form=document.querySelector('[data-research-form]'),status=document.querySelector('[data-research-status]'),journeyId='';try{journeyId=sessionStorage.getItem('rofoVnextJourneyId')||''}catch(error){}if(!form)return;form.addEventListener('submit',async function(event){event.preventDefault();var button=form.querySelector('button');button.disabled=true;status.textContent='Sharing your search…';try{var response=await fetch(form.action,{method:'POST',headers:{accept:'application/json'},body:new FormData(form)});var result=await response.json();if(!response.ok)throw new Error(result.error||'The search could not be shared.');status.textContent='Your search has been shared with Rofo. Your Location Brief and requirements were included.';button.textContent='Search shared';fetch('/api/analytics/search-profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event_name:'vnext_research_submitted',profile_version:'location-brief:v2',context:{page_type:'research_search',page_url:location.pathname,city:${JSON.stringify(market)},space_type:${JSON.stringify(propertyType)},journey_id:journeyId},profile:{space_type:${JSON.stringify(propertyType)}},attribution:{entry_page_type:${JSON.stringify(context.sourceType)},session_id:journeyId}}),keepalive:true}).catch(function(){});}catch(error){status.textContent=error.message;button.disabled=false;}});})();</script></body></html>`;
}

export async function onRequestGet({ request, env, params }) {
  if (!/^LB2-[A-F0-9]{24}$/i.test(params.publicId || "")) return privateHtml("Location Brief not found.", 404);
  const bundle = await getBriefBundle(env, params.publicId, false);
  if (!bundle) return privateHtml("Location Brief not found.", 404);
  if (!await ownsBrief(request, bundle.brief)) return privateHtml("Open this page from the browser that owns the Location Brief.", 403);
  return privateHtml(render(bundle), 200, { "referrer-policy": "same-origin" });
}
