module.exports = {
  schemaVersion: "commercial-knowledge-strategic-priorities-v1",
  updatedAt: "2026-08-07",
  note: "Strategic priority is editor-controlled. Google demand may inform Publisher work, but it does not override Rofo's market roadmap.",
  priorities: [
    {
      marketId: "san-francisco",
      marketName: "San Francisco",
      state: "CA",
      priority: "core",
      score: 100,
      category: "strategic_expansion",
      rationale: "Primary validated market for office recommendation models, Location Briefs, Business Briefs, district coverage, and broker execution.",
    },
    {
      marketId: "denver",
      marketName: "Denver",
      state: "CO",
      priority: "high",
      score: 85,
      category: "strategic_expansion",
      rationale: "Second office market used to prove portability of Commercial Knowledge System publishing and recommendation readiness.",
    },
    {
      marketId: "orange-county",
      marketName: "Orange County",
      state: "CA",
      priority: "high",
      score: 78,
      category: "strategic_expansion",
      rationale: "Important Southern California expansion market with multi-city commercial demand and future occupier workflows.",
    },
    {
      marketId: "los-angeles",
      marketName: "Los Angeles",
      state: "CA",
      priority: "high",
      score: 76,
      category: "strategic_expansion",
      rationale: "Large strategic market with broad property-type demand and district-level commercial complexity.",
    },
    {
      marketId: "seattle",
      marketName: "Seattle",
      state: "WA",
      priority: "medium",
      score: 68,
      category: "strategic_expansion",
      rationale: "Future office-oriented market with technology, professional services, and regional headquarters relevance.",
    },
  ],
};
