const regions = [
  {
    regionId: "bay-area",
    regionName: "Bay Area",
    state: "CA",
    status: "active",
    purpose: "Groups separately operated Bay Area commercial markets without assigning district ownership.",
  },
  {
    regionId: "northern-california",
    regionName: "Northern California",
    state: "CA",
    status: "active",
    purpose: "Groups Northern California markets outside the Bay Area operating region.",
  },
  {
    regionId: "southern-california",
    regionName: "Southern California",
    state: "CA",
    status: "active",
    purpose: "Groups separately operated Southern California commercial markets.",
  },
  {
    regionId: "mountain-west",
    regionName: "Mountain West",
    state: "CO",
    status: "active",
    purpose: "Groups Mountain West commercial markets.",
  },
  {
    regionId: "pacific-northwest",
    regionName: "Pacific Northwest",
    state: "WA",
    status: "active",
    purpose: "Groups Pacific Northwest commercial markets.",
  },
];

const markets = [
  {
    marketId: "san-francisco",
    marketName: "San Francisco",
    regionId: "bay-area",
    regionName: "Bay Area",
    state: "CA",
    cities: ["San Francisco"],
    status: "active",
    publisherCompatibility: { metroId: "san-francisco", metroName: "San Francisco" },
    publicRoute: "/commercial-real-estate/CA/san-francisco/",
  },
  {
    marketId: "east-bay",
    marketName: "East Bay",
    regionId: "bay-area",
    regionName: "Bay Area",
    state: "CA",
    cities: ["Oakland", "Berkeley", "Emeryville", "Hayward", "Union City", "Fremont"],
    status: "active",
    publisherCompatibility: { metroId: "san-francisco", metroName: "San Francisco" },
    publicRoute: "",
  },
  {
    marketId: "south-bay",
    marketName: "South Bay",
    regionId: "bay-area",
    regionName: "Bay Area",
    state: "CA",
    cities: ["Mountain View", "Sunnyvale", "San Jose"],
    status: "active",
    publisherCompatibility: { metroId: "san-francisco", metroName: "San Francisco" },
    publicRoute: "",
  },
  {
    marketId: "peninsula",
    marketName: "Peninsula",
    regionId: "bay-area",
    regionName: "Bay Area",
    state: "CA",
    cities: ["Palo Alto", "Redwood City", "San Mateo"],
    status: "active",
    publisherCompatibility: { metroId: "san-francisco", metroName: "San Francisco" },
    publicRoute: "",
  },
  {
    marketId: "north-bay",
    marketName: "North Bay",
    regionId: "bay-area",
    regionName: "Bay Area",
    state: "CA",
    cities: ["San Rafael", "Novato", "Petaluma", "Santa Rosa", "Napa", "Sausalito"],
    status: "active",
    publisherCompatibility: { metroId: "san-francisco", metroName: "San Francisco" },
    publicRoute: "",
    implementationNote: "Active Market registry entry; no canonical Knowledge Graph district is currently assigned.",
  },
  {
    marketId: "sacramento",
    marketName: "Sacramento",
    regionId: "northern-california",
    regionName: "Northern California",
    state: "CA",
    cities: ["Sacramento", "West Sacramento", "Rancho Cordova", "Folsom", "Roseville", "Rocklin", "Elk Grove", "Davis"],
    status: "active",
    publisherCompatibility: { metroId: "sacramento", metroName: "Sacramento" },
    publicRoute: "/commercial-real-estate/CA/sacramento/",
  },
  {
    marketId: "san-diego",
    marketName: "San Diego",
    regionId: "southern-california",
    regionName: "Southern California",
    state: "CA",
    cities: ["San Diego", "Carlsbad", "Oceanside", "Vista", "San Marcos", "Escondido", "Encinitas", "Del Mar", "Poway", "Santee", "Chula Vista"],
    status: "active",
    publisherCompatibility: { metroId: "san-diego", metroName: "San Diego" },
    publicRoute: "/commercial-real-estate/CA/san-diego/",
  },
  {
    marketId: "orange-county",
    marketName: "Orange County",
    regionId: "southern-california",
    regionName: "Southern California",
    state: "CA",
    cities: ["Irvine", "Newport Beach", "Costa Mesa", "Santa Ana", "Anaheim", "Tustin", "Lake Forest", "Mission Viejo", "Laguna Hills", "Huntington Beach", "Fullerton", "Orange"],
    status: "active",
    publisherCompatibility: { metroId: "orange-county", metroName: "Orange County" },
    publicRoute: "/commercial-real-estate/CA/orange-county/",
  },
  {
    marketId: "los-angeles",
    marketName: "Los Angeles",
    regionId: "southern-california",
    regionName: "Southern California",
    state: "CA",
    cities: ["Los Angeles", "Burbank", "Glendale", "Culver City", "Santa Monica", "El Segundo", "Torrance", "Long Beach", "Carson", "Commerce", "Vernon", "City of Industry", "Santa Fe Springs", "Pasadena"],
    status: "active",
    publisherCompatibility: { metroId: "", metroName: "" },
    publicRoute: "/commercial-real-estate/CA/los-angeles/",
  },
  {
    marketId: "denver",
    marketName: "Denver",
    regionId: "mountain-west",
    regionName: "Mountain West",
    state: "CO",
    cities: ["Denver", "Boulder", "Aurora", "Lakewood", "Golden", "Arvada", "Westminster", "Broomfield", "Louisville", "Superior", "Longmont", "Thornton", "Northglenn", "Glendale", "Englewood", "Centennial", "Commerce City", "Lone Tree"],
    status: "active",
    publisherCompatibility: { metroId: "denver", metroName: "Denver" },
    publicRoute: "/commercial-real-estate/CO/denver/",
  },
  {
    marketId: "seattle",
    marketName: "Seattle",
    regionId: "pacific-northwest",
    regionName: "Pacific Northwest",
    state: "WA",
    cities: ["Seattle", "Bellevue", "Redmond", "Kirkland", "Kent"],
    status: "active",
    publisherCompatibility: { metroId: "seattle", metroName: "Seattle" },
    publicRoute: "/commercial-real-estate/WA/seattle/",
  },
];

module.exports = {
  schemaVersion: "commercial-geography-v1",
  hierarchy: ["Region", "Market", "District"],
  regions,
  markets,
};
