const operationalSignals = {
  loading: "Loading",
  parking: "Parking",
  customerTraffic: "Customer traffic",
  visibility: "Visibility",
  transit: "Transit",
  power: "Power",
  ceilingHeight: "Ceiling height",
  officePercentage: "Office percentage",
  outdoorStorage: "Outdoor storage",
  ventilation: "Ventilation",
  plumbing: "Plumbing",
  labInfrastructure: "Lab infrastructure",
  deliveryAccess: "Delivery access",
  freewayAccess: "Freeway access",
  clientAccess: "Client access",
  patientAccess: "Patient access",
  employeeAmenities: "Employee amenities",
  foodInfrastructure: "Food infrastructure",
  security: "Security",
  signage: "Signage",
};

const ecosystems = [
  {
    id: "office",
    label: "Office",
    description: "Workplaces for knowledge work, administration, client service, headquarters, and team collaboration.",
    typicalBusinessActivities: ["knowledge_work", "client_meetings", "collaboration", "administrative_operations"],
    commonOperationalNeeds: ["transit", "parking", "clientAccess", "employeeAmenities", "visibility"],
    commonDistrictExpressions: ["Downtown office cores", "professional-service corridors", "creative office districts", "suburban office campuses"],
    subtypeIds: ["downtown_office", "professional_office", "creative_office", "executive_office", "suburban_office", "office_campus", "coworking", "government_office"],
    businessArchetypeIds: ["professional_office", "law_firm", "accounting_firm", "financial_services_firm", "consulting_firm", "marketing_agency", "creative_studio", "startup", "nonprofit_office", "government_contractor"],
  },
  {
    id: "industrial_flex",
    label: "Industrial & Flex",
    description: "Practical space for production, storage, distribution, service dispatch, trades, makers, and hybrid office-operational users.",
    typicalBusinessActivities: ["receiving", "shipping", "storage", "distribution", "service_dispatch", "light_manufacturing"],
    commonOperationalNeeds: ["loading", "deliveryAccess", "freewayAccess", "parking", "power", "ceilingHeight", "outdoorStorage"],
    commonDistrictExpressions: ["Industrial corridors", "small-bay service districts", "warehouse clusters", "R&D and flex parks"],
    subtypeIds: ["small_bay_industrial", "flex", "warehouse", "distribution", "light_manufacturing", "manufacturing", "contractor_service", "contractor_yard", "showroom_flex", "research_development", "last_mile_logistics", "food_production"],
    businessArchetypeIds: ["general_contractor", "electrician", "hvac_company", "plumbing_company", "landscaper", "cabinet_shop", "furniture_maker", "auto_repair_business", "food_producer", "light_manufacturer", "distributor", "wholesaler", "importer", "ecommerce_fulfillment_business", "equipment_service_company", "building_services_company"],
  },
  {
    id: "retail",
    label: "Retail",
    description: "Customer-facing space for storefront retail, local services, showrooms, shopping centers, and food-and-beverage uses.",
    typicalBusinessActivities: ["walk_in_retail", "walk_in_service", "customer_showroom", "food_preparation"],
    commonOperationalNeeds: ["visibility", "customerTraffic", "parking", "signage", "plumbing", "deliveryAccess"],
    commonDistrictExpressions: ["Neighborhood retail streets", "downtown retail corridors", "shopping centers", "showroom districts"],
    subtypeIds: ["neighborhood_retail", "downtown_retail", "shopping_center", "power_center", "lifestyle_retail", "service_retail", "showroom_retail"],
    businessArchetypeIds: ["marketing_agency", "wellness_practice", "food_producer", "training_center"],
  },
  {
    id: "medical",
    label: "Medical",
    description: "Care-delivery environments for medical, dental, wellness, therapy, and outpatient users.",
    typicalBusinessActivities: ["healthcare_delivery", "walk_in_service", "administrative_operations"],
    commonOperationalNeeds: ["patientAccess", "parking", "plumbing", "transit", "security"],
    commonDistrictExpressions: ["Hospital-adjacent clusters", "medical office corridors", "suburban patient-access districts"],
    subtypeIds: ["medical_office", "outpatient_clinic", "dental", "wellness", "hospital_adjacent"],
    businessArchetypeIds: ["medical_practice", "dental_practice", "physical_therapy_practice", "wellness_practice", "outpatient_clinic"],
  },
  {
    id: "life_science",
    label: "Life Science",
    description: "Research, lab, biotech, and innovation-campus environments where technical infrastructure and institutional adjacency matter.",
    typicalBusinessActivities: ["research", "product_development", "collaboration", "administrative_operations"],
    commonOperationalNeeds: ["labInfrastructure", "ventilation", "power", "loading", "security", "transit"],
    commonDistrictExpressions: ["Life-science campuses", "research parks", "institution-adjacent innovation districts"],
    subtypeIds: ["research_lab", "wet_lab", "life_science_office", "biotech_research", "innovation_campus"],
    businessArchetypeIds: ["research_company", "biotech_company", "startup"],
  },
  {
    id: "hospitality",
    label: "Hospitality",
    description: "Visitor-serving environments for lodging, food-and-beverage, event, and travel-oriented businesses.",
    typicalBusinessActivities: ["hospitality_service", "food_preparation", "walk_in_service"],
    commonOperationalNeeds: ["customerTraffic", "visibility", "parking", "transit", "foodInfrastructure", "signage"],
    commonDistrictExpressions: ["Hotel clusters", "visitor corridors", "event and entertainment districts"],
    subtypeIds: ["hotel", "food_beverage", "event_hospitality", "visitor_serving"],
    businessArchetypeIds: ["food_producer", "training_center"],
  },
  {
    id: "special_purpose",
    label: "Special Purpose",
    description: "Purpose-built or highly specific space where operational requirements matter more than conventional office, retail, or industrial labels.",
    typicalBusinessActivities: ["education", "training", "walk_in_service", "vehicle_storage"],
    commonOperationalNeeds: ["parking", "customerTraffic", "security", "plumbing", "outdoorStorage", "visibility"],
    commonDistrictExpressions: ["Institutional clusters", "automotive corridors", "education and service nodes"],
    subtypeIds: ["education", "nonprofit", "religious", "automotive", "self_storage", "recreation", "childcare", "institutional"],
    businessArchetypeIds: ["education_provider", "training_center", "childcare_provider", "nonprofit_office", "auto_repair_business"],
  },
];

const ecosystemSubtypes = [
  ["downtown_office", "office", "Downtown office", "Office space in a central business district or major urban employment core."],
  ["professional_office", "office", "Professional office", "Office space suited to service firms, advisors, consultants, and local business operations."],
  ["creative_office", "office", "Creative office", "Office space where building character, adaptability, and less formal workplace identity matter."],
  ["executive_office", "office", "Executive office", "Client-facing office environments where arrival, address, and institutional image influence fit."],
  ["suburban_office", "office", "Suburban office", "Auto-accessible office environments outside the urban core."],
  ["office_campus", "office", "Office campus", "Lower-rise or campus-style office environments supporting larger teams and a quieter workplace setting."],
  ["coworking", "office", "Coworking", "Shared or flexible office environments for smaller teams and flexible commitments."],
  ["government_office", "office", "Government office", "Office environments shaped by civic, agency, public-sector, or government-adjacent activity."],
  ["small_bay_industrial", "industrial_flex", "Small-bay industrial", "Multi-tenant industrial buildings for trades, service businesses, makers, and small operators."],
  ["flex", "industrial_flex", "Flex", "Hybrid office-operational space supporting office, production, service, storage, or technical work."],
  ["warehouse", "industrial_flex", "Warehouse", "Storage-oriented industrial space where loading, clearance, and distribution access matter."],
  ["distribution", "industrial_flex", "Distribution", "Industrial space for regional or last-mile goods movement."],
  ["light_manufacturing", "industrial_flex", "Light manufacturing", "Production space for assembly, fabrication, makers, and lower-intensity manufacturing."],
  ["manufacturing", "industrial_flex", "Manufacturing", "Industrial space for heavier production and specialized building requirements."],
  ["contractor_service", "industrial_flex", "Contractor/service", "Operational space for trades, service dispatch, equipment, and crews."],
  ["contractor_yard", "industrial_flex", "Contractor yard", "Industrial or service land requiring outdoor storage, vehicle staging, or yard utility."],
  ["showroom_flex", "industrial_flex", "Showroom flex", "Hybrid showroom, office, and operations space for products or services that need customer-facing display and back-of-house utility."],
  ["research_development", "industrial_flex", "Research and development", "Technical office/flex environments for engineering, testing, prototyping, and product development."],
  ["last_mile_logistics", "industrial_flex", "Last-mile logistics", "Distribution space oriented to local delivery reach and service territory coverage."],
  ["food_production", "industrial_flex", "Food production", "Production or commissary environments for food manufacturing, preparation, or distribution."],
  ["neighborhood_retail", "retail", "Neighborhood retail", "Local-serving retail and service space tied to nearby residents, workers, or daily errands."],
  ["downtown_retail", "retail", "Downtown retail", "Retail and service space tied to central employment, visitor, or mixed-use activity."],
  ["shopping_center", "retail", "Shopping center", "Multi-tenant retail centers with co-tenancy, parking, and customer-draw considerations."],
  ["power_center", "retail", "Power center", "Large-format retail centers shaped by regional customer access and parking."],
  ["lifestyle_retail", "retail", "Lifestyle retail", "Retail environments combining shopping, restaurants, services, and customer experience."],
  ["service_retail", "retail", "Service retail", "Customer-facing service businesses such as wellness, personal services, repair, or daily-needs uses."],
  ["showroom_retail", "retail", "Showroom retail", "Retail or showroom environments for design, furnishings, products, and appointment-driven customers."],
  ["medical_office", "medical", "Medical office", "Office environments designed or used for medical practices and healthcare administration."],
  ["outpatient_clinic", "medical", "Outpatient clinic", "Healthcare-delivery space for regular patient visits without hospital admission."],
  ["dental", "medical", "Dental", "Dental-practice space where plumbing, patient access, and buildout matter."],
  ["wellness", "medical", "Wellness", "Patient or client-care environments for therapy, wellness, and health-adjacent services."],
  ["hospital_adjacent", "medical", "Hospital adjacent", "Medical space shaped by proximity to hospitals or health systems."],
  ["research_lab", "life_science", "Research lab", "Research space with technical infrastructure needs."],
  ["wet_lab", "life_science", "Wet lab", "Laboratory environments requiring specialized plumbing, ventilation, safety, and power considerations."],
  ["life_science_office", "life_science", "Life-science office", "Office space serving life-science, biotech, healthcare, or research organizations."],
  ["biotech_research", "life_science", "Biotech research", "Research environments for biotech and related technical teams."],
  ["innovation_campus", "life_science", "Innovation campus", "Campus-style research, office, and technical environments tied to innovation ecosystems."],
  ["hotel", "hospitality", "Hotel", "Visitor lodging environments."],
  ["food_beverage", "hospitality", "Food and beverage", "Restaurant, cafe, bar, catering, and related visitor-serving food environments."],
  ["event_hospitality", "hospitality", "Event hospitality", "Event-oriented space for gatherings, entertainment, or hospitality uses."],
  ["visitor_serving", "hospitality", "Visitor serving", "Businesses whose location logic depends on visitors, tourism, or travel patterns."],
  ["education", "special_purpose", "Education", "Instructional or learning environments."],
  ["nonprofit", "special_purpose", "Nonprofit", "Mission-oriented organizational space that may blend office, service, and community uses."],
  ["religious", "special_purpose", "Religious", "Faith-based or congregation-oriented property uses."],
  ["automotive", "special_purpose", "Automotive", "Vehicle sales, repair, storage, service, or related automotive uses."],
  ["self_storage", "special_purpose", "Self-storage", "Storage facilities serving consumers or businesses."],
  ["recreation", "special_purpose", "Recreation", "Fitness, sport, entertainment, or recreation-oriented facilities."],
  ["childcare", "special_purpose", "Childcare", "Childcare or early-education space with licensing, access, and outdoor-area considerations."],
  ["institutional", "special_purpose", "Institutional", "Civic, educational, public, or institutional environments that do not behave like conventional commercial inventory."],
].map(([id, ecosystemId, label, description]) => ({ id, ecosystemId, label, description }));

const businessActivities = [
  ["knowledge_work", "Knowledge work", "Desk-based work, analysis, writing, management, and professional collaboration.", ["office"], ["downtown_office", "professional_office", "creative_office"], ["transit", "parking", "employeeAmenities"]],
  ["client_meetings", "Client meetings", "Regular client, customer, investor, or partner visits to the workplace.", ["office"], ["executive_office", "professional_office", "downtown_office"], ["clientAccess", "parking", "transit", "visibility"]],
  ["collaboration", "Collaboration", "Team-based work requiring meeting areas, shared workspaces, and employee amenities.", ["office", "life_science"], ["creative_office", "office_campus", "innovation_campus"], ["employeeAmenities", "transit", "parking"]],
  ["administrative_operations", "Administrative operations", "Back-office, administrative, support, and management functions.", ["office", "medical", "special_purpose"], ["professional_office", "medical_office"], ["parking", "transit", "security"]],
  ["healthcare_delivery", "Healthcare delivery", "Direct patient care or health-related service delivery.", ["medical"], ["medical_office", "outpatient_clinic", "dental", "wellness"], ["patientAccess", "parking", "plumbing"]],
  ["research", "Research", "Scientific, technical, product, or institutional research activity.", ["life_science", "industrial_flex"], ["research_lab", "biotech_research", "research_development"], ["labInfrastructure", "power", "ventilation"]],
  ["product_development", "Product development", "Engineering, prototyping, testing, and product-team work.", ["office", "industrial_flex", "life_science"], ["research_development", "creative_office", "innovation_campus"], ["power", "parking", "loading"]],
  ["assembly", "Assembly", "Putting products, components, or materials together in a lower-intensity production environment.", ["industrial_flex"], ["light_manufacturing", "flex"], ["power", "loading", "parking"]],
  ["light_manufacturing", "Light manufacturing", "Production work that typically requires industrial utility without heavy manufacturing assumptions.", ["industrial_flex"], ["light_manufacturing", "small_bay_industrial", "flex"], ["power", "loading", "ventilation"]],
  ["manufacturing", "Manufacturing", "Higher-intensity production with specialized power, loading, zoning, or building requirements.", ["industrial_flex"], ["manufacturing"], ["power", "loading", "ceilingHeight", "outdoorStorage"]],
  ["storage", "Storage", "Keeping goods, equipment, products, materials, or records on site.", ["industrial_flex", "special_purpose"], ["warehouse", "small_bay_industrial", "self_storage"], ["loading", "ceilingHeight", "security"]],
  ["inventory_management", "Inventory management", "Receiving, organizing, and managing product or materials for sale, service, or distribution.", ["industrial_flex", "retail"], ["warehouse", "distribution", "showroom_flex"], ["loading", "deliveryAccess", "officePercentage"]],
  ["receiving", "Receiving", "Inbound deliveries from vendors, suppliers, or customers.", ["industrial_flex", "retail", "hospitality"], ["warehouse", "distribution", "food_production"], ["loading", "deliveryAccess", "parking"]],
  ["shipping", "Shipping", "Outbound movement of goods, packages, products, or materials.", ["industrial_flex"], ["distribution", "warehouse", "last_mile_logistics"], ["loading", "deliveryAccess", "freewayAccess"]],
  ["distribution", "Distribution", "Moving goods across a service territory, region, or customer base.", ["industrial_flex"], ["distribution", "last_mile_logistics", "warehouse"], ["freewayAccess", "loading", "ceilingHeight"]],
  ["service_dispatch", "Service dispatch", "Dispatching crews, vehicles, technicians, or equipment to jobsites.", ["industrial_flex"], ["contractor_service", "small_bay_industrial", "contractor_yard"], ["parking", "outdoorStorage", "freewayAccess"]],
  ["vehicle_storage", "Vehicle storage", "Storing service vehicles, fleet vehicles, customer vehicles, or trailers.", ["industrial_flex", "special_purpose"], ["contractor_yard", "automotive"], ["outdoorStorage", "parking", "security"]],
  ["equipment_storage", "Equipment storage", "Storing tools, machines, materials, or specialty equipment.", ["industrial_flex"], ["contractor_service", "small_bay_industrial", "contractor_yard"], ["outdoorStorage", "loading", "security"]],
  ["customer_showroom", "Customer showroom", "Displaying products or services for appointment-driven or walk-in customers.", ["retail", "industrial_flex"], ["showroom_retail", "showroom_flex"], ["visibility", "customerTraffic", "parking"]],
  ["walk_in_service", "Walk-in service", "Customer-facing services where access, parking, and visibility shape demand.", ["retail", "medical", "special_purpose"], ["service_retail", "wellness", "automotive"], ["customerTraffic", "parking", "visibility"]],
  ["walk_in_retail", "Walk-in retail", "Storefront sales or services to walk-in customers.", ["retail"], ["neighborhood_retail", "downtown_retail", "shopping_center"], ["visibility", "customerTraffic", "signage"]],
  ["food_preparation", "Food preparation", "Preparing food for on-site consumption, catering, or service.", ["retail", "hospitality"], ["food_beverage", "neighborhood_retail"], ["plumbing", "ventilation", "deliveryAccess"]],
  ["food_production", "Food production", "Producing, packaging, or distributing food products.", ["industrial_flex"], ["food_production"], ["foodInfrastructure", "loading", "ventilation"]],
  ["education", "Education", "Teaching, learning, or classroom activity.", ["special_purpose"], ["education", "institutional"], ["parking", "customerTraffic", "security"]],
  ["training", "Training", "Instructional, certification, workforce, or customer-training activity.", ["special_purpose", "office"], ["education", "professional_office"], ["parking", "transit", "customerTraffic"]],
  ["hospitality_service", "Hospitality service", "Visitor, event, lodging, food, or guest-service operations.", ["hospitality"], ["hotel", "event_hospitality", "visitor_serving"], ["customerTraffic", "parking", "foodInfrastructure"]],
].map(([id, label, description, ecosystemIds, subtypeIds, signals]) => ({ id, label, description, ecosystemIds, subtypeIds, commonOperationalSignals: signals }));

const businessArchetypes = [
  ["professional_office", "Professional office", "A service-oriented office user that balances employee access, client visits, and operating cost.", ["knowledge_work", "client_meetings"], ["administrative_operations"], ["office"], ["retail"], ["clientAccess", "transit", "parking"], ["formal address versus cost and flexibility"]],
  ["law_firm", "Law firm", "A client-facing professional office user that often values credibility, meeting space, transit, and courthouse or downtown access.", ["knowledge_work", "client_meetings"], ["administrative_operations"], ["office"], [], ["clientAccess", "transit", "parking"], ["formal downtown presence versus cost"]],
  ["accounting_firm", "Accounting firm", "A professional-service office user balancing client access, employee commute, confidentiality, and seasonal workflow.", ["knowledge_work", "client_meetings"], ["administrative_operations"], ["office"], [], ["clientAccess", "parking", "transit"], ["client-facing image versus practical occupancy cost"]],
  ["financial_services_firm", "Financial services firm", "A client-facing office user that may value recognizable business districts, visitor experience, and transit access.", ["knowledge_work", "client_meetings"], ["administrative_operations"], ["office"], [], ["clientAccess", "transit", "security"], ["image and access versus flexibility"]],
  ["consulting_firm", "Consulting firm", "A knowledge-work user that may prioritize client access, employee commute, flexible collaboration, and brand signal.", ["knowledge_work", "client_meetings", "collaboration"], [], ["office"], [], ["transit", "clientAccess", "employeeAmenities"], ["client convenience versus team commute patterns"]],
  ["marketing_agency", "Marketing agency", "A creative office user that may value adaptable space, client presentation, neighborhood identity, and collaboration.", ["knowledge_work", "collaboration", "client_meetings"], [], ["office"], ["retail"], ["employeeAmenities", "visibility", "transit"], ["creative identity versus traditional client-facing formality"]],
  ["creative_studio", "Creative studio", "A creative or production-adjacent user that may need flexible layouts, character, occasional client visits, and practical access.", ["collaboration", "product_development", "client_meetings"], [], ["office"], ["industrial_flex"], ["loading", "visibility", "parking"], ["character versus efficiency and systems"]],
  ["startup", "Startup", "A growth-oriented team that may prioritize talent access, flexibility, collaboration, transit, and the ability to scale.", ["knowledge_work", "collaboration", "product_development"], [], ["office"], ["life_science", "industrial_flex"], ["transit", "employeeAmenities", "parking"], ["flexibility versus cost and brand signal"]],
  ["nonprofit_office", "Nonprofit office", "A mission-oriented office user balancing access, cost, staff commute, community presence, and service delivery.", ["administrative_operations", "client_meetings"], ["walk_in_service"], ["office"], ["special_purpose"], ["transit", "parking", "customerTraffic"], ["mission access versus office image"]],
  ["government_contractor", "Government contractor", "An office user that may need government-adjacent geography, security, meeting space, and reliable access.", ["knowledge_work", "client_meetings"], ["administrative_operations"], ["office"], [], ["security", "clientAccess", "transit"], ["agency access versus broader hiring geography"]],
  ["medical_practice", "Medical practice", "A patient-facing healthcare user that needs reliable access, parking or transit, and medical office compatibility.", ["healthcare_delivery"], ["administrative_operations"], ["medical"], ["office"], ["patientAccess", "parking", "plumbing"], ["patient access versus occupancy cost"]],
  ["dental_practice", "Dental practice", "A healthcare user with specialized plumbing, patient access, parking, and buildout considerations.", ["healthcare_delivery"], ["administrative_operations"], ["medical"], [], ["plumbing", "patientAccess", "parking"], ["specialized buildout versus location flexibility"]],
  ["physical_therapy_practice", "Physical therapy practice", "A healthcare and wellness user that may need patient access, parking, ground-floor convenience, and open treatment areas.", ["healthcare_delivery"], ["walk_in_service"], ["medical"], ["retail"], ["patientAccess", "parking", "visibility"], ["access and parking versus medical-office ecosystem"]],
  ["wellness_practice", "Wellness practice", "A patient or client-service user balancing customer access, visibility, comfort, and cost.", ["healthcare_delivery", "walk_in_service"], [], ["medical"], ["retail"], ["patientAccess", "visibility", "parking"], ["retail visibility versus clinical functionality"]],
  ["outpatient_clinic", "Outpatient clinic", "A healthcare-delivery user with patient flow, access, operational reliability, and medical buildout needs.", ["healthcare_delivery"], ["administrative_operations"], ["medical"], [], ["patientAccess", "parking", "security"], ["patient reach versus specialized facility requirements"]],
  ["general_contractor", "General contractor", "A trades or service business needing dispatch, equipment storage, vehicles, and access to jobsite geography.", ["service_dispatch", "equipment_storage"], ["administrative_operations"], ["industrial_flex"], ["office"], ["parking", "outdoorStorage", "freewayAccess"], ["yard and access versus client-facing image"]],
  ["electrician", "Electrician", "A service business needing dispatch, vehicle parking, parts storage, and practical regional access.", ["service_dispatch", "equipment_storage"], ["inventory_management"], ["industrial_flex"], [], ["parking", "deliveryAccess", "freewayAccess"], ["operational access versus polished office environment"]],
  ["hvac_company", "HVAC company", "A service business needing equipment storage, dispatch, loading, vehicles, and freeway access.", ["service_dispatch", "equipment_storage", "receiving"], [], ["industrial_flex"], [], ["loading", "parking", "outdoorStorage"], ["yard utility versus customer-facing location"]],
  ["plumbing_company", "Plumbing company", "A trades business needing dispatch, storage, service vehicles, and practical loading.", ["service_dispatch", "equipment_storage"], ["receiving"], ["industrial_flex"], [], ["parking", "loading", "outdoorStorage"], ["service geography versus building polish"]],
  ["landscaper", "Landscaper", "A service business often needing vehicles, equipment, materials, yard capacity, and access to customer territories.", ["service_dispatch", "equipment_storage", "vehicle_storage"], [], ["industrial_flex"], ["special_purpose"], ["outdoorStorage", "parking", "freewayAccess"], ["outdoor storage versus zoning and visibility"]],
  ["cabinet_shop", "Cabinet shop", "A maker or fabrication user needing production space, loading, power, storage, and sometimes showroom access.", ["light_manufacturing", "assembly", "customer_showroom"], ["receiving"], ["industrial_flex"], ["retail"], ["power", "loading", "ventilation"], ["production utility versus showroom identity"]],
  ["furniture_maker", "Furniture maker", "A maker or light manufacturer needing production, storage, loading, and possible customer showroom space.", ["light_manufacturing", "assembly", "customer_showroom"], [], ["industrial_flex"], ["retail"], ["loading", "power", "visibility"], ["character and showroom access versus industrial utility"]],
  ["auto_repair_business", "Auto repair business", "An automotive service user needing vehicle access, service bays, parking, and compatible zoning.", ["walk_in_service", "vehicle_storage"], ["equipment_storage"], ["special_purpose"], ["industrial_flex"], ["parking", "outdoorStorage", "visibility"], ["customer access versus zoning limits"]],
  ["food_producer", "Food producer", "A production user needing food preparation or production infrastructure, loading, storage, and distribution access.", ["food_production", "receiving", "shipping"], [], ["industrial_flex"], ["hospitality"], ["foodInfrastructure", "loading", "ventilation"], ["production compliance versus customer-facing location"]],
  ["light_manufacturer", "Light manufacturer", "A production user needing power, loading, storage, and practical labor and freight access.", ["light_manufacturing", "assembly"], ["receiving", "shipping"], ["industrial_flex"], [], ["power", "loading", "parking"], ["production utility versus office identity"]],
  ["distributor", "Distributor", "A goods-movement user needing warehouse, loading, delivery access, and service territory reach.", ["distribution", "shipping", "receiving"], ["inventory_management"], ["industrial_flex"], [], ["loading", "freewayAccess", "ceilingHeight"], ["regional reach versus customer-facing presence"]],
  ["wholesaler", "Wholesaler", "A business managing inventory, customer pickup, distribution, and sometimes showroom or counter sales.", ["inventory_management", "receiving", "shipping"], ["customer_showroom"], ["industrial_flex"], ["retail"], ["loading", "parking", "visibility"], ["industrial utility versus customer access"]],
  ["importer", "Importer", "A goods-based business needing receiving, storage, distribution, customs or port/airport access where relevant.", ["receiving", "storage", "distribution"], [], ["industrial_flex"], [], ["deliveryAccess", "loading", "freewayAccess"], ["logistics access versus labor and occupancy cost"]],
  ["ecommerce_fulfillment_business", "E-commerce fulfillment business", "A fulfillment user needing storage, packing, shipping, loading, and last-mile or carrier access.", ["storage", "inventory_management", "shipping"], [], ["industrial_flex"], [], ["loading", "deliveryAccess", "ceilingHeight"], ["throughput needs versus building cost"]],
  ["equipment_service_company", "Equipment service company", "A service and repair user needing storage, dispatch, receiving, and sometimes customer pickup.", ["service_dispatch", "equipment_storage", "receiving"], [], ["industrial_flex"], [], ["loading", "parking", "outdoorStorage"], ["service access versus customer-facing polish"]],
  ["building_services_company", "Building-services company", "A facilities, janitorial, maintenance, or building-services user needing dispatch, supplies, vehicles, and regional access.", ["service_dispatch", "storage", "vehicle_storage"], [], ["industrial_flex"], [], ["parking", "storage", "freewayAccess"], ["operational utility versus office image"]],
  ["research_company", "Research company", "A technical user needing research infrastructure, talent access, institutional adjacency, and operational flexibility.", ["research", "product_development"], ["knowledge_work"], ["life_science"], ["industrial_flex", "office"], ["labInfrastructure", "power", "transit"], ["technical infrastructure versus cost and flexibility"]],
  ["biotech_company", "Biotech company", "A life-science user that may require lab capability, research adjacency, specialized systems, and talent access.", ["research", "product_development"], ["collaboration"], ["life_science"], ["office"], ["labInfrastructure", "ventilation", "power"], ["lab fit versus office flexibility"]],
  ["education_provider", "Education provider", "A teaching or training user needing access, classroom capacity, safety, and sometimes specialized facilities.", ["education"], ["training"], ["special_purpose"], ["office"], ["parking", "transit", "security"], ["student access versus facility constraints"]],
  ["training_center", "Training center", "A workforce, customer, or professional training user needing classroom space, access, parking, and scheduling flexibility.", ["training"], ["client_meetings"], ["special_purpose"], ["office"], ["parking", "transit", "customerTraffic"], ["access and parking versus office polish"]],
  ["childcare_provider", "Childcare provider", "A care and education user with licensing, drop-off, outdoor-area, safety, and neighborhood-access needs.", ["education", "walk_in_service"], [], ["special_purpose"], [], ["parking", "security", "customerTraffic"], ["licensing and outdoor needs versus available building formats"]],
].map(([id, label, description, primaryActivities, secondaryActivities, preferredEcosystems, possibleAlternatives, commonOperationalRequirements, commonTradeoffs]) => ({
  id,
  label,
  description,
  primaryActivities,
  secondaryActivities,
  preferredEcosystems,
  possibleEcosystemAlternatives: possibleAlternatives,
  commonOperationalRequirements,
  commonTradeoffs,
  reviewNotes: "",
}));

function indexById(items) {
  return items.reduce((result, item) => {
    result[item.id] = item;
    return result;
  }, {});
}

module.exports = {
  operationalSignals,
  ecosystems,
  ecosystemSubtypes,
  businessActivities,
  businessArchetypes,
  ecosystemById: indexById(ecosystems),
  subtypeById: indexById(ecosystemSubtypes),
  activityById: indexById(businessActivities),
  archetypeById: indexById(businessArchetypes),
};
