"use strict";
const fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,"..");
const index=require("../data/internal/commercial-district-intelligence-batch-v1/index.json");
const labels={office:"Office",retail:"Retail",industrial:"Industrial",flex:"Flex"};
const slugs={office:"office-space",retail:"retail-space",industrial:"industrial-space",flex:"flex-space"};
const titles={office:"Explore Office Districts",retail:"Explore Retail Districts & Corridors",industrial:"Explore Industrial Districts",flex:"Explore Flex Districts"};
const typeLabels={OFFICE_DISTRICT:"Office district",INDUSTRIAL_DISTRICT:"Industrial district",INDUSTRIAL_CORRIDOR:"Industrial corridor",RETAIL_DISTRICT:"Retail district",RETAIL_CORRIDOR:"Retail corridor",MIXED_COMMERCIAL_DISTRICT:"Mixed commercial district",R_AND_D_TECHNICAL_CLUSTER:"Technical employment area"};
const releaseAllowlist=new Set(["denver","seattle","san-jose","atlanta","nashville","detroit","kansas-city"]);
const byMarket={},byMarketKey={};
for(const item of index.markets){if(!releaseAllowlist.has(item.id))continue;const record=JSON.parse(fs.readFileSync(path.join(root,"data/internal/commercial-district-intelligence-batch-v1",item.file),"utf8"));const base=`/commercial-real-estate/${record.market.state}/${record.market.id}/`;const bySpaceType={};for(const type of Object.keys(labels)){const raw=record.spaceTypes[type]||[];const geographies=raw.map(x=>({...x,geographyTypeLabel:typeLabels[x.geographyType]||"Commercial district",evidenceTier:x.publicEvidenceTier,routeState:"COMPONENT_ONLY",canonicalPath:null,grid:{group:"commercial-districts",order:x.gridOrder},description:x.shortDescription,commercialCharacter:x.whatStandsOut,areaPatterns:x.commonHere,access:x.accessReadiness==="OBJECTIVE_ACCESS_READY"?x.accessObservations:[],investigationBoundaries:x.worthKnowing,related:x.compareWith.map(id=>raw.find(y=>y.id===id)).filter(Boolean).slice(0,4).map(y=>({id:y.id,label:y.label,path:null}))}));bySpaceType[type]={id:type,label:labels[type],slug:slugs[type],path:`${base}${slugs[type]}/`,explorationTitle:titles[type],introduction:`Explore the ${record.market.label} districts most relevant to ${labels[type]} searches.`,geographies};}const experience={schemaVersion:"commercial-district-intelligence-batch-public:v1",city:{id:item.id,label:record.market.label,state:record.market.state,path:base},sourceSurfacePrefix:item.id,spaceTypes:Object.values(bySpaceType),bySpaceType,byGeographyId:{},availabilityFirewall:"Confirm current availability and the exact condition, configuration, access, and permitted use of any specific space."};byMarket[item.id]=experience;byMarketKey[`${record.market.state}/${item.id}`]=experience;}
module.exports={schemaVersion:"commercial-district-intelligence-batch-public:v1",releaseAllowlist:Object.freeze([...releaseAllowlist]),byMarket,byMarketKey};
