function clean(value) {
  return String(value || "").trim();
}

function slugify(value) {
  return clean(value)
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildingPath(address) {
  return `/commercial-real-estate/building/CO/denver/${slugify(address)}/`;
}

function district(id, name, slug, primarySpaceType) {
  return {
    id,
    name,
    slug,
    city: "Denver",
    state_abbr: "CO",
    area_type: "district",
    path: `/commercial-real-estate/CO/denver/${slug}/`,
    primarySpaceType,
  };
}

const districts = {
  downtown: district("den-downtown-denver", "Downtown Denver", "downtown-denver", "office"),
  lodo: district("den-lodo", "LoDo", "lodo", "office"),
  rino: district("den-rino", "RiNo", "rino", "office"),
  cherryCreek: district("den-cherry-creek", "Cherry Creek", "cherry-creek", "retail"),
  denverTechCenter: district("den-denver-tech-center", "Denver Tech Center", "denver-tech-center", "office"),
  centralPark: district("den-central-park", "Central Park", "central-park", "medical"),
};

const handbookTopics = [
  {
    title: "Choosing the Right Commercial Location",
    url: "/commercial-real-estate/lease-guide/choosing-the-right-commercial-location/",
    summary: "Use location fit, access, customers, employees, and operations before narrowing the building list.",
  },
  {
    title: "How to Compare Commercial Spaces",
    url: "/commercial-real-estate/lease-guide/how-to-compare-commercial-spaces/",
    summary: "Compare buildings by business fit, total occupancy cost, operations, buildout, and future flexibility.",
  },
  {
    title: "Tenant Improvements",
    url: "/commercial-real-estate/lease-guide/tenant-improvements/",
    summary: "Understand buildout scope, timing, landlord contributions, and what to validate before leasing.",
  },
];

const districtContext = {
  downtown: {
    workplaceCharacter: "Central Denver office environment shaped by civic, legal, finance, consulting, transit, and regional business identity.",
    neighborhoodCharacter: "Dense downtown business core where client access, institutional adjacency, and central identity matter more than parking convenience.",
    transit: "Downtown Denver offers stronger transit and civic access than most suburban nodes, while exact commute and parking patterns remain building-specific.",
    parking: "Structured or nearby parking should be validated early for client-facing and employee-heavy teams.",
    amenities: "Restaurants, hotels, civic institutions, professional services, and downtown services support client-facing office use.",
  },
  cherryCreek: {
    workplaceCharacter: "Polished customer-facing commercial environment where boutique office, service retail, wellness, and retail adjacency overlap.",
    neighborhoodCharacter: "Walkable, retail-oriented district with stronger customer and brand presence than back-office or warehouse utility.",
    transit: "Customer and employee access depends more on parking, local circulation, and trip patterns than rail-oriented commuting.",
    parking: "Parking, frontage, and arrival experience should be validated carefully for any customer-facing use.",
    amenities: "Retail, restaurants, hospitality, wellness, and client-service amenities are part of the district's business value.",
  },
  centralPark: {
    workplaceCharacter: "Northeast Denver mixed commercial environment where medical, office, retail, and local service uses serve growing residential and customer geography.",
    neighborhoodCharacter: "Parking-friendly and customer-oriented compared with downtown, with medical and service users evaluating access by patient geography.",
    transit: "Freeway and neighborhood access are usually more important than downtown transit identity.",
    parking: "Patient, visitor, employee, and accessible parking should be validated before assuming fit.",
    amenities: "Retail, service, and neighborhood amenities support patient-facing and local-service businesses.",
  },
  denverTechCenter: {
    workplaceCharacter: "Southeast Denver office environment shaped by corporate offices, professional services, regional headquarters, parking, and I-25 access.",
    neighborhoodCharacter: "Suburban office district where commute geography, parking, larger floorplates, and business-park practicality matter more than downtown walkability.",
    transit: "I-25 and southeast metro access are the primary location story; RTD and employee commute patterns should be validated against the exact building.",
    parking: "Parking is usually a stronger part of the DTC value proposition than in downtown Denver, but allocation, visitor access, and cost still require building-level validation.",
    amenities: "Office-support amenities, hotels, restaurants, and southeast metro services vary by building cluster and should be compared against employee and visitor needs.",
  },
};

function profileBrief(fields) {
  const snapshot = fields.snapshot || [];
  const bestFit = fields.bestFit || [];
  const validationNotes = fields.validationNotes || [];

  return {
    status: "published",
    ecosystemContext: {
      primaryEcosystem: fields.primaryEcosystem,
      ecosystemSubtypes: fields.ecosystemSubtypes,
      representativeRole: fields.representativeRole,
    },
    businessFit: {
      archetypes: fields.businessArchetypes,
      activities: fields.businessActivities,
      fitSummary: fields.fitSummary,
    },
    operationalProfile: fields.operationalProfile || [],
    environmentExplanation: fields.environmentExplanation,
    comparisonContext: {
      relatedDistricts: fields.relatedDistricts || [],
    },
    evidence: {
      confidence: fields.confidence || "editorially_supported",
      provenance: {
        ecosystem: "representative-building",
        operationalCharacteristics: "district-and-building-profile",
        editorialInterpretation: "building-brief",
      },
      sourceNotes: fields.sourceNotes || [],
    },
    summary: fields.summary,
    rofoTake: fields.rofoTake,
    buildingSummary: fields.summary,
    buildingImportance: fields.rofoTake,
    snapshot,
    quickFacts: snapshot,
    bestFit,
    idealFor: bestFit,
    mayNotFit: fields.mayNotFit || [],
    buildingExperience: fields.buildingExperience,
    locationContext: fields.locationContext,
    districtContext: fields.locationContext,
    advantages: fields.advantages || [],
    tradeoffs: fields.tradeoffs || [],
    validationNotes,
    validationChecklist: validationNotes,
    nearbyDistricts: fields.nearbyDistricts || [],
    nearbyAlternatives: fields.nearbyAlternatives || [],
    relatedInsights: handbookTopics,
    representativeCompanies: [],
    ecosystemSubtypes: fields.ecosystemSubtypes,
    representativeRole: fields.representativeRole,
    businessActivities: fields.businessActivities,
    businessArchetypes: fields.businessArchetypes,
    operationalCharacteristics: fields.operationalCharacteristics || [],
    fitSummary: fields.fitSummary,
    confidence: fields.confidence || "editorially_supported",
    sourceNotes: fields.sourceNotes || [],
  };
}

function record(fields) {
  const canonicalDistrict = districts[fields.districtKey];
  const defaults = districtContext[fields.districtKey];
  const path = buildingPath(fields.address);
  const brief = profileBrief(fields.brief);

  return {
    id: `co-denver-${slugify(fields.address)}`,
    building_path: path,
    identity: {
      name: fields.name,
      address: fields.address,
      city: "Denver",
      state_abbr: "CO",
      district: canonicalDistrict.name,
      canonicalDistrict,
      secondaryDistricts: fields.secondaryDistricts || [],
      buildingType: fields.buildingType,
      primarySpaceType: fields.primarySpaceType || canonicalDistrict.primarySpaceType,
      assetClass: fields.assetClass || "Representative Commercial Building",
    },
    editorial: {
      editorialRole: fields.editorialRole,
      editorialReason: fields.editorialReason,
      representativeThemes: fields.representativeThemes,
    },
    business: {
      businessFit: fields.businessFit,
      idealCompanyProfiles: brief.idealFor,
      companySizes: fields.companySizes || ["small and mid-sized businesses", "customer-facing teams", "professional and service operators"],
    },
    experience: {
      workplaceCharacter: defaults.workplaceCharacter,
      neighborhoodCharacter: defaults.neighborhoodCharacter,
      executivePresence: fields.executivePresence || "medium",
      innovationScore: fields.innovationScore || "moderate",
    },
    operations: {
      transit: defaults.transit,
      parking: defaults.parking,
      amenities: defaults.amenities,
      foodEnvironment: fields.foodEnvironment || "Food and service access should be evaluated by customer, employee, and visitor patterns.",
    },
    tradeoffs: {
      strengths: brief.advantages,
      limitations: brief.tradeoffs,
      businessesThatShouldCompare: brief.mayNotFit,
      nearbyAlternatives: fields.relatedDistrictPaths || [],
    },
    validation: {
      questionsToValidate: brief.validationNotes,
      tourObservations: brief.validationNotes.slice(0, 3),
    },
    relationships: {
      nearbyBuildings: (fields.nearbyBuildingPaths || []).slice(0, 5),
      comparisonBuildings: (fields.comparisonBuildingPaths || []).slice(0, 5),
      relatedDistricts: fields.relatedDistrictPaths || [],
    },
    quality: {
      sourceConfidence: fields.sourceConfidence || "medium",
      publicationStatus: "published",
      sourceBasis: "Denver Industrial & Flex Ecosystem Balance Sprint",
    },
    buildingBrief: brief,
  };
}

const records = [
  record({
    name: "1200 17th St",
    address: "1200 17th St",
    districtKey: "downtown",
    buildingType: "Downtown office",
    primarySpaceType: "office",
    editorialRole: "Downtown Class A Office Environment",
    editorialReason: "Provides Denver with an initial office Building Profile counterweight to the industrial/flex migration and explains Downtown Denver's central office operating model.",
    representativeThemes: ["Downtown office", "Client-facing identity", "Transit and civic access", "Professional services"],
    businessFit: ["law firms", "finance firms", "consulting firms", "regional professional offices"],
    relatedDistrictPaths: [districts.cherryCreek.path],
    nearbyBuildingPaths: [buildingPath("1600 Broadway"), buildingPath("1700 Lincoln St"), buildingPath("999 18th St")],
    comparisonBuildingPaths: [buildingPath("100 Fillmore Place"), buildingPath("4600 S Syracuse St"), buildingPath("1600 Broadway")],
    brief: {
      primaryEcosystem: "office",
      ecosystemSubtypes: ["downtown_office", "executive_office"],
      representativeRole: "downtown_class_a_office",
      businessActivities: ["knowledge_work", "client_meetings", "administrative_operations", "collaboration"],
      businessArchetypes: ["law_firm", "financial_services_firm", "consulting_firm", "professional_office"],
      operationalCharacteristics: ["professional_image", "large_floorplates", "structured_parking", "transit_access", "urban_core_access"],
      fitSummary: "Useful for professional-service and client-facing teams comparing central Denver office identity, access, and institutional adjacency.",
      summary: "1200 17th St helps explain Downtown Denver as a central office environment for legal, finance, consulting, and regional professional-service users. It is useful for businesses comparing whether civic access, client meetings, transit, and central business identity matter more than easier parking or suburban office scale.",
      rofoTake: "Denver's ecosystem picture should not be balanced only by industrial/flex depth. This profile gives office coverage a Building Profile benchmark without changing recommendation behavior.",
      snapshot: [
        { label: "Primary ecosystem", value: "Office" },
        { label: "Business use", value: "Downtown class A office environment" },
        { label: "District", value: "Downtown Denver" },
        { label: "Access context", value: "Central business district, civic, transit, and professional-service geography" },
        { label: "Comparison role", value: "Office counterweight to Denver industrial/flex Building Profile depth" },
      ],
      bestFit: [
        "Law, finance, consulting, and professional-service firms that value central Denver identity.",
        "Client-facing teams comparing downtown access against Cherry Creek or Denver Tech Center alternatives.",
        "Regional office users that need a recognizable Denver business address and access to downtown institutions.",
      ],
      mayNotFit: [
        "Parking-heavy back-office teams that may prefer Denver Tech Center or suburban office nodes.",
        "Industrial, flex, or warehouse users that need loading, yard, or production utility.",
      ],
      buildingExperience: "A tour should focus on arrival sequence, floorplate fit, transit and parking tradeoffs, client access, and how the downtown setting supports the business's operating model.",
      locationContext: "Downtown Denver is the metro's central civic, legal, finance, and regional office core. Compare Cherry Creek for a more boutique customer-facing environment and Denver Tech Center for parking-oriented corporate office scale.",
      advantages: [
        "Adds office Building Profile depth to balance Denver's industrial/flex brief concentration.",
        "Explains central Denver office identity for professional-service users.",
        "Supports comparison between downtown office, Cherry Creek, and southeast suburban office environments.",
      ],
      tradeoffs: [
        "Parking and commute friction may matter more than in suburban office nodes.",
        "Downtown identity may be less useful for teams whose customers or employees are concentrated outside central Denver.",
        "Office image does not solve operational needs such as loading, storage, production, or vehicle movement.",
      ],
      operationalProfile: [
        { label: "Client access", summary: "Downtown office users should evaluate whether central civic, legal, transit, and professional-service access improves client meetings and recruiting." },
        { label: "Parking and arrival", summary: "Parking, visitor arrival, and elevator or lobby experience should be validated before assuming a downtown building supports the team's daily pattern." },
      ],
      environmentExplanation: {
        whyItExists: "Downtown class A office environments exist for businesses that benefit from central identity, institutional access, client meetings, and professional-service clustering.",
        whyChooseThisEnvironment: "Choose this environment over industrial/flex when client-facing office identity matters more than loading or storage, and compare Cherry Creek or DTC when parking, customer geography, or suburban access is more important.",
        representativeValue: "1200 17th St gives Denver's office ecosystem an initial Building Profile benchmark.",
      },
      relatedDistricts: [{ districtId: "cherry-creek", reason: "Boutique client-facing office and retail adjacency alternative." }],
      nearbyAlternatives: [
        { label: "100 Fillmore Place", url: buildingPath("100 Fillmore Place"), reason: "Compare this when Cherry Creek client-facing identity and retail adjacency are more important than downtown office scale." },
        { label: "1600 Broadway", url: buildingPath("1600 Broadway"), reason: "Compare this as another Downtown Denver office reference before assuming one building defines the district." },
        { label: "4600 S Syracuse St", url: buildingPath("4600 S Syracuse St"), reason: "Compare this when Denver Tech Center parking and southeast suburban office access may fit better." },
      ],
      nearbyDistricts: [
        { label: "Cherry Creek", url: districts.cherryCreek.path, reason: "Compare when boutique client-facing identity and retail adjacency matter more than central downtown office scale." },
        { label: "Denver Tech Center", url: districts.denverTechCenter.path, reason: "Compare when southeast metro access, parking, or suburban office scale is the stronger operating driver." },
      ],
      validationNotes: ["Confirm parking strategy.", "Validate visitor arrival and security process.", "Confirm floorplate fit and expansion options.", "Compare downtown identity against Cherry Creek and DTC."],
      sourceNotes: ["Existing Denver graph representative building for Downtown Denver."],
    },
  }),
  record({
    name: "1600 Broadway",
    address: "1600 Broadway",
    districtKey: "downtown",
    buildingType: "Government-adjacent downtown office",
    primarySpaceType: "office",
    editorialRole: "Civic Access Office Environment",
    editorialReason: "Adds a Downtown Denver Building Profile for government-adjacent, administrative, and civic-facing office decisions around the Broadway and Lincoln corridor.",
    representativeThemes: ["Downtown office", "Civic access", "Government adjacency", "Administrative office"],
    businessFit: ["government-adjacent firms", "policy organizations", "consulting firms", "administrative offices"],
    relatedDistrictPaths: [districts.lodo.path, districts.cherryCreek.path, districts.denverTechCenter.path],
    nearbyBuildingPaths: [buildingPath("1200 17th St"), buildingPath("1700 Lincoln St"), buildingPath("999 18th St")],
    comparisonBuildingPaths: [buildingPath("1200 17th St"), buildingPath("1700 Lincoln St"), buildingPath("100 Fillmore Place")],
    brief: {
      primaryEcosystem: "office",
      ecosystemSubtypes: ["downtown_office", "civic_adjacent_office"],
      representativeRole: "government_office_environment",
      businessActivities: ["administrative_operations", "client_meetings", "stakeholder_meetings", "knowledge_work"],
      businessArchetypes: ["consulting_firm", "professional_office", "nonprofit", "government_adjacent_organization"],
      operationalCharacteristics: ["civic_access", "visitor_access", "professional_image", "transit_access", "structured_parking"],
      fitSummary: "Useful for teams comparing downtown civic access, public-sector adjacency, and central administrative context against more boutique or suburban alternatives.",
      summary: "1600 Broadway helps explain Downtown Denver as a civic-adjacent office environment for administrative, policy, consulting, nonprofit, and professional-service users. It is useful for teams weighing visitor access, public-sector proximity, downtown legitimacy, and central-market convenience against parking-led suburban office patterns.",
      rofoTake: "Downtown Denver needs more than one office benchmark. This profile adds the civic and government-adjacent side of the district without making unsupported claims about tenancy or current availability.",
      snapshot: [
        { label: "Primary ecosystem", value: "Office" },
        { label: "Business use", value: "Civic-adjacent downtown office environment" },
        { label: "District", value: "Downtown Denver" },
        { label: "Access context", value: "Broadway and Lincoln corridor, civic, administrative, and professional-service geography" },
        { label: "Comparison role", value: "Civic-access counterpoint to executive and transit-oriented downtown office profiles" },
      ],
      bestFit: [
        "Policy, consulting, nonprofit, administrative, and professional-service teams that value civic proximity.",
        "Organizations that host visitors or stakeholders and want a recognizable central Denver location.",
        "Office users comparing Downtown Denver's institutional access against Cherry Creek or Denver Tech Center alternatives.",
      ],
      mayNotFit: [
        "Teams whose daily pattern depends primarily on easy parking, suburban commute balance, or campus-style expansion.",
        "Creative or hospitality-adjacent users that may value LoDo or RiNo district character more than civic-office context.",
      ],
      buildingExperience: "A tour should focus on visitor arrival, security process, parking plan, transit access, meeting flow, and whether civic or institutional proximity meaningfully improves daily operations.",
      locationContext: "Downtown Denver is the metro's central civic, legal, finance, and professional office core. Compare LoDo for historic mixed-use texture, Cherry Creek for polished customer-facing identity, and Denver Tech Center for southeast metro office convenience.",
      advantages: [
        "Adds civic-access evidence to Downtown Denver's office Building Profile coverage.",
        "Helps explain why government-adjacent and stakeholder-facing organizations may prefer downtown.",
        "Supports comparison between formal downtown office, boutique client-facing, and suburban office settings.",
      ],
      tradeoffs: [
        "Civic access may not offset parking or commute friction for teams with dispersed suburban employees.",
        "Security, visitor routing, and meeting logistics should be validated before assuming daily fit.",
        "The downtown setting may feel more formal than creative users seeking RiNo or LoDo character want.",
      ],
      operationalProfile: [
        { label: "Stakeholder access", summary: "Civic-adjacent users should validate whether public-sector, institutional, or professional-service proximity changes meeting frequency and location value." },
        { label: "Visitor process", summary: "Visitor arrival, parking, transit access, and any security process should be tested against the organization's daily meeting pattern." },
      ],
      environmentExplanation: {
        whyItExists: "Civic-adjacent office environments exist for organizations that benefit from being near public institutions, downtown meeting patterns, professional services, and central administrative infrastructure.",
        whyChooseThisEnvironment: "Choose this environment when civic access and stakeholder convenience matter more than retail-adjacent polish or suburban parking. Compare LoDo, Cherry Creek, and DTC when district texture, customer arrival, or commute geography changes the decision.",
        representativeValue: "1600 Broadway adds a civic-access benchmark to Downtown Denver Building Profile evidence.",
      },
      relatedDistricts: [
        { districtId: "lodo", reason: "Historic mixed-use downtown-edge alternative." },
        { districtId: "denver-tech-center", reason: "Southeast suburban office and parking-oriented alternative." },
      ],
      nearbyAlternatives: [
        { label: "1200 17th St", url: buildingPath("1200 17th St"), reason: "Compare this when formal professional-service office identity matters more than civic adjacency." },
        { label: "1700 Lincoln St", url: buildingPath("1700 Lincoln St"), reason: "Compare this when executive image and client-facing presence are stronger drivers." },
        { label: "Denver Place", url: buildingPath("999 18th St"), reason: "Compare this when transit, walkability, and central access are the main downtown factors." },
      ],
      nearbyDistricts: [
        { label: "LoDo", url: districts.lodo.path, reason: "Compare when historic mixed-use texture matters more than civic-adjacent office context." },
        { label: "Denver Tech Center", url: districts.denverTechCenter.path, reason: "Compare when southeast metro access and parking convenience matter more than central civic access." },
      ],
      validationNotes: ["Confirm visitor arrival sequence.", "Validate parking plan.", "Review security and access requirements.", "Compare civic proximity against daily commute patterns."],
      sourceNotes: ["Existing Denver graph representative building for Downtown Denver."],
    },
  }),
  record({
    name: "1700 Lincoln St",
    address: "1700 Lincoln St",
    districtKey: "downtown",
    buildingType: "Executive downtown office",
    primarySpaceType: "office",
    editorialRole: "Client-Facing Executive Office Environment",
    editorialReason: "Adds a Downtown Denver Building Profile for client-facing and executive office decisions where address identity and professional presence are central to fit.",
    representativeThemes: ["Downtown office", "Executive presence", "Client-facing identity", "Professional services"],
    businessFit: ["law firms", "finance firms", "consulting firms", "executive offices", "regional headquarters"],
    relatedDistrictPaths: [districts.cherryCreek.path, districts.denverTechCenter.path, districts.lodo.path],
    nearbyBuildingPaths: [buildingPath("1200 17th St"), buildingPath("1600 Broadway"), buildingPath("999 18th St")],
    comparisonBuildingPaths: [buildingPath("1200 17th St"), buildingPath("100 Fillmore Place"), buildingPath("4600 S Syracuse St")],
    brief: {
      primaryEcosystem: "office",
      ecosystemSubtypes: ["downtown_office", "executive_office"],
      representativeRole: "executive_office_environment",
      businessActivities: ["client_meetings", "executive_work", "knowledge_work", "administrative_operations"],
      businessArchetypes: ["law_firm", "financial_services_firm", "consulting_firm", "regional_office"],
      operationalCharacteristics: ["professional_image", "client_arrival", "executive_presence", "transit_access", "structured_parking"],
      fitSummary: "Useful for firms comparing whether Downtown Denver address identity and client-facing presence justify a central office requirement.",
      summary: "1700 Lincoln St helps explain Downtown Denver as a client-facing and executive office environment for law, finance, consulting, advisory, and regional office users. It is useful for teams evaluating address identity, meeting experience, central access, and professional credibility against parking convenience or suburban commute patterns.",
      rofoTake: "This profile strengthens Downtown Denver's evidence for professional presence while keeping the recommendation practical: executive image only matters when it supports actual client, leadership, or stakeholder use.",
      snapshot: [
        { label: "Primary ecosystem", value: "Office" },
        { label: "Business use", value: "Client-facing executive office environment" },
        { label: "District", value: "Downtown Denver" },
        { label: "Access context", value: "Central Denver professional-service, civic, and regional business geography" },
        { label: "Comparison role", value: "Executive-presence counterpoint to civic-access and transit-oriented downtown office profiles" },
      ],
      bestFit: [
        "Law, finance, consulting, advisory, and executive teams that regularly host clients or senior stakeholders.",
        "Regional offices that want a central Denver business identity rather than a suburban campus setting.",
        "Professional-service firms comparing downtown credibility against Cherry Creek polish or Denver Tech Center convenience.",
      ],
      mayNotFit: [
        "Teams that do not benefit from client-facing image or a central address signal.",
        "Operations that prioritize parking simplicity, low-friction commute patterns, or industrial utility over professional presence.",
      ],
      buildingExperience: "A tour should focus on lobby and visitor experience, meeting-space fit, elevator and security flow, parking plan, floorplate usability, and whether the address supports the firm's client expectations.",
      locationContext: "Downtown Denver gives client-facing users a central professional-service setting. Compare Cherry Creek when a more boutique, retail-adjacent customer environment matters more and Denver Tech Center when southeast metro access and parking dominate.",
      advantages: [
        "Adds executive and client-facing evidence to Downtown Denver's office coverage.",
        "Clarifies why professional-service firms may choose downtown over suburban alternatives.",
        "Supports law, finance, consulting, and regional-office Business Brief reasoning.",
      ],
      tradeoffs: [
        "Professional image can be overvalued if clients rarely visit or the team works mostly remotely.",
        "Parking, commute, and visitor arrival may require more planning than in suburban office nodes.",
        "The district's formal tone may not fit creative teams seeking adaptive or neighborhood texture.",
      ],
      operationalProfile: [
        { label: "Client meetings", summary: "Client-facing teams should validate arrival, reception, meeting flow, privacy, and whether downtown proximity makes meetings easier." },
        { label: "Address value", summary: "The central address should be treated as useful only when it supports clients, recruiting, leadership presence, or regional stakeholder access." },
      ],
      environmentExplanation: {
        whyItExists: "Executive downtown office environments exist for organizations that need professional credibility, meeting-ready access, leadership presence, and a central business identity.",
        whyChooseThisEnvironment: "Choose this environment when client-facing presence and address identity matter more than suburban parking or creative district character. Compare Cherry Creek, DTC, and LoDo when those tradeoffs become stronger.",
        representativeValue: "1700 Lincoln St adds an executive-presence benchmark to Downtown Denver Building Profile evidence.",
      },
      relatedDistricts: [
        { districtId: "cherry-creek", reason: "Boutique client-facing and retail-adjacent alternative." },
        { districtId: "denver-tech-center", reason: "Southeast suburban office and parking-oriented alternative." },
      ],
      nearbyAlternatives: [
        { label: "1200 17th St", url: buildingPath("1200 17th St"), reason: "Compare this when formal class A office context matters more than executive-presence signaling." },
        { label: "1600 Broadway", url: buildingPath("1600 Broadway"), reason: "Compare this when civic or government-adjacent access is a stronger driver." },
        { label: "Denver Place", url: buildingPath("999 18th St"), reason: "Compare this when transit and walkable downtown access matter more than executive image." },
      ],
      nearbyDistricts: [
        { label: "Cherry Creek", url: districts.cherryCreek.path, reason: "Compare when a more boutique, retail-adjacent client-facing environment is preferable." },
        { label: "Denver Tech Center", url: districts.denverTechCenter.path, reason: "Compare when parking, southeast commute geography, or suburban office scale matters more." },
      ],
      validationNotes: ["Validate client arrival.", "Confirm meeting-space fit.", "Review parking and commute plan.", "Compare professional image against Cherry Creek and DTC alternatives."],
      sourceNotes: ["Existing Denver graph representative building for Downtown Denver."],
    },
  }),
  record({
    name: "Denver Place",
    address: "999 18th St",
    districtKey: "downtown",
    buildingType: "Transit-oriented downtown office",
    primarySpaceType: "office",
    editorialRole: "Walkable Downtown Office Environment",
    editorialReason: "Adds a Downtown Denver Building Profile for teams whose district fit depends on transit, walkability, stakeholder access, and central office identity.",
    representativeThemes: ["Downtown office", "Transit access", "Walkability", "Regional office identity"],
    businessFit: ["professional-service firms", "regional offices", "nonprofits", "central administrative teams"],
    relatedDistrictPaths: [districts.lodo.path, districts.rino.path, districts.denverTechCenter.path],
    nearbyBuildingPaths: [buildingPath("1200 17th St"), buildingPath("1600 Broadway"), buildingPath("1700 Lincoln St")],
    comparisonBuildingPaths: [buildingPath("1200 17th St"), buildingPath("1600 Broadway"), buildingPath("4600 S Syracuse St")],
    brief: {
      primaryEcosystem: "office",
      ecosystemSubtypes: ["downtown_office", "transit_oriented_office"],
      representativeRole: "transit_oriented_office_environment",
      businessActivities: ["knowledge_work", "stakeholder_meetings", "client_meetings", "administrative_operations"],
      businessArchetypes: ["professional_office", "regional_office", "nonprofit", "administrative_office"],
      operationalCharacteristics: ["transit_access", "walkability", "visitor_access", "professional_image", "downtown_amenities"],
      fitSummary: "Useful for office users comparing whether transit, walkability, stakeholder access, and downtown services should lead the Denver location decision.",
      summary: "Denver Place helps explain Downtown Denver as a walkable and transit-oriented office environment for professional-service, nonprofit, regional office, and administrative users. It is useful for teams weighing employee access, stakeholder convenience, downtown services, and central-market identity against parking-sensitive or suburban alternatives.",
      rofoTake: "This profile gives Downtown Denver an access-oriented office benchmark, making the district easier to evaluate for teams whose fit depends on how people reach and use the office.",
      snapshot: [
        { label: "Primary ecosystem", value: "Office" },
        { label: "Business use", value: "Transit-oriented downtown office environment" },
        { label: "District", value: "Downtown Denver" },
        { label: "Access context", value: "Central Denver transit, walkability, civic, hospitality, and professional-service geography" },
        { label: "Comparison role", value: "Access-oriented counterpoint to executive and civic-adjacent downtown office profiles" },
      ],
      bestFit: [
        "Professional-service, nonprofit, regional, and administrative teams that value transit and stakeholder access.",
        "Organizations comparing central employee access against Denver Tech Center or suburban parking convenience.",
        "Teams that want downtown walkability and services to support meetings, hiring, or hybrid attendance.",
      ],
      mayNotFit: [
        "Parking-sensitive customer operations whose visitors expect low-friction vehicle access.",
        "Industrial, flex, or warehouse users requiring loading, production, yard, or vehicle-oriented operations.",
      ],
      buildingExperience: "A tour should focus on transit approach, parking strategy, visitor arrival, nearby services, meeting flow, floorplate usability, and how the downtown environment supports daily employee and stakeholder movement.",
      locationContext: "Downtown Denver provides central office identity, transit, walkability, and professional-service context. Compare Denver Tech Center for parking and southeast access, RiNo for creative district character, and LoDo for historic downtown-edge texture.",
      advantages: [
        "Adds transit and walkability evidence to Downtown Denver's office Building Profile coverage.",
        "Helps nonprofit and stakeholder-facing teams evaluate central access without relying only on executive-image logic.",
        "Supports comparison between Downtown Denver, RiNo, LoDo, and Denver Tech Center office environments.",
      ],
      tradeoffs: [
        "Transit and walkability may not solve parking needs for visitors, clients, or employees arriving from suburban geographies.",
        "Central location value depends on actual employee and stakeholder travel patterns.",
        "The downtown setting may be less distinctive than RiNo or LoDo for teams prioritizing creative district identity.",
      ],
      operationalProfile: [
        { label: "Employee access", summary: "Teams should validate whether transit, walking routes, parking, and commute patterns match how employees will actually use the office." },
        { label: "Stakeholder movement", summary: "Nonprofits and regional offices should test whether downtown services and central access improve meetings, collaboration, and external visits." },
      ],
      environmentExplanation: {
        whyItExists: "Transit-oriented downtown office environments exist for organizations that value central access, walkability, meetings, downtown services, and a recognizable regional office setting.",
        whyChooseThisEnvironment: "Choose this environment when employee and stakeholder access matter more than suburban parking convenience or creative district texture. Compare DTC, RiNo, and LoDo when those conditions change.",
        representativeValue: "Denver Place adds a walkable-access benchmark to Downtown Denver Building Profile evidence.",
      },
      relatedDistricts: [
        { districtId: "lodo", reason: "Historic mixed-use downtown-edge alternative." },
        { districtId: "rino", reason: "Creative adaptive office and mixed commercial alternative." },
      ],
      nearbyAlternatives: [
        { label: "1200 17th St", url: buildingPath("1200 17th St"), reason: "Compare this when formal professional-service office identity matters more than access orientation." },
        { label: "1600 Broadway", url: buildingPath("1600 Broadway"), reason: "Compare this when civic or government-adjacent context is more important." },
        { label: "1700 Lincoln St", url: buildingPath("1700 Lincoln St"), reason: "Compare this when executive image and client-facing presence are stronger drivers." },
      ],
      nearbyDistricts: [
        { label: "LoDo", url: districts.lodo.path, reason: "Compare when historic mixed-use texture and downtown-edge hospitality context matter more." },
        { label: "RiNo", url: districts.rino.path, reason: "Compare when creative adaptive office character matters more than central office access." },
      ],
      validationNotes: ["Confirm transit access.", "Validate visitor parking.", "Review employee commute patterns.", "Compare walkability against DTC and suburban alternatives."],
      sourceNotes: ["Existing Denver graph representative building for Downtown Denver."],
    },
  }),
  record({
    name: "4643 S Ulster St",
    address: "4643 S Ulster St",
    districtKey: "denverTechCenter",
    buildingType: "DTC professional office",
    primarySpaceType: "office",
    editorialRole: "Professional Office Environment",
    editorialReason: "Adds a practical Denver Tech Center Building Profile for regional service, administrative, and client-facing office users.",
    representativeThemes: ["Denver Tech Center", "Professional office", "Southeast metro access", "Parking-oriented office"],
    businessFit: ["professional services", "regional service offices", "administrative teams", "client-facing offices"],
    relatedDistrictPaths: [districts.downtown.path, districts.cherryCreek.path],
    nearbyBuildingPaths: [buildingPath("4600 S Syracuse St"), buildingPath("7900 E Union Ave")],
    comparisonBuildingPaths: [buildingPath("4600 S Syracuse St"), buildingPath("7900 E Union Ave"), buildingPath("1200 17th St")],
    brief: {
      primaryEcosystem: "office",
      ecosystemSubtypes: ["suburban_office", "professional_office"],
      representativeRole: "professional_office_environment",
      businessActivities: ["knowledge_work", "administrative_operations", "client_meetings"],
      businessArchetypes: ["professional_office", "consulting_firm", "regional_service_office", "administrative_office"],
      operationalCharacteristics: ["parking_oriented", "freeway_access", "professional_image", "southeast_metro_access"],
      fitSummary: "Useful for teams comparing practical DTC professional office utility against downtown identity or Cherry Creek polish.",
      summary: "4643 S Ulster St helps explain Denver Tech Center as a practical professional office environment for regional service, administrative, consulting, and client-facing users. It is useful for teams weighing southeast metro access, parking, and office convenience against downtown Denver identity or Cherry Creek customer-facing polish.",
      rofoTake: "This profile gives Denver Tech Center a practical office benchmark. It should be evaluated as evidence of DTC's suburban professional-office pattern, not as a claim about current availability, tenancy, or a guaranteed fit.",
      snapshot: [
        { label: "Primary ecosystem", value: "Office" },
        { label: "Business use", value: "Professional office environment" },
        { label: "District", value: "Denver Tech Center" },
        { label: "Access context", value: "Southeast Denver, I-25, parking-oriented office geography" },
        { label: "Comparison role", value: "Practical DTC office benchmark" },
      ],
      bestFit: [
        "Professional-service, consulting, and administrative teams that value southeast metro access.",
        "Client-facing office users that need parking convenience more than a central downtown address.",
        "Regional service offices comparing DTC with Downtown Denver, Cherry Creek, Inverness, or Centennial.",
      ],
      mayNotFit: [
        "Teams that need a dense urban office identity, strong transit orientation, or downtown civic adjacency.",
        "Retail, medical, industrial, or warehouse users whose fit depends on property-specific infrastructure.",
      ],
      buildingExperience: "A tour should focus on office layout, parking and visitor arrival, employee commute geography, meeting flow, and whether the building supports the team's southeast metro operating pattern.",
      locationContext: "Denver Tech Center is strongest when southeast metro access, parking, and suburban office scale matter more than downtown identity. Compare Downtown Denver for central civic access and Cherry Creek for boutique client-facing polish.",
      advantages: [
        "Adds a practical professional-office benchmark to Denver Tech Center evidence.",
        "Helps explain why DTC can fit regional service and administrative users.",
        "Supports comparison against Downtown Denver, Cherry Creek, Inverness, and Centennial.",
      ],
      tradeoffs: [
        "DTC convenience may be less useful for users that depend on downtown transit, civic access, or urban walkability.",
        "Professional office evidence does not establish current suite availability, parking allocation, or buildout suitability.",
        "The district may feel too suburban for teams whose culture or customers are centered in Denver's urban core.",
      ],
      operationalProfile: [
        { label: "Southeast access", summary: "Validate whether employee, customer, and partner geography actually favors DTC over Downtown Denver, Cherry Creek, Inverness, or Centennial." },
        { label: "Parking and arrival", summary: "Confirm parking allocation, visitor access, signage, and arrival sequence before relying on DTC's parking-oriented reputation." },
      ],
      environmentExplanation: {
        whyItExists: "DTC professional office environments exist for businesses that need suburban office function, parking, southeast access, and regional convenience more than urban identity.",
        whyChooseThisEnvironment: "Choose this environment when practical office utility and southeast commute patterns matter more than central Denver image or retail-adjacent customer presence.",
        representativeValue: "4643 S Ulster St adds a practical professional-office evidence point to Denver Tech Center.",
      },
      relatedDistricts: [
        { districtId: "downtown-denver", reason: "Central civic, legal, finance, and transit-oriented office alternative." },
        { districtId: "cherry-creek", reason: "Boutique client-facing and retail-adjacent office alternative." },
      ],
      nearbyAlternatives: [
        { label: "DTC Tech", url: buildingPath("4600 S Syracuse St"), reason: "Compare when larger business-park office identity or technology-support context matters more." },
        { label: "DTC Corporate Center III", url: buildingPath("7900 E Union Ave"), reason: "Compare when campus-style corporate office scale is the stronger question." },
        { label: "1200 17th St", url: buildingPath("1200 17th St"), reason: "Compare when central Denver identity and civic access may outweigh DTC convenience." },
      ],
      nearbyDistricts: [
        { label: "Downtown Denver", url: districts.downtown.path, reason: "Compare when central civic, legal, finance, transit, or downtown client access matters more than southeast parking convenience." },
        { label: "Cherry Creek", url: districts.cherryCreek.path, reason: "Compare when boutique client-facing image and retail-adjacent customer experience matter more than DTC office practicality." },
        { label: "Inverness", url: "/commercial-real-estate/CO/englewood/inverness/", reason: "Compare when a quieter southeast business-park setting may fit better than Denver Tech Center." },
      ],
      validationNotes: ["Confirm office layout and meeting-space fit.", "Validate parking allocation and visitor arrival.", "Review employee commute geography.", "Compare DTC utility against Downtown Denver and Cherry Creek identity."],
      sourceNotes: ["Existing Denver graph representative building for Denver Tech Center."],
    },
  }),
  record({
    name: "DTC Corporate Center III",
    address: "7900 E Union Ave",
    districtKey: "denverTechCenter",
    buildingType: "DTC corporate office",
    primarySpaceType: "office",
    editorialRole: "Suburban Corporate Office Environment",
    editorialReason: "Adds a Denver Tech Center Building Profile for the larger corporate and campus-style office side of the district.",
    representativeThemes: ["Denver Tech Center", "Corporate office", "Campus-style office", "Southeast metro access"],
    businessFit: ["regional headquarters", "corporate offices", "professional services", "administrative teams"],
    relatedDistrictPaths: [districts.downtown.path],
    nearbyBuildingPaths: [buildingPath("4643 S Ulster St"), buildingPath("4600 S Syracuse St")],
    comparisonBuildingPaths: [buildingPath("4643 S Ulster St"), buildingPath("4600 S Syracuse St"), buildingPath("1700 Lincoln St")],
    brief: {
      primaryEcosystem: "office",
      ecosystemSubtypes: ["suburban_office", "corporate_office", "campus_style_office"],
      representativeRole: "suburban_office_campus",
      businessActivities: ["knowledge_work", "administrative_operations", "client_meetings", "collaboration"],
      businessArchetypes: ["regional_headquarters", "corporate_office", "professional_office", "back_office_team"],
      operationalCharacteristics: ["parking_oriented", "large_floorplates", "freeway_access", "suburban_access", "professional_image"],
      fitSummary: "Useful for companies comparing DTC's larger corporate office pattern against downtown identity, Cherry Creek image, or Inverness business-park alternatives.",
      summary: "DTC Corporate Center III helps explain Denver Tech Center as a corporate and campus-style office environment for regional headquarters, professional-service teams, administrative groups, and larger office users. It is useful for comparing suburban office scale, parking, southeast metro access, and floorplate needs against more urban Denver choices.",
      rofoTake: "This profile gives DTC a larger-format corporate-office benchmark. The useful question is not whether every business should be in DTC, but whether southeast access, parking, and office scale solve the user's operating pattern better than central Denver alternatives.",
      snapshot: [
        { label: "Primary ecosystem", value: "Office" },
        { label: "Business use", value: "Corporate / campus-style office environment" },
        { label: "District", value: "Denver Tech Center" },
        { label: "Access context", value: "Southeast metro office and I-25 corridor" },
        { label: "Comparison role", value: "Larger DTC office-scale benchmark" },
      ],
      bestFit: [
        "Regional headquarters and corporate office users that value DTC identity and southeast access.",
        "Professional-service and administrative teams comparing larger floorplate or expansion needs.",
        "Parking-sensitive office users comparing DTC with Downtown Denver, Cherry Creek, Inverness, or Centennial.",
      ],
      mayNotFit: [
        "Small teams that value urban walkability, transit, or boutique district identity more than office scale.",
        "Users that need confirmed technical infrastructure, specialized medical buildout, or industrial functionality.",
      ],
      buildingExperience: "A tour should test floorplate fit, expansion needs, parking, visitor arrival, employee commute patterns, and whether the campus-style setting supports the business's daily operating model.",
      locationContext: "Denver Tech Center is Denver's clearest southeast corporate office alternative to central business districts. Compare Downtown Denver for civic identity, Cherry Creek for boutique client-facing presence, and Inverness for quieter business-park context.",
      advantages: [
        "Adds larger corporate office evidence to Denver Tech Center coverage.",
        "Explains DTC's role for headquarters, administrative, and parking-sensitive users.",
        "Supports comparison between DTC, Downtown Denver, Cherry Creek, and Inverness.",
      ],
      tradeoffs: [
        "Corporate office scale can be less valuable for smaller teams or users whose clients expect a central Denver address.",
        "Suburban convenience may come with less walkable district texture than Downtown Denver, LoDo, RiNo, or Cherry Creek.",
        "Representative evidence does not establish current availability, expansion options, or exact building systems.",
      ],
      operationalProfile: [
        { label: "Corporate scale", summary: "Validate whether the requirement benefits from larger office format, expansion room, and DTC corporate identity." },
        { label: "Commute geography", summary: "Test southeast employee, client, and partner geography before assuming DTC outperforms central or north/west Denver alternatives." },
      ],
      environmentExplanation: {
        whyItExists: "Suburban corporate office environments exist for teams that prioritize parking, regional access, floorplate utility, and a recognized business-park identity.",
        whyChooseThisEnvironment: "Choose this environment when DTC scale and southeast access matter more than downtown transit, civic identity, or boutique customer-facing image.",
        representativeValue: "DTC Corporate Center III adds a larger corporate-office benchmark to Denver Tech Center.",
      },
      relatedDistricts: [
        { districtId: "downtown-denver", reason: "More central civic, legal, finance, and transit-oriented office alternative." },
        { districtId: "inverness", reason: "Quieter southeast business-park alternative with DTC adjacency." },
      ],
      nearbyAlternatives: [
        { label: "4643 S Ulster St", url: buildingPath("4643 S Ulster St"), reason: "Compare when practical professional-office utility matters more than corporate scale." },
        { label: "DTC Tech", url: buildingPath("4600 S Syracuse St"), reason: "Compare when technology-support or business-park office context is the stronger question." },
        { label: "1700 Lincoln St", url: buildingPath("1700 Lincoln St"), reason: "Compare when downtown client-facing presence may outweigh DTC convenience." },
      ],
      nearbyDistricts: [
        { label: "Downtown Denver", url: districts.downtown.path, reason: "Compare when central civic, legal, finance, transit, or downtown client access matters more than southeast corporate office scale." },
        { label: "Cherry Creek", url: districts.cherryCreek.path, reason: "Compare when boutique client-facing image and retail-adjacent customer experience matter more than campus-style office scale." },
        { label: "Inverness", url: "/commercial-real-estate/CO/englewood/inverness/", reason: "Compare when southeast business-park context is useful but Denver Tech Center visibility is less important." },
      ],
      validationNotes: ["Confirm floorplate and expansion fit.", "Validate parking allocation and visitor arrival.", "Review employee commute geography.", "Compare DTC corporate scale against downtown and Inverness alternatives."],
      sourceNotes: ["Existing Denver graph representative building for Denver Tech Center."],
    },
  }),
  record({
    name: "DTC Tech",
    address: "4600 S Syracuse St",
    districtKey: "denverTechCenter",
    buildingType: "DTC technology / business-park office",
    primarySpaceType: "office",
    editorialRole: "Technology-Support Office Environment",
    editorialReason: "Adds a Denver Tech Center Building Profile for technology, office-heavy flex, and southeast business-park comparisons.",
    representativeThemes: ["Denver Tech Center", "Technology-support office", "Business-park office", "Southeast access"],
    businessFit: ["technology companies", "office-heavy flex users", "professional services", "administrative teams"],
    relatedDistrictPaths: [districts.downtown.path, districts.rino.path],
    nearbyBuildingPaths: [buildingPath("4643 S Ulster St"), buildingPath("7900 E Union Ave")],
    comparisonBuildingPaths: [buildingPath("4643 S Ulster St"), buildingPath("7900 E Union Ave"), buildingPath("1200 17th St")],
    brief: {
      primaryEcosystem: "office",
      ecosystemSubtypes: ["suburban_office", "technology_office", "business_park_office"],
      representativeRole: "suburban_office_campus",
      businessActivities: ["knowledge_work", "collaboration", "administrative_operations", "technical_support"],
      businessArchetypes: ["technology_company", "professional_office", "administrative_office", "office_heavy_flex_user"],
      operationalCharacteristics: ["parking_oriented", "freeway_access", "suburban_access", "larger_floorplates", "professional_image"],
      fitSummary: "Useful for technology, office-heavy flex, and professional users comparing DTC's business-park office setting with downtown or creative Denver alternatives.",
      summary: "DTC Tech helps explain Denver Tech Center as a southeast business-park office environment for technology, office-heavy flex, administrative, and professional-service users. It is useful for teams comparing parking, I-25 access, larger office formats, and suburban convenience against RiNo creative identity or Downtown Denver central access.",
      rofoTake: "This profile strengthens DTC's technology and business-park office evidence while keeping the boundary clear: DTC may support office-heavy technical users, but it is not a substitute for true warehouse, lab, or industrial validation.",
      snapshot: [
        { label: "Primary ecosystem", value: "Office" },
        { label: "Business use", value: "Technology / business-park office environment" },
        { label: "District", value: "Denver Tech Center" },
        { label: "Access context", value: "Southeast metro business-park office geography" },
        { label: "Comparison role", value: "DTC technology and office-heavy flex benchmark" },
      ],
      bestFit: [
        "Technology, technical support, and office-heavy flex teams that value parking and southeast access.",
        "Professional or administrative users comparing DTC business-park office utility against downtown or creative districts.",
        "Companies that need a practical office setting more than RiNo creative texture or Downtown Denver civic identity.",
      ],
      mayNotFit: [
        "Teams that need warehouse, loading, lab, or production infrastructure without direct property validation.",
        "Creative or client-facing users that value RiNo, LoDo, Cherry Creek, or Downtown Denver identity more than DTC convenience.",
      ],
      buildingExperience: "A tour should test office-heavy technical fit, parking, employee commute patterns, meeting and collaboration needs, and whether the business-park setting supports the team's culture and operations.",
      locationContext: "Denver Tech Center gives technology and professional users a southeast office alternative to Downtown Denver and RiNo. Compare RiNo when creative district identity matters more and Downtown Denver when central civic or transit access is stronger.",
      advantages: [
        "Adds technology-support and business-park office evidence to Denver Tech Center.",
        "Helps distinguish DTC office-heavy flex fit from true industrial or warehouse requirements.",
        "Supports comparison between DTC, Downtown Denver, RiNo, Inverness, and Centennial.",
      ],
      tradeoffs: [
        "Business-park office convenience may feel less distinctive than RiNo or downtown Denver for recruiting and culture.",
        "Office-heavy technical fit does not imply lab, warehouse, production, loading, or specialized infrastructure.",
        "DTC may be weaker when employee or client geography is centered north, west, or downtown.",
      ],
      operationalProfile: [
        { label: "Office-heavy technical fit", summary: "Validate whether the requirement is primarily office, office/flex, or a specialized technical use requiring infrastructure beyond ordinary office space." },
        { label: "District comparison", summary: "Compare DTC against RiNo, Downtown Denver, Inverness, Centennial, and US-36 alternatives when talent, clients, or technical needs point elsewhere." },
      ],
      environmentExplanation: {
        whyItExists: "Business-park technology office environments exist for teams that need practical office function, parking, and regional access without a dense urban district requirement.",
        whyChooseThisEnvironment: "Choose this environment when southeast access and office-heavy technical practicality matter more than creative district identity or central transit access.",
        representativeValue: "DTC Tech gives Denver Tech Center a technology-support and business-park office benchmark.",
      },
      relatedDistricts: [
        { districtId: "rino", reason: "Creative and adaptive office alternative for teams prioritizing urban technology culture." },
        { districtId: "downtown-denver", reason: "Central business district alternative for teams prioritizing civic, transit, or client access." },
      ],
      nearbyAlternatives: [
        { label: "4643 S Ulster St", url: buildingPath("4643 S Ulster St"), reason: "Compare when practical professional-office utility matters more than technology-support positioning." },
        { label: "DTC Corporate Center III", url: buildingPath("7900 E Union Ave"), reason: "Compare when larger corporate office scale is the stronger requirement." },
        { label: "1200 17th St", url: buildingPath("1200 17th St"), reason: "Compare when downtown professional identity may matter more than DTC convenience." },
      ],
      nearbyDistricts: [
        { label: "RiNo", url: districts.rino.path, reason: "Compare when creative office identity and urban technology culture matter more than southeast parking-oriented practicality." },
        { label: "Downtown Denver", url: districts.downtown.path, reason: "Compare when central civic, transit, partner, or client access matters more than DTC office-heavy technical utility." },
        { label: "Inverness", url: "/commercial-real-estate/CO/englewood/inverness/", reason: "Compare when a quieter southeast business-park alternative may fit better than Denver Tech Center." },
      ],
      validationNotes: ["Confirm whether the requirement is ordinary office, office-heavy flex, or specialized technical space.", "Validate parking and employee commute patterns.", "Review collaboration, meeting, and expansion needs.", "Compare DTC against RiNo, Downtown Denver, and US-36 technology alternatives."],
      sourceNotes: ["Existing Denver graph representative building for Denver Tech Center."],
    },
  }),
  record({
    name: "100 Fillmore Place",
    address: "100 Fillmore Place",
    districtKey: "cherryCreek",
    buildingType: "Client-facing office / retail-adjacent commercial",
    primarySpaceType: "retail",
    editorialRole: "Neighborhood Service Retail Environment",
    editorialReason: "Adds a customer-facing Cherry Creek profile so Denver's retail and service-retail ecosystem is not represented only as secondary district context.",
    representativeThemes: ["Service retail", "Retail adjacency", "Customer access", "Boutique professional services"],
    businessFit: ["service retail", "wellness providers", "customer-facing professional services", "boutique brands"],
    relatedDistrictPaths: [districts.downtown.path, districts.centralPark.path],
    nearbyBuildingPaths: [buildingPath("250 Fillmore St"), buildingPath("205 Detroit St")],
    comparisonBuildingPaths: [buildingPath("1200 17th St"), buildingPath("8354 Northfield Blvd"), buildingPath("205 Detroit St")],
    brief: {
      primaryEcosystem: "retail",
      ecosystemSubtypes: ["neighborhood_retail", "service_retail"],
      representativeRole: "neighborhood_service_retail",
      businessActivities: ["walk_in_service", "client_meetings", "customer_showroom"],
      businessArchetypes: ["wellness_practice", "marketing_agency", "professional_office"],
      operationalCharacteristics: ["street_visibility", "customer_parking", "walk_in_customer_access", "retail_adjacent", "professional_image"],
      fitSummary: "Useful for customer-facing service businesses comparing Cherry Creek's retail adjacency, visitor experience, and polished district identity.",
      summary: "100 Fillmore Place helps explain Cherry Creek as a customer-facing commercial environment where boutique office, service retail, wellness, and retail adjacency overlap. It is useful for businesses comparing whether visitor experience, district image, and customer access matter more than conventional office efficiency or lower-cost operating space.",
      rofoTake: "This profile closes the initial retail Building Profile gap in Denver while keeping retail as an important supporting ecosystem rather than a new primary Rofo focus.",
      snapshot: [
        { label: "Primary ecosystem", value: "Retail" },
        { label: "Business use", value: "Neighborhood service retail environment" },
        { label: "District", value: "Cherry Creek" },
        { label: "Access context", value: "Customer-facing Cherry Creek commercial geography" },
        { label: "Comparison role", value: "Retail and service-retail counterweight to industrial/flex depth" },
      ],
      bestFit: [
        "Wellness, service, boutique professional, and customer-facing businesses that benefit from Cherry Creek's district identity.",
        "Teams comparing whether retail adjacency and visitor experience matter more than conventional office efficiency.",
        "Businesses that need a polished arrival sequence and customer geography without becoming a pure downtown office search.",
      ],
      mayNotFit: [
        "Back-office teams that do not benefit from customer access or retail adjacency.",
        "Industrial or warehouse users needing loading, yard, or operational utility.",
      ],
      buildingExperience: "A tour should focus on customer arrival, visibility, parking, signage, nearby retail context, and whether the district's image supports the business model.",
      locationContext: "Cherry Creek differs from Downtown Denver by emphasizing polished customer-facing identity, retail adjacency, and local visitor experience. Compare Central Park when parking and northeast Denver customer geography matter more.",
      advantages: [
        "Adds initial retail/customer-facing Building Profile depth to Denver.",
        "Helps distinguish service retail and retail-adjacent professional use from generic office coverage.",
        "Supports comparison between Cherry Creek, Downtown Denver, and Central Park customer geographies.",
      ],
      tradeoffs: [
        "Retail adjacency may increase cost or complexity without helping businesses that do not need customer presence.",
        "Parking, signage, frontage, and customer arrival vary by exact suite and should be validated.",
        "Customer-facing identity may be less useful for private administrative teams or operational businesses.",
      ],
      operationalProfile: [
        { label: "Customer presence", summary: "Customer-facing users should validate visibility, arrival, signage, and how surrounding retail activity supports the intended use." },
        { label: "District fit", summary: "Cherry Creek can help businesses that benefit from polished customer geography, but it may be less efficient for private office or operational uses." },
      ],
      environmentExplanation: {
        whyItExists: "Neighborhood service retail environments exist for businesses that need customers to find, enter, and trust the location, while still operating in a broader commercial district.",
        whyChooseThisEnvironment: "Choose this environment over Downtown Denver when customer experience and retail adjacency matter more than central office identity. Compare Central Park when parking and northeast customer geography are stronger drivers.",
        representativeValue: "100 Fillmore Place gives Denver an initial retail/service-retail Building Profile benchmark.",
      },
      relatedDistricts: [{ districtId: "central-park", reason: "Parking-friendly medical, service, and local customer geography alternative." }],
      nearbyAlternatives: [
        { label: "1200 17th St", url: buildingPath("1200 17th St"), reason: "Compare this when central office identity matters more than retail adjacency." },
        { label: "3401 Quebec St", url: buildingPath("3401 Quebec Street, Suite 9000"), reason: "Compare this when patient access and northeast Denver customer geography are stronger drivers." },
        { label: "205 Detroit St", url: buildingPath("205 Detroit St"), reason: "Compare this as another Cherry Creek building before treating one customer-facing example as the full district." },
      ],
      validationNotes: ["Confirm frontage and signage rights.", "Validate customer parking and arrival sequence.", "Confirm permitted use.", "Compare retail adjacency against operating cost and privacy needs."],
      sourceNotes: ["Existing Denver graph representative building for Cherry Creek."],
    },
  }),
  record({
    name: "3401 Quebec St",
    address: "3401 Quebec Street, Suite 9000",
    districtKey: "centralPark",
    buildingType: "Medical / professional office",
    primarySpaceType: "medical",
    editorialRole: "Medical Office Environment",
    editorialReason: "Adds a medical Building Profile benchmark for Central Park so Denver's medical ecosystem has initial brief depth outside industrial/flex.",
    representativeThemes: ["Medical office", "Patient access", "Northeast Denver", "Service-commercial context"],
    businessFit: ["medical practice", "wellness practice", "specialty clinic", "administrative office"],
    relatedDistrictPaths: [districts.cherryCreek.path, districts.downtown.path],
    nearbyBuildingPaths: [buildingPath("8354 Northfield Blvd")],
    comparisonBuildingPaths: [buildingPath("100 Fillmore Place"), buildingPath("1200 17th St"), buildingPath("8354 Northfield Blvd")],
    brief: {
      primaryEcosystem: "medical",
      ecosystemSubtypes: ["medical_office"],
      representativeRole: "medical_office_environment",
      businessActivities: ["healthcare_delivery", "administrative_operations", "walk_in_service"],
      businessArchetypes: ["medical_practice", "dental_practice", "physical_therapy_practice", "wellness_practice", "outpatient_clinic"],
      operationalCharacteristics: ["customer_parking", "professional_image", "medical_use_compatible", "walk_in_customer_access", "suburban_access"],
      fitSummary: "Useful for medical and wellness users comparing northeast Denver patient access, parking, and service-commercial context.",
      summary: "3401 Quebec St helps explain Central Park as a medical and professional-service environment for businesses serving northeast Denver customer and patient geography. It is useful for practices and service users comparing parking, accessibility, neighborhood access, and patient convenience against central Denver image or hospital-adjacent locations.",
      rofoTake: "This profile gives Denver medical Building Profile depth so industrial/flex Building Briefs no longer carry all ecosystem evidence.",
      snapshot: [
        { label: "Primary ecosystem", value: "Medical" },
        { label: "Business use", value: "Medical office environment" },
        { label: "District", value: "Central Park" },
        { label: "Access context", value: "Northeast Denver patient and customer geography" },
        { label: "Comparison role", value: "Medical counterweight to Denver industrial/flex Building Profile depth" },
      ],
      bestFit: [
        "Medical, dental, wellness, physical therapy, and outpatient users serving northeast Denver customers or patients.",
        "Professional or administrative users that need parking-friendly access without a downtown office identity.",
        "Patient-facing practices comparing Central Park's local access against Cherry Creek, Aurora, or south metro medical nodes.",
      ],
      mayNotFit: [
        "Practices requiring hospital adjacency or specialized clinical infrastructure without direct property validation.",
        "Executive office users whose clients expect Downtown Denver, Cherry Creek, or DTC identity.",
      ],
      buildingExperience: "A tour should focus on patient arrival, parking, accessibility, layout, plumbing or clinical requirements, signage, and whether the district matches the practice's referral geography.",
      locationContext: "Central Park gives Denver a different medical and service-commercial model from Downtown Denver or Cherry Creek: more parking-friendly, more neighborhood/customer-oriented, and less dependent on central office image.",
      advantages: [
        "Adds initial medical Building Profile depth to Denver.",
        "Explains patient and customer access in a northeast Denver mixed commercial setting.",
        "Supports comparison between Central Park, Cherry Creek, Downtown Denver, and other medical/service nodes.",
      ],
      tradeoffs: [
        "Medical fit depends on suite-level infrastructure, accessibility, permitted use, and patient flow.",
        "Central Park may not provide the same referral ecosystem as hospital-adjacent or specialty medical clusters.",
        "A neighborhood medical setting may be less useful for firms whose client or employee geography is centered downtown or along I-25.",
      ],
      operationalProfile: [
        { label: "Patient access", summary: "Medical users should validate parking, accessibility, arrival sequence, signage, and how easily patients can reach the location." },
        { label: "Clinical requirements", summary: "Plumbing, HVAC, layout, permitted use, and any specialized medical improvements must be confirmed before relying on the property as a fit." },
      ],
      environmentExplanation: {
        whyItExists: "Medical office environments exist because healthcare and wellness users need patient access, privacy, professional image, parking, and clinical buildout feasibility to work together.",
        whyChooseThisEnvironment: "Choose this environment over Downtown Denver when patient parking and northeast Denver service geography matter more than central office identity. Compare Cherry Creek when polished customer-facing image is a stronger driver.",
        representativeValue: "3401 Quebec St gives Denver's medical ecosystem an initial Building Profile benchmark.",
      },
      relatedDistricts: [{ districtId: "cherry-creek", reason: "More polished patient/customer-facing central Denver alternative." }],
      nearbyAlternatives: [
        { label: "8354 Northfield Blvd", url: buildingPath("8354 Northfield Blvd"), reason: "Compare this as another Central Park customer-facing reference before assuming one building defines the area." },
        { label: "100 Fillmore Place", url: buildingPath("100 Fillmore Place"), reason: "Compare this when Cherry Creek customer-facing identity matters more than northeast patient geography." },
        { label: "1200 17th St", url: buildingPath("1200 17th St"), reason: "Compare this when central office access is more important than parking-friendly medical or service access." },
      ],
      validationNotes: ["Confirm permitted medical use.", "Validate accessibility and patient parking.", "Confirm plumbing, HVAC, and layout requirements.", "Review signage and patient arrival sequence."],
      sourceNotes: ["Existing Denver graph representative building for Central Park."],
    },
  }),
];

module.exports = {
  canonicalBuildings: records,
};
