module.exports = {
  schemaVersion: "denver-office-editorial-recommendation-model-v1",
  modelKey: "denver:office",
  marketId: "denver",
  marketName: "Denver",
  regionId: "mountain-west",
  regionName: "Mountain West",
  spaceType: "office",
  sourceDocuments: [
    "docs/product/rofo-knowledge-architecture.md",
    "docs/product/business-brief-publishing-system.md",
    "docs/product/denver-office-editorial-recommendation-model.md",
    "_data/locationKnowledgeGraph.js",
    "_data/businessBriefDefinitions.js",
  ],
  unsupportedRankingSignals: [
    "exactBudget",
    "budget",
    "cost",
    "costSensitivity",
    "currentRents",
    "askingRates",
    "concessions",
    "currentAvailability",
    "landlordMotivation",
    "leaseEconomics",
    "costPosition",
  ],
  initialConsiderationSet: [
    "downtown-denver",
    "lodo",
    "rino",
    "cherry-creek",
    "denver-tech-center",
  ],
  districtOrder: [
    "downtown-denver",
    "lodo",
    "rino",
    "cherry-creek",
    "denver-tech-center",
    "central-park",
    "santa-fe-arts-district",
  ],
  districts: {
    "downtown-denver": {
      districtName: "Downtown Denver",
      launchRole: "default_initial",
      strategyRole: "Central civic, legal, finance, consulting, nonprofit, and regional office core.",
      stableAttributes: {
        transitOrientation: "high",
        parkingPattern: "medium",
        walkability: "high",
        clientAccessibility: "high",
        districtImage: "traditional_professional",
        growthFlexibility: "medium",
        amenityEnvironment: "high",
        talentAccess: "high",
        freewayAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "medium",
        lowerRiseCharacter: "low",
        southeastMetroAccess: "medium",
      },
      ecosystems: ["professional_services", "financial_services", "legal", "civic", "nonprofit", "client_facing"],
      buildingCharacter: ["traditional_professional", "high_rise", "corporate", "downtown_core"],
      nearbyAlternatives: ["lodo", "rino", "cherry-creek", "denver-tech-center"],
    },
    lodo: {
      districtName: "LoDo",
      launchRole: "default_initial",
      strategyRole: "Historic downtown-edge office district with Union Station, hospitality, and client access.",
      stableAttributes: {
        transitOrientation: "high",
        parkingPattern: "medium",
        walkability: "high",
        clientAccessibility: "high",
        districtImage: "historic_downtown_edge",
        growthFlexibility: "medium",
        amenityEnvironment: "high",
        talentAccess: "high",
        freewayAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "high",
        lowerRiseCharacter: "medium",
        southeastMetroAccess: "low",
      },
      ecosystems: ["professional_services", "technology", "creative", "hospitality_adjacent", "client_facing"],
      buildingCharacter: ["historic_distinctive", "creative_informal", "downtown_edge"],
      nearbyAlternatives: ["downtown-denver", "rino", "cherry-creek"],
    },
    rino: {
      districtName: "RiNo",
      launchRole: "default_initial",
      strategyRole: "Creative mixed-use office district for startups, design, showroom, and adaptive commercial users.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "medium",
        walkability: "high",
        clientAccessibility: "medium",
        districtImage: "creative_mixed_use",
        growthFlexibility: "medium",
        amenityEnvironment: "high",
        talentAccess: "high",
        freewayAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "high",
        lowerRiseCharacter: "medium",
        southeastMetroAccess: "low",
      },
      ecosystems: ["technology", "creative", "startup", "design", "showroom", "nonprofit"],
      buildingCharacter: ["creative_informal", "adaptive", "mixed_commercial"],
      nearbyAlternatives: ["lodo", "downtown-denver", "central-park", "santa-fe-arts-district"],
    },
    "cherry-creek": {
      districtName: "Cherry Creek",
      launchRole: "default_initial",
      strategyRole: "Polished boutique, client-facing, retail-adjacent professional office district.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "medium",
        walkability: "high",
        clientAccessibility: "high",
        districtImage: "polished_boutique",
        growthFlexibility: "medium",
        amenityEnvironment: "high",
        talentAccess: "high",
        freewayAccess: "medium",
        modernEnvironment: "medium",
        creativeCharacter: "medium",
        lowerRiseCharacter: "medium",
        southeastMetroAccess: "medium",
      },
      ecosystems: ["professional_services", "financial_services", "legal", "healthcare", "client_facing", "retail_adjacent"],
      buildingCharacter: ["traditional_professional", "modern_polished", "boutique"],
      nearbyAlternatives: ["downtown-denver", "lodo", "denver-tech-center"],
    },
    "denver-tech-center": {
      districtName: "Denver Tech Center",
      launchRole: "default_initial",
      strategyRole: "Southeast corporate office and business-park district for parking, highway access, and suburban scale.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "high",
        walkability: "medium",
        clientAccessibility: "high",
        districtImage: "corporate_suburban",
        growthFlexibility: "high",
        amenityEnvironment: "high",
        talentAccess: "high",
        freewayAccess: "high",
        modernEnvironment: "high",
        creativeCharacter: "low",
        lowerRiseCharacter: "medium",
        southeastMetroAccess: "high",
      },
      ecosystems: ["technology", "professional_services", "corporate", "regional_headquarters", "healthcare"],
      buildingCharacter: ["modern_polished", "traditional_professional", "suburban_campus"],
      nearbyAlternatives: ["downtown-denver", "cherry-creek"],
    },
    "central-park": {
      districtName: "Central Park",
      launchRole: "signal_specific",
      strategyRole: "Northeast Denver office, medical, service, and administrative district with parking-oriented access.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "high",
        walkability: "medium",
        clientAccessibility: "high",
        districtImage: "practical_mixed_commercial",
        growthFlexibility: "medium",
        amenityEnvironment: "high",
        talentAccess: "medium",
        freewayAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "low",
        lowerRiseCharacter: "medium",
        southeastMetroAccess: "low",
      },
      ecosystems: ["healthcare", "medical_office", "local_services", "administrative"],
      buildingCharacter: ["medical_office", "service_commercial", "parking_oriented"],
      nearbyAlternatives: ["rino", "cherry-creek"],
      entrySignals: ["healthcare", "medical_office", "northeast_denver", "parking"],
    },
    "santa-fe-arts-district": {
      districtName: "Santa Fe Arts District",
      launchRole: "signal_specific",
      strategyRole: "Creative, arts, showroom, and customer-facing commercial district with limited office-default role.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "medium",
        walkability: "medium",
        clientAccessibility: "medium",
        districtImage: "arts_creative",
        growthFlexibility: "low",
        amenityEnvironment: "medium",
        talentAccess: "medium",
        freewayAccess: "high",
        modernEnvironment: "low",
        creativeCharacter: "high",
        lowerRiseCharacter: "high",
        southeastMetroAccess: "low",
      },
      ecosystems: ["creative", "arts", "showroom", "customer_facing"],
      buildingCharacter: ["creative_informal", "lower_rise_neighborhood", "adaptive"],
      nearbyAlternatives: ["rino", "cherry-creek"],
      entrySignals: ["creative_informal", "lower_rise_neighborhood", "design_creative", "showroom_presentation"],
    },
  },
  businessFacts: {
    city: { required: true, behavior: "defines_market" },
    spaceType: { required: true, behavior: "defines_space_type_model" },
    headcount: { required: false, behavior: "influences_scale_and_inventory_depth" },
    expectedGrowth: { required: false, behavior: "influences_growth_flexibility" },
    clientVisitFrequency: { required: false, behavior: "influences_client_access_and_image" },
    recruitingImportance: { required: false, behavior: "influences_talent_access_and_environment" },
    businessType: { required: false, behavior: "influences_ecosystem_fit" },
    operationalUse: { required: false, behavior: "influences_office_job_to_be_done" },
    approximateSquareFootage: { required: false, behavior: "compatibility_only" },
  },
  officeEnvironmentTaxonomy: {
    modern_polished: {
      label: "Modern and polished",
      attributes: ["modernEnvironment", "growthFlexibility", "districtImage"],
      rise: ["denver-tech-center", "downtown-denver", "cherry-creek"],
      fall: ["santa-fe-arts-district"],
    },
    historic_distinctive: {
      label: "Historic and distinctive",
      attributes: ["creativeCharacter", "lowerRiseCharacter", "districtImage"],
      rise: ["lodo", "rino"],
      fall: ["denver-tech-center", "central-park"],
    },
    creative_informal: {
      label: "Creative and informal",
      attributes: ["creativeCharacter", "ecosystems", "buildingCharacter"],
      rise: ["rino", "lodo", "santa-fe-arts-district"],
      fall: ["denver-tech-center", "downtown-denver"],
      enter: ["santa-fe-arts-district"],
    },
    traditional_professional: {
      label: "Traditional and professional",
      attributes: ["clientAccessibility", "districtImage", "corporateEnvironment"],
      rise: ["downtown-denver", "cherry-creek", "denver-tech-center"],
      fall: ["rino", "santa-fe-arts-district"],
    },
    lower_rise_neighborhood: {
      label: "Lower-rise and neighborhood-oriented",
      attributes: ["lowerRiseCharacter", "parkingPattern", "districtImage"],
      rise: ["cherry-creek", "central-park", "santa-fe-arts-district", "rino"],
      fall: ["downtown-denver"],
      enter: ["central-park", "santa-fe-arts-district"],
    },
    not_sure: {
      label: "Not sure yet",
      attributes: [],
      rise: [],
      fall: [],
      enter: [],
    },
  },
  constraints: {
    districtAnchor: {
      effect: "strong_weight_anchor",
      explanation: "User-selected anchors strongly weight the named district and can introduce known nearby alternatives when comparison is allowed.",
    },
    nearbyAlternatives: {
      effect: "introduce_known_nearby",
      explanation: "Nearby alternatives enter only from explicit model relationships.",
    },
    commuteOrientation: {
      effect: "strong_weight_access_pattern",
      values: {
        central_city: {
          rise: ["downtown-denver", "lodo", "rino", "cherry-creek"],
          fall: ["denver-tech-center", "central-park"],
          attributes: ["transitOrientation", "walkability", "clientAccessibility"],
        },
        southeast_metro: {
          rise: ["denver-tech-center", "cherry-creek"],
          fall: ["rino", "lodo"],
          attributes: ["southeastMetroAccess", "freewayAccess", "parkingPattern"],
        },
        east_bay: {
          rise: [],
          fall: [],
          attributes: [],
          unsupported: true,
        },
        east_denver: {
          rise: ["central-park", "rino"],
          fall: ["denver-tech-center"],
          enter: ["central-park"],
          attributes: ["freewayAccess", "parkingPattern"],
        },
        transit_oriented: {
          rise: ["downtown-denver", "lodo"],
          fall: ["denver-tech-center", "central-park"],
          attributes: ["transitOrientation", "walkability"],
        },
      },
    },
    institutionProximity: {
      values: {
        healthcare_services: {
          rise: ["central-park", "cherry-creek"],
          enter: ["central-park"],
          fall: ["rino", "santa-fe-arts-district"],
          attributes: ["ecosystems", "clientAccessibility", "parkingPattern"],
        },
      },
    },
  },
  priorities: {
    regional_transit: {
      label: "Transit access",
      attributes: ["transitOrientation", "walkability"],
      riseHigh: ["downtown-denver", "lodo"],
      fallLow: ["central-park", "denver-tech-center"],
    },
    parking: {
      label: "Parking and driving practicality",
      attributes: ["parkingPattern", "freewayAccess"],
      riseHigh: ["denver-tech-center", "central-park", "cherry-creek"],
      fallLow: ["downtown-denver", "lodo", "rino"],
      enter: ["central-park"],
    },
    client_access: {
      label: "Client access",
      attributes: ["clientAccessibility", "districtImage"],
      riseHigh: ["downtown-denver", "cherry-creek", "lodo", "denver-tech-center"],
      fallLow: ["rino", "santa-fe-arts-district"],
    },
    recruiting: {
      label: "Recruiting and employee attraction",
      attributes: ["talentAccess", "amenityEnvironment", "districtImage"],
      riseHigh: ["downtown-denver", "lodo", "rino", "cherry-creek", "denver-tech-center"],
    },
    walkability_amenities: {
      label: "Walkability and amenities",
      attributes: ["walkability", "amenityEnvironment"],
      riseHigh: ["downtown-denver", "lodo", "rino", "cherry-creek"],
      fallLow: ["denver-tech-center", "central-park"],
    },
    growth_flexibility: {
      label: "Growth flexibility",
      attributes: ["growthFlexibility"],
      riseHigh: ["denver-tech-center", "downtown-denver", "rino"],
      fallLow: ["santa-fe-arts-district"],
    },
    freeway_access: {
      label: "Highway access",
      attributes: ["freewayAccess", "parkingPattern"],
      riseHigh: ["denver-tech-center", "central-park", "downtown-denver", "rino"],
      fallLow: [],
      enter: ["central-park"],
    },
  },
  businessTypeEffects: {
    technology: {
      rise: ["rino", "denver-tech-center", "downtown-denver", "lodo"],
      attributes: ["ecosystems", "talentAccess", "growthFlexibility"],
    },
    professional_services: {
      rise: ["downtown-denver", "cherry-creek", "lodo"],
      fall: ["santa-fe-arts-district"],
      attributes: ["clientAccessibility", "districtImage"],
    },
    law_firm: {
      rise: ["downtown-denver", "cherry-creek", "lodo"],
      fall: ["rino", "santa-fe-arts-district"],
      attributes: ["legal", "clientAccessibility", "districtImage"],
    },
    healthcare: {
      rise: ["central-park", "cherry-creek", "downtown-denver"],
      enter: ["central-park"],
      fall: ["rino", "santa-fe-arts-district"],
      attributes: ["healthcare", "clientAccessibility", "parkingPattern"],
    },
    nonprofit: {
      rise: ["downtown-denver", "lodo", "rino"],
      attributes: ["civic", "transitOrientation", "creativeCharacter"],
    },
    mission_driven: {
      rise: ["downtown-denver", "lodo", "rino"],
      attributes: ["civic", "transitOrientation", "creativeCharacter"],
    },
    design_creative: {
      rise: ["rino", "lodo", "santa-fe-arts-district", "cherry-creek"],
      enter: ["santa-fe-arts-district"],
      fall: ["downtown-denver", "denver-tech-center"],
      attributes: ["creativeCharacter", "ecosystems"],
    },
  },
  operationalUseEffects: {
    client_meetings: { priorityAlias: "client_access" },
    team_collaboration: { priorityAlias: "recruiting" },
    recruiting: { priorityAlias: "recruiting" },
    administrative_office: {
      rise: ["downtown-denver", "denver-tech-center", "central-park"],
      enter: ["central-park"],
      attributes: ["corporateEnvironment", "parkingPattern", "clientAccessibility"],
    },
    healthcare_services: { constraintAlias: "institutionProximity", value: "healthcare_services" },
    showroom_presentation: {
      rise: ["rino", "santa-fe-arts-district", "cherry-creek"],
      enter: ["santa-fe-arts-district"],
      attributes: ["ecosystems", "creativeCharacter", "clientAccessibility"],
    },
    quiet_focused_work: {
      rise: ["cherry-creek", "denver-tech-center"],
      attributes: ["districtImage", "parkingPattern"],
    },
  },
  confidenceStates: {
    starting_set: {
      label: "Starting set",
      description: "Rofo knows Denver and office and can identify credible office districts, but should not imply a precise ranking.",
      ordered: false,
    },
    emerging_ranking: {
      label: "Emerging ranking",
      description: "Rofo has enough business context to show which Denver districts are separating and why, while preserving near ties.",
      ordered: true,
    },
    refined_shortlist: {
      label: "Refined shortlist",
      description: "Rofo can defend a smaller Denver shortlist because multiple user signals point toward the same durable district attributes.",
      ordered: true,
    },
  },
  nextQuestions: {
    commuteOrientation: {
      questionId: "commuteOrientation",
      prompt: "Should the office lean central Denver, southeast metro, east Denver, or transit-oriented?",
      targets: ["transitOrientation", "parkingPattern", "southeastMetroAccess", "freewayAccess"],
    },
    officeEnvironment: {
      questionId: "officeEnvironment",
      prompt: "What kind of office environment would fit the business?",
      targets: ["creativeCharacter", "modernEnvironment", "lowerRiseCharacter", "districtImage"],
    },
    clientVisitFrequency: {
      questionId: "clientVisitFrequency",
      prompt: "How often will clients, partners, patients, or stakeholders visit the office?",
      targets: ["clientAccessibility", "districtImage"],
    },
    expectedGrowth: {
      questionId: "expectedGrowth",
      prompt: "Do you expect the team to grow meaningfully in the next 12 to 24 months?",
      targets: ["growthFlexibility"],
    },
    businessType: {
      questionId: "businessType",
      prompt: "Which description is closest to your business?",
      targets: ["ecosystems"],
    },
  },
  explanationTemplates: {
    rise: "{districtName} moved up because {signalLabel} aligns with {attributeLabel}.",
    fall: "{districtName} moved down because {signalLabel} makes {attributeLabel} less aligned than stronger candidates.",
    enter: "{districtName} entered consideration because {signalLabel} matches {attributeLabel}.",
    tie: "{districtA} and {districtB} remain close because both support {sharedSignal}.",
    excluded: "{districtName} was excluded because {reason}.",
    costIgnored: "Budget, rent, value, and cost language was preserved for broker review but did not affect Denver district ranking.",
  },
};
