function clean(value) {
  return String(value || "").trim();
}

function slugify(value) {
  return clean(value)
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildingPath(address) {
  return `/commercial-real-estate/building/CA/berkeley/${slugify(address)}/`;
}

const downtownBerkeleyDistrict = {
  id: "eb-downtown-berkeley",
  name: "Downtown Berkeley",
  slug: "downtown-berkeley",
  city: "Berkeley",
  state_abbr: "CA",
  area_type: "downtown_core",
  path: "/commercial-real-estate/CA/berkeley/downtown-berkeley/",
  primarySpaceType: "office",
};

const relatedDistricts = [
  {
    label: "Emeryville Commercial Core",
    url: "/commercial-real-estate/CA/emeryville/emeryville-commercial-core/",
    reason: "Compare when a more campus-oriented East Bay office setting, parking, and freeway access matter more.",
  },
  {
    label: "West Berkeley",
    url: "/commercial-real-estate/CA/berkeley/west-berkeley/",
    reason: "Compare when industrial/flex character, maker activity, or production-oriented buildings matter more.",
  },
  {
    label: "Jack London Square",
    url: "/commercial-real-estate/CA/oakland/jack-london-square/",
    reason: "Compare when Oakland waterfront identity and a broader Oakland client or creative-office context matter more.",
  },
];

const handbookTopics = [
  {
    title: "Choosing the Right Commercial Location",
    url: "/commercial-real-estate/lease-guide/choosing-the-right-commercial-location/",
    summary: "Use location fit, access, customers, employees, and operations before narrowing the building list.",
  },
  {
    title: "How to Compare Commercial Spaces",
    url: "/commercial-real-estate/lease-guide/how-to-compare-commercial-spaces/",
    summary: "Compare buildings by business fit, total occupancy cost, operations, buildout, and future flexibility.",
  },
  {
    title: "Tenant Improvements",
    url: "/commercial-real-estate/lease-guide/tenant-improvements/",
    summary: "Understand buildout scope, timing, landlord approvals, and what to validate before leasing.",
  },
];

const defaultNearbyBuildings = [
  buildingPath("2140 Shattuck Ave"),
  buildingPath("2150 Shattuck Ave"),
  buildingPath("2168 Shattuck Ave"),
  buildingPath("2030 Addison St"),
  buildingPath("2130 Center St"),
];

function officeRetailBrief(fields) {
  const snapshot = fields.snapshot || [];
  const bestFit = fields.bestFit || [];
  const validationNotes = fields.validationNotes || [];

  return {
    status: "published",
    ecosystemContext: {
      primaryEcosystem: "office",
      secondaryEcosystems: ["retail"],
      ecosystemSubtypes: fields.ecosystemSubtypes,
      representativeRole: fields.representativeRole,
    },
    businessFit: {
      archetypes: fields.businessArchetypes,
      activities: fields.businessActivities,
      fitSummary: fields.fitSummary,
    },
    operationalProfile: fields.operationalProfile || [],
    environmentExplanation: fields.environmentExplanation,
    comparisonContext: {
      relatedDistricts,
    },
    evidence: {
      confidence: fields.confidence || "editorially_supported",
      provenance: {
        ecosystem: "commercial-market-evidence",
        operationalCharacteristics: "district-and-building-profile",
        editorialInterpretation: "building-brief",
      },
      sourceNotes: fields.sourceNotes || [],
    },
    summary: fields.summary,
    rofoTake: fields.rofoTake,
    buildingSummary: fields.summary,
    buildingImportance: fields.rofoTake,
    snapshot,
    quickFacts: snapshot,
    bestFit,
    idealFor: bestFit,
    mayNotFit: fields.mayNotFit || [],
    buildingExperience: fields.buildingExperience,
    locationContext: fields.locationContext,
    districtContext: fields.locationContext,
    advantages: fields.advantages || [],
    tradeoffs: fields.tradeoffs || [],
    validationNotes,
    validationChecklist: validationNotes,
    nearbyDistricts: relatedDistricts,
    nearbyAlternatives: fields.nearbyAlternatives || [],
    relatedInsights: handbookTopics,
    representativeCompanies: fields.representativeCompanies || [],
    ecosystemSubtypes: fields.ecosystemSubtypes,
    representativeRole: fields.representativeRole,
    businessActivities: fields.businessActivities,
    businessArchetypes: fields.businessArchetypes,
    operationalCharacteristics: fields.operationalCharacteristics || [],
    fitSummary: fields.fitSummary,
    confidence: fields.confidence || "editorially_supported",
    sourceNotes: fields.sourceNotes || [],
  };
}

function record(fields) {
  const path = buildingPath(fields.address);
  const brief = officeRetailBrief(fields.brief);

  return {
    id: `east-bay-downtown-berkeley-${slugify(fields.address)}`,
    building_path: path,
    identity: {
      name: fields.name,
      address: fields.address,
      city: "Berkeley",
      state_abbr: "CA",
      district: downtownBerkeleyDistrict.name,
      canonicalDistrict: downtownBerkeleyDistrict,
      secondaryDistricts: fields.secondaryDistricts || [],
      buildingType: fields.buildingType || "Downtown office / service-commercial building",
      primarySpaceType: "office",
      assetClass: fields.assetClass || "Representative Office / Retail Building",
    },
    editorial: {
      editorialRole: fields.editorialRole,
      editorialReason: fields.editorialReason,
      representativeThemes: fields.representativeThemes,
    },
    business: {
      businessFit: fields.businessFit,
      idealCompanyProfiles: brief.idealFor,
      companySizes: fields.companySizes || ["small businesses", "professional-service teams", "nonprofits", "education-adjacent organizations"],
    },
    experience: {
      workplaceCharacter: "Walkable Downtown Berkeley office and service-commercial environment shaped by BART, UC Berkeley adjacency, civic activity, restaurants, and smaller urban floorplates.",
      neighborhoodCharacter: "Transit-oriented university downtown with stronger walkability and customer access than suburban parking or campus-style office scale.",
      executivePresence: fields.executivePresence || "medium",
      innovationScore: fields.innovationScore || "moderate",
    },
    operations: {
      transit: "Downtown Berkeley BART and local transit are core location advantages, with exact walking route and arrival pattern depending on the address.",
      parking: "Parking is more constrained than in Emeryville or suburban East Bay districts and should be validated early.",
      amenities: "Restaurants, civic uses, UC Berkeley adjacency, and downtown services shape the district experience.",
      foodEnvironment: "Street-level food and service access is a meaningful advantage for many downtown office, nonprofit, and service users.",
    },
    tradeoffs: {
      strengths: brief.advantages,
      limitations: brief.tradeoffs,
      businessesThatShouldCompare: brief.mayNotFit,
      nearbyAlternatives: relatedDistricts.map((item) => item.url),
    },
    validation: {
      questionsToValidate: brief.validationNotes,
      tourObservations: brief.validationNotes.slice(0, 3),
    },
    relationships: {
      nearbyBuildings: (fields.nearbyBuildingPaths || defaultNearbyBuildings).filter((item) => item !== path).slice(0, 5),
      comparisonBuildings: (fields.comparisonBuildingPaths || defaultNearbyBuildings).filter((item) => item !== path).slice(0, 5),
      relatedDistricts: relatedDistricts.map((item) => item.url),
    },
    quality: {
      sourceConfidence: fields.sourceConfidence || "medium",
      publicationStatus: "published",
      sourceBasis: "Downtown Berkeley Commercial Market Evidence district-building mission",
    },
    buildingBrief: brief,
  };
}

function briefFor(fields) {
  return {
    summary: `${fields.name} is a Downtown Berkeley Building Profile for ${fields.fitLine}. It helps users compare BART access, UC Berkeley adjacency, downtown services, and smaller urban office or service-commercial fit against Emeryville, West Berkeley, and Oakland alternatives.`,
    rofoTake: `${fields.name} matters because Downtown Berkeley needs concrete examples of its walkable university-adjacent office and retail-support environment. This profile explains ${fields.roleLower} without implying current availability, tenancy, pricing, or specialized use suitability.`,
    snapshot: [
      { label: "Primary ecosystem", value: "Office" },
      { label: "Secondary context", value: fields.secondaryContext },
      { label: "District", value: "Downtown Berkeley" },
      { label: "Access context", value: fields.accessContext },
      { label: "Evidence role", value: fields.evidenceRole },
      { label: "Validation context", value: "Suite condition, access, parking, signage, and current terms require verification" },
    ],
    bestFit: [
      fields.bestFitPrimary,
      "Organizations that value Downtown Berkeley BART access, UC Berkeley adjacency, restaurants, and walkable services.",
      "Users comparing Downtown Berkeley's urban convenience against Emeryville office parks, West Berkeley flex buildings, or Oakland alternatives.",
    ],
    mayNotFit: [
      "Companies that need heavy parking, truck access, warehouse utility, lab infrastructure, or large campus-style expansion.",
      "Users whose brand or operations depend on suburban arrival patterns, dedicated customer parking, or a quieter office-park setting.",
      "Industrial, medical, or specialized technical users whose requirements must be validated at a property-specific level.",
    ],
    buildingExperience: `Evaluate ${fields.name} around daily arrival, BART usefulness, visitor access, suite layout, parking strategy, and whether the surrounding downtown activity supports the business.`,
    locationContext: `${fields.name} supports Downtown Berkeley's commercial-market evidence by showing ${fields.locationContext}. Compare nearby Shattuck, Addison, Allston, Bancroft, and Milvia examples before deciding whether the user needs central transit access, campus adjacency, or a quieter East Bay alternative.`,
    advantages: fields.advantages,
    tradeoffs: [
      "Parking and visitor arrival can be harder than in more auto-oriented East Bay office markets.",
      "Older or smaller downtown buildings can require careful validation of layout, access, building systems, signage, and improvement scope.",
      "The profile does not establish current availability, tenant mix, rent, or permitted-use fit.",
    ],
    operationalProfile: [
      { label: "Transit-oriented office", summary: "Use this profile when BART access and walkable downtown services are part of the location decision." },
      { label: "University adjacency", summary: "Validate whether proximity to UC Berkeley helps with clients, staff, programs, customers, or institutional relationships." },
      { label: "Urban tradeoff", summary: "Compare transit and downtown access against parking, expansion needs, visitor arrival, and building-specific condition." },
    ],
    environmentExplanation: {
      whyItExists: "Downtown Berkeley office and service-commercial buildings exist for users that benefit from transit, university adjacency, civic access, and walkable customer or employee activity.",
      whyChooseThisEnvironment: "Choose this environment when Berkeley identity and downtown access matter more than parking-heavy or campus-style office geography.",
      representativeValue: `${fields.name} gives Rofo a ${fields.representativeValue}.`,
    },
    nearbyAlternatives: fields.nearbyAlternatives,
    validationNotes: [
      "Confirm current availability, suite size, floorplate, shared areas, and buildout condition before relying on the profile.",
      "Validate parking, visitor arrival, bike/transit access, and whether BART proximity fits employees and customers.",
      "Confirm signage, street visibility, access control, hours, and customer-facing suitability where relevant.",
      "Compare Downtown Berkeley with Emeryville, West Berkeley, and Oakland if parking, industrial/flex needs, or larger office scale matter more.",
    ],
    ecosystemSubtypes: fields.ecosystemSubtypes,
    representativeRole: fields.representativeRole,
    businessActivities: fields.businessActivities,
    businessArchetypes: fields.businessArchetypes,
    operationalCharacteristics: fields.operationalCharacteristics,
    fitSummary: "Downtown Berkeley fit depends on BART access, UC Berkeley adjacency, walkability, visitor pattern, parking tolerance, and whether the building supports the user's office or service-commercial workflow.",
    sourceNotes: [
      `Repository representative building page expansions identify ${fields.name} as a Downtown Berkeley representative building for ${fields.sourceContext}.`,
      "The Knowledge Graph identifies Downtown Berkeley as a BART- and UC Berkeley-adjacent office and retail district.",
    ],
  };
}

const records = [
  record({
    name: "1936 University Ave",
    address: "1936 University Ave",
    editorialRole: "University Avenue Service-Office Benchmark",
    editorialReason: "Represents the University Avenue side of Downtown Berkeley for service, professional-office, and local customer-access users.",
    representativeThemes: ["University Avenue", "Downtown Berkeley", "Service office", "BART access"],
    businessFit: ["professional office", "service business", "education-adjacent organization", "local customer-facing office"],
    nearbyBuildingPaths: [buildingPath("2030 Addison St"), buildingPath("2140 Shattuck Ave"), buildingPath("2070 Allston Way")],
    comparisonBuildingPaths: [buildingPath("2030 Addison St"), buildingPath("2140 Shattuck Ave"), "/commercial-real-estate/building/CA/berkeley/650-university-ave/"],
    brief: briefFor({
      name: "1936 University Ave",
      fitLine: "service businesses, professional offices, and education-adjacent users evaluating University Avenue",
      roleLower: "the University Avenue service-office pattern",
      secondaryContext: "University Avenue service commercial and office",
      accessContext: "University Avenue, Downtown Berkeley BART, and UC Berkeley adjacency",
      evidenceRole: "University Avenue service-office benchmark",
      bestFitPrimary: "Service businesses, small professional offices, and education-adjacent teams that want University Avenue visibility and central Berkeley access.",
      locationContext: "how University Avenue extends the district beyond the Shattuck core",
      representativeValue: "University Avenue service-office benchmark",
      sourceContext: "University Avenue commercial context",
      advantages: [
        "Adds University Avenue evidence to the Downtown Berkeley collection.",
        "Helps users compare corridor visibility with central Shattuck office options.",
        "Connects office and service-commercial fit to BART and UC Berkeley adjacency.",
      ],
      nearbyAlternatives: [
        { label: "2030 Addison St", url: buildingPath("2030 Addison St"), reason: "Compare when civic-adjacent office context matters more than University Avenue frontage." },
        { label: "2140 Shattuck Ave", url: buildingPath("2140 Shattuck Ave"), reason: "Compare when central Shattuck Avenue office identity matters more." },
        { label: "650 University Ave", url: "/commercial-real-estate/building/CA/berkeley/650-university-ave/", reason: "Compare when west-side Berkeley access and flex/service context matter more." },
      ],
      ecosystemSubtypes: ["professional_office", "service_commercial", "university_adjacent_office"],
      representativeRole: "university_avenue_service_office_benchmark",
      businessActivities: ["professional_services", "client_meetings", "customer_service", "education_support"],
      businessArchetypes: ["professional_services_firm", "nonprofit", "education_support_organization", "local_service_business"],
      operationalCharacteristics: ["bart_access", "university_adjacency", "street_visibility", "parking_validation_required"],
    }),
  }),
  record({
    name: "2030 Addison St",
    address: "2030 Addison St",
    editorialRole: "Addison Street Professional Office Benchmark",
    editorialReason: "Adds civic and arts-adjacent office evidence near Downtown Berkeley's BART and Shattuck core.",
    representativeThemes: ["Addison Street", "Professional office", "Civic core", "Arts adjacency"],
    businessFit: ["professional office", "nonprofit office", "civic-adjacent organization", "education-adjacent office"],
    nearbyBuildingPaths: [buildingPath("2130 Center St"), buildingPath("2168 Shattuck Ave"), buildingPath("2118 Milvia St")],
    comparisonBuildingPaths: [buildingPath("2130 Center St"), buildingPath("2168 Shattuck Ave"), buildingPath("1936 University Ave")],
    brief: briefFor({
      name: "2030 Addison St",
      fitLine: "professional-service, nonprofit, and civic-adjacent users comparing Addison Street with Shattuck and Center Street",
      roleLower: "the Addison Street professional-office pattern",
      secondaryContext: "Civic, arts, and professional-office context",
      accessContext: "Addison Street, Downtown Berkeley BART, civic uses, and Shattuck Avenue",
      evidenceRole: "Addison Street professional office benchmark",
      bestFitPrimary: "Professional-service firms, nonprofits, and civic-adjacent organizations that want central Berkeley access without relying on a primary Shattuck frontage.",
      locationContext: "how Addison Street contributes civic and arts-adjacent office evidence to the district",
      representativeValue: "civic-adjacent professional-office benchmark",
      sourceContext: "professional office and civic-adjacent commercial context",
      advantages: [
        "Adds Addison Street office evidence near BART and civic activity.",
        "Helps distinguish Downtown Berkeley from campus-only or industrial/flex Berkeley choices.",
        "Supports nonprofit, professional-service, and institution-adjacent office fit.",
      ],
      nearbyAlternatives: [
        { label: "2130 Center St", url: buildingPath("2130 Center St"), reason: "Compare when Center Street and civic/arts proximity are stronger requirements." },
        { label: "2168 Shattuck Ave", url: buildingPath("2168 Shattuck Ave"), reason: "Compare when a central Shattuck professional-office benchmark is preferred." },
        { label: "1936 University Ave", url: buildingPath("1936 University Ave"), reason: "Compare when University Avenue visibility and service-commercial corridor context matter more than Addison Street civic adjacency." },
      ],
      ecosystemSubtypes: ["professional_office", "civic_adjacent_office", "university_adjacent_office"],
      representativeRole: "addison_street_professional_office_benchmark",
      businessActivities: ["professional_services", "client_meetings", "nonprofit_operations", "education_support"],
      businessArchetypes: ["professional_services_firm", "nonprofit", "education_support_organization", "civic_partner"],
      operationalCharacteristics: ["bart_access", "civic_adjacency", "walkable_services", "parking_validation_required"],
    }),
  }),
  record({
    name: "2040 Bancroft Way",
    address: "2040 Bancroft Way",
    editorialRole: "UC Berkeley Edge Benchmark",
    editorialReason: "Represents university-edge office and service decisions on the east side of Downtown Berkeley.",
    representativeThemes: ["UC Berkeley adjacency", "University-edge office", "Bancroft Way", "Downtown Berkeley"],
    businessFit: ["education-adjacent office", "nonprofit office", "student-serving service business", "professional office"],
    nearbyBuildingPaths: [buildingPath("2130 Center St"), buildingPath("2070 Allston Way"), buildingPath("2118 Milvia St")],
    comparisonBuildingPaths: [buildingPath("2130 Center St"), buildingPath("2070 Allston Way"), "/commercial-real-estate/CA/emeryville/emeryville-commercial-core/"],
    brief: briefFor({
      name: "2040 Bancroft Way",
      fitLine: "education-adjacent organizations, nonprofits, and service users evaluating the UC Berkeley edge",
      roleLower: "the university-edge office and service pattern",
      secondaryContext: "UC Berkeley edge office and service context",
      accessContext: "Bancroft Way, UC Berkeley adjacency, and Downtown Berkeley services",
      evidenceRole: "UC Berkeley edge benchmark",
      bestFitPrimary: "Education-adjacent organizations, nonprofits, and service businesses that benefit from being close to the UC Berkeley edge.",
      locationContext: "how the campus edge differs from central Shattuck, Addison, and University Avenue options",
      representativeValue: "UC Berkeley edge office benchmark",
      sourceContext: "university-edge office and service users",
      advantages: [
        "Adds campus-edge evidence to the Downtown Berkeley collection.",
        "Helps users evaluate whether UC Berkeley adjacency is operationally useful.",
        "Complements central Shattuck and civic-core examples.",
      ],
      nearbyAlternatives: [
        { label: "2130 Center St", url: buildingPath("2130 Center St"), reason: "Compare when civic and arts context matter as much as campus adjacency." },
        { label: "2070 Allston Way", url: buildingPath("2070 Allston Way"), reason: "Compare when a smaller secondary-street office setting fits better." },
        { label: "Emeryville Commercial Core", url: "/commercial-real-estate/CA/emeryville/emeryville-commercial-core/", reason: "Compare when parking and campus-style office geography matter more than direct UC Berkeley edge access." },
      ],
      ecosystemSubtypes: ["university_adjacent_office", "professional_office", "service_commercial"],
      representativeRole: "uc_berkeley_edge_benchmark",
      businessActivities: ["education_support", "professional_services", "client_meetings", "customer_service"],
      businessArchetypes: ["education_support_organization", "nonprofit", "professional_services_firm", "student_serving_business"],
      operationalCharacteristics: ["university_adjacency", "walkable_services", "bart_access", "parking_validation_required"],
    }),
  }),
  record({
    name: "2070 Allston Way",
    address: "2070 Allston Way",
    editorialRole: "Allston Way Small Office Benchmark",
    editorialReason: "Shows a smaller secondary-street office pattern close to Downtown Berkeley's transit, civic, and university-adjacent activity.",
    representativeThemes: ["Small office", "Allston Way", "Secondary street", "Downtown Berkeley"],
    businessFit: ["small office", "consulting office", "local service business", "professional services"],
    nearbyBuildingPaths: [buildingPath("2118 Milvia St"), buildingPath("2130 Center St"), buildingPath("2168 Shattuck Ave")],
    comparisonBuildingPaths: [buildingPath("2118 Milvia St"), buildingPath("2130 Center St"), buildingPath("2140 Shattuck Ave")],
    brief: briefFor({
      name: "2070 Allston Way",
      fitLine: "small professional offices and service users comparing secondary-street downtown options",
      roleLower: "the smaller secondary-street office pattern",
      secondaryContext: "Small professional office and service-commercial context",
      accessContext: "Allston Way, Shattuck Avenue, BART, and the civic core",
      evidenceRole: "Allston Way small office benchmark",
      bestFitPrimary: "Small professional offices, consultants, and local service users that want central Berkeley access without a larger tower or business-park setting.",
      locationContext: "how secondary-street office buildings complement Shattuck and University Avenue examples",
      representativeValue: "small-office benchmark off the primary frontage",
      sourceContext: "smaller professional office and service users near the downtown core",
      advantages: [
        "Adds small-office evidence beyond primary Shattuck Avenue buildings.",
        "Helps users compare visibility against quieter downtown access.",
        "Supports Downtown Berkeley's smaller-team office story.",
      ],
      nearbyAlternatives: [
        { label: "2118 Milvia St", url: buildingPath("2118 Milvia St"), reason: "Compare when a quieter civic-core service-office setting is preferred." },
        { label: "2130 Center St", url: buildingPath("2130 Center St"), reason: "Compare when Center Street civic and arts context matters more." },
        { label: "2140 Shattuck Ave", url: buildingPath("2140 Shattuck Ave"), reason: "Compare when main-corridor Shattuck Avenue identity and BART-oriented office visibility matter more than Allston Way's quieter setting." },
      ],
      ecosystemSubtypes: ["small_tenant_office", "professional_office", "service_commercial"],
      representativeRole: "allston_way_small_office_benchmark",
      businessActivities: ["professional_services", "client_meetings", "customer_service", "administrative_operations"],
      businessArchetypes: ["consulting_firm", "professional_services_firm", "local_service_business", "nonprofit"],
      operationalCharacteristics: ["small_tenant_fit", "bart_access", "walkable_services", "parking_validation_required"],
    }),
  }),
  record({
    name: "2118 Milvia St",
    address: "2118 Milvia St",
    editorialRole: "Milvia Street Service-Office Benchmark",
    editorialReason: "Adds a quieter civic-core office example for local service and smaller professional users.",
    representativeThemes: ["Milvia Street", "Service office", "Civic core", "Small office"],
    businessFit: ["small professional office", "local service business", "nonprofit office", "administrative office"],
    nearbyBuildingPaths: [buildingPath("2070 Allston Way"), buildingPath("2030 Addison St"), buildingPath("2130 Center St")],
    comparisonBuildingPaths: [buildingPath("2070 Allston Way"), buildingPath("2030 Addison St"), buildingPath("2168 Shattuck Ave")],
    brief: briefFor({
      name: "2118 Milvia St",
      fitLine: "local service businesses and smaller office users near the civic core",
      roleLower: "the Milvia Street civic-core service-office pattern",
      secondaryContext: "Civic-core service office and small office context",
      accessContext: "Milvia Street, BART, civic activity, and Downtown Berkeley services",
      evidenceRole: "Milvia Street service-office benchmark",
      bestFitPrimary: "Small professional offices, local service businesses, and community-serving organizations that want central Berkeley access in a quieter downtown position.",
      locationContext: "how Milvia Street expands the collection beyond Shattuck frontage and campus-edge examples",
      representativeValue: "civic-core small service-office benchmark",
      sourceContext: "local service and smaller office users near the civic core",
      advantages: [
        "Adds quieter civic-core office evidence.",
        "Helps smaller users compare Milvia, Allston, Addison, and Shattuck options.",
        "Supports Downtown Berkeley's local-service and professional-office range.",
      ],
      nearbyAlternatives: [
        { label: "2070 Allston Way", url: buildingPath("2070 Allston Way"), reason: "Compare when Allston Way secondary-street office fit is similar." },
        { label: "2030 Addison St", url: buildingPath("2030 Addison St"), reason: "Compare when Addison Street civic and arts adjacency matters more." },
        { label: "2168 Shattuck Ave", url: buildingPath("2168 Shattuck Ave"), reason: "Compare when central Shattuck professional-office identity matters more." },
      ],
      ecosystemSubtypes: ["small_tenant_office", "service_commercial", "professional_office"],
      representativeRole: "milvia_street_service_office_benchmark",
      businessActivities: ["professional_services", "customer_service", "administrative_operations", "nonprofit_operations"],
      businessArchetypes: ["local_service_business", "professional_services_firm", "nonprofit", "community_serving_organization"],
      operationalCharacteristics: ["small_tenant_fit", "civic_adjacency", "walkable_services", "parking_validation_required"],
    }),
  }),
  record({
    name: "2130 Center St",
    address: "2130 Center St",
    editorialRole: "Center Street Civic Office Benchmark",
    editorialReason: "Represents Center Street's civic, arts, BART, and university-adjacent office setting.",
    representativeThemes: ["Center Street", "Civic office", "Arts adjacency", "BART access"],
    businessFit: ["nonprofit office", "professional office", "civic-adjacent organization", "education-adjacent office"],
    nearbyBuildingPaths: [buildingPath("2030 Addison St"), buildingPath("2040 Bancroft Way"), buildingPath("2168 Shattuck Ave")],
    comparisonBuildingPaths: [buildingPath("2030 Addison St"), buildingPath("2040 Bancroft Way"), buildingPath("2140 Shattuck Ave")],
    brief: briefFor({
      name: "2130 Center St",
      fitLine: "civic-adjacent, nonprofit, and professional office users near BART and the UC Berkeley edge",
      roleLower: "the Center Street civic-office pattern",
      secondaryContext: "Civic, arts, transit, and university-adjacent office context",
      accessContext: "Center Street, BART, civic uses, arts venues, and UC Berkeley adjacency",
      evidenceRole: "Center Street civic office benchmark",
      bestFitPrimary: "Nonprofits, civic-adjacent organizations, professional offices, and education-adjacent teams that want BART access and a central Berkeley setting.",
      locationContext: "how Center Street connects civic, arts, transit, and university-adjacent demand",
      representativeValue: "Center Street civic-office benchmark",
      sourceContext: "civic, arts, and professional office context near the district core",
      advantages: [
        "Adds Center Street civic and arts-adjacent evidence.",
        "Helps users compare civic-core fit against Shattuck and campus-edge options.",
        "Supports nonprofit and institution-adjacent office decisions.",
      ],
      nearbyAlternatives: [
        { label: "2030 Addison St", url: buildingPath("2030 Addison St"), reason: "Compare when Addison Street professional-office context is similar." },
        { label: "2040 Bancroft Way", url: buildingPath("2040 Bancroft Way"), reason: "Compare when direct UC Berkeley edge adjacency matters more." },
        { label: "2168 Shattuck Ave", url: buildingPath("2168 Shattuck Ave"), reason: "Compare when central Shattuck professional-office identity matters more." },
      ],
      ecosystemSubtypes: ["civic_adjacent_office", "professional_office", "university_adjacent_office"],
      representativeRole: "center_street_civic_office_benchmark",
      businessActivities: ["nonprofit_operations", "professional_services", "client_meetings", "education_support"],
      businessArchetypes: ["nonprofit", "civic_partner", "professional_services_firm", "education_support_organization"],
      operationalCharacteristics: ["bart_access", "civic_adjacency", "university_adjacency", "parking_validation_required"],
    }),
  }),
  record({
    name: "2140 Shattuck Ave",
    address: "2140 Shattuck Ave",
    editorialRole: "Shattuck Corridor Office Benchmark",
    editorialReason: "Anchors Downtown Berkeley's core Shattuck Avenue office and BART-oriented professional-service context.",
    representativeThemes: ["Shattuck Avenue", "Transit-oriented office", "Professional services", "Downtown Berkeley"],
    businessFit: ["professional office", "client-facing office", "education-adjacent office", "nonprofit office"],
    nearbyBuildingPaths: [buildingPath("2150 Shattuck Ave"), buildingPath("2168 Shattuck Ave"), buildingPath("1936 University Ave")],
    comparisonBuildingPaths: [buildingPath("2150 Shattuck Ave"), buildingPath("2168 Shattuck Ave"), "/commercial-real-estate/CA/emeryville/emeryville-commercial-core/"],
    brief: briefFor({
      name: "2140 Shattuck Ave",
      fitLine: "transit-oriented office users and professional-service firms evaluating the Shattuck Avenue core",
      roleLower: "the Shattuck Avenue transit-oriented office pattern",
      secondaryContext: "Core Shattuck Avenue professional office",
      accessContext: "Shattuck Avenue, Downtown Berkeley BART, UC Berkeley, and downtown services",
      evidenceRole: "Shattuck corridor office benchmark",
      bestFitPrimary: "Professional-service firms, nonprofits, and education-adjacent teams that want the main Downtown Berkeley office corridor and BART access.",
      locationContext: "how Shattuck Avenue anchors the district's office and professional-service identity",
      representativeValue: "central Shattuck transit-oriented office benchmark",
      sourceContext: "Shattuck corridor and BART-oriented business context",
      advantages: [
        "Anchors the collection's Shattuck Avenue office evidence.",
        "Shows why BART and walkability can drive Downtown Berkeley fit.",
        "Creates a useful comparison against Emeryville's parking-oriented office geography.",
      ],
      nearbyAlternatives: [
        { label: "2150 Shattuck Ave", url: buildingPath("2150 Shattuck Ave"), reason: "Compare another central Shattuck professional-office benchmark when the search is focused on BART-oriented corridor identity." },
        { label: "2168 Shattuck Ave", url: buildingPath("2168 Shattuck Ave"), reason: "Compare when Constitution Square and central corridor identity are relevant." },
        { label: "Emeryville Commercial Core", url: "/commercial-real-estate/CA/emeryville/emeryville-commercial-core/", reason: "Compare when parking and campus-style office geography matter more." },
      ],
      ecosystemSubtypes: ["professional_office", "transit_oriented_office", "university_adjacent_office"],
      representativeRole: "shattuck_corridor_office_benchmark",
      businessActivities: ["professional_services", "client_meetings", "education_support", "administrative_operations"],
      businessArchetypes: ["professional_services_firm", "consulting_firm", "nonprofit", "education_support_organization"],
      operationalCharacteristics: ["bart_access", "walkable_services", "university_adjacency", "parking_validation_required"],
    }),
  }),
  record({
    name: "2150 Shattuck Ave",
    address: "2150 Shattuck Ave",
    editorialRole: "BART-Oriented Professional Office Benchmark",
    editorialReason: "Strengthens central Shattuck coverage for professional office and institution-adjacent users.",
    representativeThemes: ["Central Shattuck", "Professional office", "BART-oriented office", "Downtown Berkeley"],
    businessFit: ["professional office", "consulting office", "education-adjacent office", "regional project office"],
    nearbyBuildingPaths: [buildingPath("2140 Shattuck Ave"), buildingPath("2168 Shattuck Ave"), buildingPath("2300 Shattuck Ave")],
    comparisonBuildingPaths: [buildingPath("2140 Shattuck Ave"), buildingPath("2168 Shattuck Ave"), buildingPath("2300 Shattuck Ave")],
    brief: briefFor({
      name: "2150 Shattuck Ave",
      fitLine: "professional-service firms and education-adjacent office users comparing central Shattuck Avenue options",
      roleLower: "the central Shattuck professional-office pattern",
      secondaryContext: "Central Shattuck professional office",
      accessContext: "Shattuck Avenue, BART, downtown services, and UC Berkeley adjacency",
      evidenceRole: "BART-oriented professional office benchmark",
      bestFitPrimary: "Professional-service firms, consulting teams, nonprofits, and university-facing organizations that want a central Shattuck office setting.",
      locationContext: "how central Shattuck gives Downtown Berkeley its clearest professional-office corridor",
      representativeValue: "central Shattuck professional-office benchmark",
      sourceContext: "BART and university-adjacent commercial core",
      advantages: [
        "Strengthens central Shattuck Avenue office evidence.",
        "Helps users compare multiple Downtown Berkeley professional-office buildings.",
        "Supports transit-oriented and university-facing office decisions.",
      ],
      nearbyAlternatives: [
        { label: "2140 Shattuck Ave", url: buildingPath("2140 Shattuck Ave"), reason: "Compare another core Shattuck office benchmark when central corridor visibility and BART proximity are the main requirements." },
        { label: "2168 Shattuck Ave", url: buildingPath("2168 Shattuck Ave"), reason: "Compare when Constitution Square is a relevant central Shattuck option." },
        { label: "2300 Shattuck Ave", url: buildingPath("2300 Shattuck Ave"), reason: "Compare when south Shattuck corridor depth and larger-office context matter more." },
      ],
      ecosystemSubtypes: ["professional_office", "transit_oriented_office", "small_tenant_office"],
      representativeRole: "bart_oriented_professional_office_benchmark",
      businessActivities: ["professional_services", "client_meetings", "education_support", "project_office"],
      businessArchetypes: ["professional_services_firm", "consulting_firm", "nonprofit", "regional_project_team"],
      operationalCharacteristics: ["bart_access", "walkable_services", "central_business_corridor", "parking_validation_required"],
    }),
  }),
  record({
    name: "2168 Shattuck Ave",
    address: "2168 Shattuck Ave",
    editorialRole: "Constitution Square Professional Office Benchmark",
    editorialReason: "Adds a named central Shattuck professional-office reference in Rofo source data.",
    representativeThemes: ["Constitution Square", "Professional office", "Central Shattuck", "BART access"],
    businessFit: ["professional office", "consulting office", "nonprofit office", "education-adjacent office"],
    nearbyBuildingPaths: [buildingPath("2140 Shattuck Ave"), buildingPath("2150 Shattuck Ave"), buildingPath("2070 Allston Way")],
    comparisonBuildingPaths: [buildingPath("2140 Shattuck Ave"), buildingPath("2150 Shattuck Ave"), buildingPath("2030 Addison St")],
    brief: briefFor({
      name: "2168 Shattuck Ave",
      fitLine: "professional-office users comparing Constitution Square and other central Shattuck options",
      roleLower: "the Constitution Square professional-office pattern",
      secondaryContext: "Named central Shattuck professional office",
      accessContext: "Shattuck Avenue, Downtown Berkeley BART, and university-facing services",
      evidenceRole: "Constitution Square professional office benchmark",
      bestFitPrimary: "Professional-service firms, consulting teams, nonprofits, and university-facing organizations that want central Shattuck access and a named downtown office reference.",
      locationContext: "how a named central Shattuck building helps users compare Downtown Berkeley office options",
      representativeValue: "named central Shattuck professional-office benchmark",
      sourceContext: "central transit-oriented business corridor",
      advantages: [
        "Adds a named Shattuck Avenue professional-office reference.",
        "Supports Downtown Berkeley's central transit-oriented office story.",
        "Gives users another concrete comparison against 2140 and 2150 Shattuck.",
      ],
      nearbyAlternatives: [
        { label: "2140 Shattuck Ave", url: buildingPath("2140 Shattuck Ave"), reason: "Compare another Shattuck corridor office benchmark when main-street office identity is more important than the named Constitution Square context." },
        { label: "2150 Shattuck Ave", url: buildingPath("2150 Shattuck Ave"), reason: "Compare another BART-oriented professional-office reference when central Shattuck alternatives are still being narrowed." },
        { label: "2030 Addison St", url: buildingPath("2030 Addison St"), reason: "Compare when Addison Street civic and arts context matters more." },
      ],
      ecosystemSubtypes: ["professional_office", "transit_oriented_office", "small_tenant_office"],
      representativeRole: "constitution_square_professional_office_benchmark",
      businessActivities: ["professional_services", "client_meetings", "education_support", "administrative_operations"],
      businessArchetypes: ["professional_services_firm", "consulting_firm", "nonprofit", "education_support_organization"],
      operationalCharacteristics: ["bart_access", "walkable_services", "central_business_corridor", "parking_validation_required"],
    }),
  }),
  record({
    name: "2300 Shattuck Ave",
    address: "2300 Shattuck Ave",
    editorialRole: "South Shattuck Office Scale Benchmark",
    editorialReason: "Adds south Shattuck corridor depth and larger-office comparison value to Downtown Berkeley.",
    representativeThemes: ["South Shattuck", "Office scale", "Professional services", "Downtown Berkeley"],
    businessFit: ["office user", "professional-service firm", "education-adjacent organization", "regional office"],
    nearbyBuildingPaths: [buildingPath("2150 Shattuck Ave"), buildingPath("2168 Shattuck Ave"), buildingPath("2040 Bancroft Way")],
    comparisonBuildingPaths: [buildingPath("2150 Shattuck Ave"), buildingPath("2168 Shattuck Ave"), "/commercial-real-estate/CA/emeryville/emeryville-commercial-core/"],
    brief: briefFor({
      name: "2300 Shattuck Ave",
      fitLine: "office users comparing south Shattuck corridor depth with the core BART-area buildings",
      roleLower: "the south Shattuck office-scale pattern",
      secondaryContext: "South Shattuck office corridor and scale comparison",
      accessContext: "South Shattuck Avenue, Downtown Berkeley services, and UC Berkeley adjacency",
      evidenceRole: "South Shattuck office scale benchmark",
      bestFitPrimary: "Professional-service firms, office users, and education-adjacent organizations that want Downtown Berkeley identity while comparing the broader Shattuck corridor.",
      locationContext: "how Downtown Berkeley office evidence extends south of the immediate BART core",
      representativeValue: "south Shattuck office-scale benchmark",
      sourceContext: "larger Shattuck corridor office and professional-service users",
      advantages: [
        "Broadens Downtown Berkeley beyond the immediate BART core.",
        "Adds south Shattuck corridor evidence for office users.",
        "Helps users decide whether Downtown Berkeley has enough practical office depth for the search.",
      ],
      nearbyAlternatives: [
        { label: "2150 Shattuck Ave", url: buildingPath("2150 Shattuck Ave"), reason: "Compare when central Shattuck BART-oriented office identity matters more." },
        { label: "2168 Shattuck Ave", url: buildingPath("2168 Shattuck Ave"), reason: "Compare another central Shattuck professional-office benchmark when the search remains focused on the BART-oriented core." },
        { label: "Emeryville Commercial Core", url: "/commercial-real-estate/CA/emeryville/emeryville-commercial-core/", reason: "Compare when campus-style office scale and parking matter more than Downtown Berkeley walkability." },
      ],
      ecosystemSubtypes: ["professional_office", "downtown_office", "transit_oriented_office"],
      representativeRole: "south_shattuck_office_scale_benchmark",
      businessActivities: ["professional_services", "client_meetings", "education_support", "regional_office"],
      businessArchetypes: ["professional_services_firm", "regional_office", "consulting_firm", "education_support_organization"],
      operationalCharacteristics: ["corridor_depth", "walkable_services", "university_adjacency", "parking_validation_required"],
    }),
  }),
];

module.exports = {
  canonicalBuildings: records,
};
