module.exports = {
  "CA/san-francisco": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$65–$85/SF/YR",
    average_rent_label: "Typical office asking rent",
    average_rent_direction: "down",
    availability_rate: "Elevated supply",
    availability_label: "Tenant-favorable availability",
    availability_direction: "up",
    market_trend: "Tenant-favorable market",
    market_trend_label: "More options and negotiating flexibility",
    market_trend_direction: "flat",
    notable_areas: ["Financial District", "SoMa", "Mission Bay", "Jackson Square"],
    notable_areas_label: "Common tenant search areas",
    summary: "San Francisco remains one of the Bay Area's most important office, retail, and innovation markets. Tenants often compare downtown, SoMa, Mission Bay, and nearby East Bay markets when evaluating pricing, commute access, and building quality.",
    rent_note: "Office rents vary significantly by building class, neighborhood, size, and lease structure.",
    availability_note: "Availability remains elevated compared with pre-2020 levels, giving tenants more negotiating room in many submarkets.",
    tenant_takeaway: "Tenants should compare neighborhoods carefully and pay close attention to total occupancy cost, concession packages, commute patterns, and building quality."
  },

  "NY/new-york": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$75–$90/SF/YR",
    average_rent_direction: "up",
    average_rent_label: "Typical Manhattan asking rent",
    availability_rate: "Tightening supply",
    availability_direction: "down",
    availability_label: "Improving availability in prime areas",
    market_trend: "Selective landlord-favorable market",
    market_trend_direction: "up",
    market_trend_label: "Strong demand for high-quality space",
    notable_areas: ["Midtown", "Flatiron", "SoHo", "Financial District"],
    notable_areas_label: "Common tenant search areas",
    summary: "New York remains one of the strongest and most competitive office markets in the country. Tenants often compare Midtown, Flatiron, SoHo, and Downtown depending on budget, commute access, brand, and building quality.",
    rent_note: "Office rents vary widely by neighborhood, building class, floor height, and lease structure.",
    availability_note: "Prime buildings have tightened more quickly than commodity office space, so availability can feel very different by submarket.",
    tenant_takeaway: "Tenants should compare building quality, concessions, commute access, and long-term flexibility before choosing a location."
  },

  "CA/los-angeles": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$48–$65/SF/YR",
    average_rent_direction: "flat",
    average_rent_label: "Typical office asking rent",
    availability_rate: "Elevated supply",
    availability_direction: "up",
    availability_label: "More options across many submarkets",
    market_trend: "Tenant-favorable market",
    market_trend_direction: "flat",
    market_trend_label: "Good options but highly submarket-specific",
    notable_areas: ["Downtown LA", "West LA", "Hollywood", "Culver City"],
    notable_areas_label: "Common tenant search areas",
    summary: "Los Angeles is a broad, highly segmented office market where pricing and availability vary significantly by submarket. Tenants often compare Downtown, West LA, Hollywood, and Culver City based on commute patterns, customer access, and brand fit.",
    rent_note: "Office rents are often quoted monthly in Los Angeles and can vary substantially between Downtown, Westside, and entertainment-focused submarkets.",
    availability_note: "Availability remains elevated in many parts of the market, giving tenants room to compare options and negotiate terms.",
    tenant_takeaway: "Tenants should focus on commute patterns, parking, building quality, and the specific submarket that best supports their team or customer base."
  },

  "IL/chicago": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$40–$50/SF/YR",
    average_rent_direction: "flat",
    average_rent_label: "Typical downtown asking rent",
    availability_rate: "Elevated supply",
    availability_direction: "flat",
    availability_label: "Tenant choice remains broad",
    market_trend: "Stabilizing market",
    market_trend_direction: "flat",
    market_trend_label: "Concessions remain important",
    notable_areas: ["The Loop", "River North", "West Loop", "Fulton Market"],
    notable_areas_label: "Common tenant search areas",
    summary: "Chicago remains a major office market with strong transit access and a deep inventory of downtown buildings. Tenants often compare The Loop, River North, West Loop, and Fulton Market based on image, amenities, access, and cost.",
    rent_note: "Asking rents can remain stable even when landlords compete through concessions, improvement allowances, and flexible deal terms.",
    availability_note: "Availability remains elevated, but better-located and amenity-rich buildings can perform differently from older commodity space.",
    tenant_takeaway: "Tenants should compare effective rent, concessions, transit access, and building quality rather than focusing only on headline asking rent."
  },

  "FL/miami": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$60–$72/SF/YR",
    average_rent_direction: "up",
    average_rent_label: "Typical office asking rent",
    availability_rate: "Balanced supply",
    availability_direction: "down",
    availability_label: "Stronger demand than many peer markets",
    market_trend: "Landlord-favorable market",
    market_trend_direction: "up",
    market_trend_label: "Premium space remains competitive",
    notable_areas: ["Brickell", "Downtown Miami", "Wynwood", "Coral Gables"],
    notable_areas_label: "Common tenant search areas",
    summary: "Miami continues to attract office demand from finance, professional services, technology, and firms seeking a South Florida presence. Tenants often compare Brickell, Downtown, Wynwood, and Coral Gables based on image, access, and client proximity.",
    rent_note: "Premium Miami office space can command materially higher rents, especially in top buildings and core submarkets.",
    availability_note: "Availability is generally more balanced than in many large U.S. office markets, especially for high-quality space.",
    tenant_takeaway: "Tenants should move carefully but be prepared to act quickly on well-located, high-quality options."
  },

  "TX/austin": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$40–$55/SF/YR",
    average_rent_direction: "down",
    average_rent_label: "Typical office asking rent",
    availability_rate: "Elevated supply",
    availability_direction: "up",
    availability_label: "More choices after recent growth cycle",
    market_trend: "Tenant-favorable market",
    market_trend_direction: "flat",
    market_trend_label: "More options and negotiating flexibility",
    notable_areas: ["Downtown", "The Domain", "East Austin", "South Congress"],
    notable_areas_label: "Common tenant search areas",
    summary: "Austin remains a major growth market, but recent office supply and changing workplace patterns have created more options for tenants. Companies often compare Downtown, The Domain, East Austin, and South Congress based on talent access, amenities, and budget.",
    rent_note: "Office rents vary widely between central Austin, newer amenity-rich projects, and more value-oriented submarkets.",
    availability_note: "Elevated availability can create opportunities for tenants seeking better locations, improved terms, or upgraded space.",
    tenant_takeaway: "Tenants should compare total occupancy cost, parking, commute patterns, and flexibility before committing."
  },

  "CO/denver": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$38–$45/SF/YR",
    average_rent_direction: "flat",
    average_rent_label: "Typical office asking rent",
    availability_rate: "Elevated supply",
    availability_direction: "flat",
    availability_label: "Tenant choice remains broad",
    market_trend: "Stabilizing market",
    market_trend_direction: "flat",
    market_trend_label: "Gradual recovery with selective demand",
    notable_areas: ["Downtown Denver", "LoDo", "Cherry Creek", "Denver Tech Center"],
    notable_areas_label: "Common tenant search areas",
    summary: "Denver offers a mix of downtown, neighborhood, and suburban office options. Tenants often compare Downtown, LoDo, Cherry Creek, and the Denver Tech Center based on commute access, amenities, parking, and total cost.",
    rent_note: "Asking rents can vary significantly between downtown towers, boutique neighborhood space, and suburban office buildings.",
    availability_note: "Availability remains elevated in many parts of the market, though demand is more selective for well-located and upgraded buildings.",
    tenant_takeaway: "Tenants should compare central and suburban options carefully, especially around parking, commute patterns, and concession packages."
  },

  "WA/seattle": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$45–$55/SF/YR",
    average_rent_direction: "flat",
    average_rent_label: "Typical office asking rent",
    availability_rate: "Elevated supply",
    availability_direction: "up",
    availability_label: "Large-block availability remains meaningful",
    market_trend: "Tenant-favorable market",
    market_trend_direction: "flat",
    market_trend_label: "More options in core office submarkets",
    notable_areas: ["Downtown Seattle", "South Lake Union", "Capitol Hill", "Belltown"],
    notable_areas_label: "Common tenant search areas",
    summary: "Seattle remains a major technology and business market, but office availability is elevated in several core areas. Tenants often compare Downtown, South Lake Union, Capitol Hill, and nearby Eastside alternatives based on workforce access and building quality.",
    rent_note: "Asking rents remain supported by newer and higher-quality buildings, even as availability is elevated in parts of the market.",
    availability_note: "Tenants may find more negotiating flexibility, especially in larger blocks or older buildings.",
    tenant_takeaway: "Tenants should compare Seattle options against Bellevue and other Eastside markets when evaluating access, cost, and employee preferences."
  },

  "TX/dallas": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$28–$36/SF/YR",
    average_rent_direction: "up",
    average_rent_label: "Typical office asking rent",
    availability_rate: "Elevated but improving supply",
    availability_direction: "down",
    availability_label: "Prime buildings performing better",
    market_trend: "Mixed but improving market",
    market_trend_direction: "up",
    market_trend_label: "Stronger demand for quality space",
    notable_areas: ["Uptown", "Downtown Dallas", "Turtle Creek", "Las Colinas"],
    notable_areas_label: "Common tenant search areas",
    summary: "Dallas offers a broad office market with many options across urban and suburban submarkets. Tenants often compare Uptown, Downtown, Turtle Creek, and Las Colinas based on commute access, parking, amenities, and value.",
    rent_note: "Asking rents vary significantly between Class A, suburban, and value-oriented buildings.",
    availability_note: "Overall availability remains elevated, but higher-quality buildings have shown stronger leasing activity.",
    tenant_takeaway: "Tenants should compare building quality, parking, concessions, and commute patterns across both Dallas and broader DFW options."
  },

  "CA/oakland": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$40–$48/SF/YR",
    average_rent_direction: "flat",
    average_rent_label: "Typical office asking rent",
    availability_rate: "Elevated supply",
    availability_direction: "flat",
    availability_label: "Tenant options remain available",
    market_trend: "Tenant-favorable market",
    market_trend_direction: "flat",
    market_trend_label: "Value alternative to San Francisco",
    notable_areas: ["Downtown Oakland", "Uptown", "Jack London Square", "Temescal"],
    notable_areas_label: "Common tenant search areas",
    summary: "Oakland can be an attractive alternative for tenants comparing Bay Area access, transit, and relative value. Tenants often compare Downtown Oakland, Uptown, Jack London Square, and nearby East Bay markets against San Francisco options.",
    rent_note: "Office rents are generally lower than San Francisco but vary by building quality, transit access, and neighborhood.",
    availability_note: "Availability remains elevated enough to give tenants options, especially when comparing Oakland with nearby East Bay and San Francisco markets.",
    tenant_takeaway: "Tenants should compare Oakland on access, employee commute patterns, parking, and overall value relative to San Francisco."
  },

  "CA/san-jose": {
    snapshot_title: "Office Market Snapshot",
    average_rent: "$58–$68/SF/YR",
    average_rent_direction: "up",
    average_rent_label: "Typical Silicon Valley asking rent",
    availability_rate: "Balanced to elevated supply",
    availability_direction: "down",
    availability_label: "Improving demand in quality buildings",
    market_trend: "Selective growth market",
    market_trend_direction: "up",
    market_trend_label: "Tech and AI demand supporting activity",
    notable_areas: ["Downtown San Jose", "North San Jose", "Santana Row", "South San Jose"],
    notable_areas_label: "Common tenant search areas",
    summary: "San Jose sits within the broader Silicon Valley office market, where technology, AI, and innovation tenants continue to shape demand. Tenants often compare Downtown San Jose, North San Jose, Santana Row, and nearby Silicon Valley markets based on talent access, commute patterns, and building quality.",
    rent_note: "Office rents vary widely across Silicon Valley depending on building quality, location, and proximity to major technology employers.",
    availability_note: "Availability is more balanced than in some large coastal markets, with better-quality buildings seeing stronger tenant interest.",
    tenant_takeaway: "Tenants should compare San Jose with nearby Silicon Valley submarkets and pay close attention to commute patterns, parking, and long-term flexibility."
  }
};
