module.exports = Object.freeze({
  schemaVersion: "recommendation-activation-registry:v1",
  flows: Object.freeze({
    "san-diego:industrial_flex:bounded": Object.freeze({
      activationKey: "san-diego:industrial_flex:bounded",
      marketId: "san-diego",
      propertyType: "industrial_flex",
      propertyTypeAliases: Object.freeze(["industrial-flex", "industrial_flex"]),
      cohort: "bounded",
      certificationId: "san-diego-industrial-flex-v1",
      certificationStatus: "certified_for_bounded_real_user_cohort",
      activationEligible: true,
      entryContextIds: Object.freeze(["miramar", "otay-mesa", "kearny-mesa", "sorrento-mesa", "sorrento-valley"]),
    }),
    "north-orange-county:industrial_flex:bounded": Object.freeze({
      activationKey: "north-orange-county:industrial_flex:bounded",
      marketId: "north-orange-county",
      propertyType: "industrial_flex",
      propertyTypeAliases: Object.freeze(["industrial-flex", "industrial_flex"]),
      cohort: "bounded",
      certificationId: "north-orange-county-industrial-flex-v1",
      certificationStatus: "certified_for_bounded_real_user_cohort",
      activationEligible: true,
      entryMarketIds: Object.freeze(["anaheim", "fullerton"]),
      entryContextIds: Object.freeze(["anaheim-canyon", "fullerton-industrial-service-area"]),
    }),
    "phoenix:industrial_flex:bounded": Object.freeze({
      activationKey: "phoenix:industrial_flex:bounded",
      marketId: "phoenix",
      propertyType: "industrial_flex",
      propertyTypeAliases: Object.freeze(["industrial-flex", "industrial_flex"]),
      cohort: "bounded",
      certificationId: "phoenix-industrial-flex-v1",
      certificationStatus: "certified_for_bounded_real_user_cohort",
      activationEligible: true,
      entryMarketIds: Object.freeze(["phoenix"]),
      entryContextIds: Object.freeze(["southwest-phoenix-industrial", "airport-south-central-industrial", "phoenix-airport-sky-harbor-area", "north-phoenix-advanced-operations", "deer-valley", "north-phoenix-tsmc-corridor"]),
    }),
    "indianapolis:industrial_flex:bounded": Object.freeze({
      activationKey: "indianapolis:industrial_flex:bounded",
      marketId: "indianapolis",
      propertyType: "industrial_flex",
      propertyTypeAliases: Object.freeze(["industrial-flex", "industrial_flex"]),
      cohort: "bounded",
      certificationId: "indianapolis-industrial-flex-v1",
      certificationStatus: "certified_for_bounded_real_user_cohort",
      activationEligible: true,
      entryMarketIds: Object.freeze(["indianapolis"]),
      entryContextIds: Object.freeze(["indianapolis-airport-logistics", "park-fletcher", "stout-field", "park-100-northwest-indianapolis", "park-100"]),
    }),
  }),
});
