module.exports = {
  "san-francisco": {
    metro: "San Francisco",
    qaStatus: "completed",
    lastQaDate: "2026-07-26",
    validationStatus: "compass_ready_editorial_developing",
    scenarioCount: 8,
    reportPath: "/docs/recommendation-qa/san-francisco-pilot/",
    notes: "San Francisco pilot scenarios produce differentiated, graph-backed market paths across core San Francisco office, life-science/growth, creative office, boutique executive office, Palo Alto executive/startup, Redwood City Peninsula midpoint office, North Bayshore technology campus, and Moffett Park R&D profiles. Remaining node-level explainability refinements should continue as editorial maturity work, not a Compass QA blocker.",
  },
  sacramento: {
    metro: "Sacramento",
    qaStatus: "completed",
    lastQaDate: "2026-07-09",
    validationStatus: "pilot_passed",
    scenarioCount: 7,
    reportPath: "/docs/recommendation-qa/sacramento-pilot/",
    notes: "Sacramento pilot scenarios produce differentiated, graph-backed market paths for office, medical, flex, warehouse, and retail/service profiles.",
  },
  "san-diego": {
    metro: "San Diego",
    qaStatus: "completed",
    lastQaDate: "2026-07-09",
    validationStatus: "legacy_compass_calibration_complete_level3_default_off",
    scenarioCount: 10,
    reportPath: "/docs/recommendation-qa/san-diego-pilot/",
    notes: "Legacy Compass scenarios remain useful calibration evidence but do not certify current controlled Level 3 behavior. Only the bounded City of San Diego Industrial/Flex foundation may enter current Recommendation Intelligence, and its independent production flag defaults off; Office, Retail, and regional paths remain non-certified.",
  },
  "orange-county": {
    metro: "Orange County",
    qaStatus: "completed",
    lastQaDate: "2026-07-10",
    validationStatus: "compass_ready_editorial_developing",
    scenarioCount: 12,
    reportPath: "/docs/recommendation-qa/orange-county-pilot/",
    notes: "Orange County pilot scenarios produce differentiated, graph-backed market paths across office, R&D, airport-access professional office, medical, executive office, warehouse/flex, contractor/service industrial, and South OC profiles. Under the Compass operating model, QA and Location Brief quality support Compass Ready status while representative-building enrichment continues as an editorial workstream.",
  },
  denver: {
    metro: "Denver",
    qaStatus: "completed",
    lastQaDate: "2026-07-14",
    validationStatus: "compass_ready_editorial_developing",
    scenarioCount: 12,
    reportPath: "/docs/recommendation-qa/denver-pilot/",
    notes: "Denver pilot scenarios produce differentiated, graph-backed market paths across central office, creative office, client-facing executive office, southeast suburban office, Boulder/US-36 technology, industrial/logistics, medical, west metro professional-service, and flex/R&D support profiles. Representative-building depth remains an editorial enhancement workstream, not a readiness blocker.",
  },
  seattle: {
    metro: "Seattle",
    qaStatus: "completed",
    lastQaDate: "2026-07-26",
    validationStatus: "compass_ready_editorial_developing",
    scenarioCount: 9,
    reportPath: "/docs/recommendation-qa/seattle-pilot/",
    notes: "Seattle pilot scenarios produce differentiated, graph-backed district-level paths across downtown office, historic executive office, creative waterfront office, Bellevue professional office, Eastside technology office, SODO urban warehouse, Georgetown contractor/service industrial, Ballard/Interbay flex, and Kent Valley distribution profiles. Broad city-level Seattle discovery remains a Compass enhancement because a canonical Seattle city starter node is not yet present.",
  },
};
