module.exports = {
  sacramento: {
    metro: "Sacramento",
    qaStatus: "completed",
    lastQaDate: "2026-07-09",
    validationStatus: "pilot_passed",
    scenarioCount: 7,
    reportPath: "/docs/recommendation-qa/sacramento-pilot/",
    notes: "Sacramento pilot scenarios produce differentiated, graph-backed market paths for office, medical, flex, warehouse, and retail/service profiles.",
  },
  "san-diego": {
    metro: "San Diego",
    qaStatus: "completed",
    lastQaDate: "2026-07-09",
    validationStatus: "compass_ready",
    scenarioCount: 10,
    reportPath: "/docs/recommendation-qa/san-diego-pilot/",
    notes: "San Diego pilot scenarios produce differentiated, graph-backed market paths across office, medical, life science/R&D, showroom/flex, warehouse, manufacturing, and North County profiles. Editorial broker-style review passed after calibration; representative-building depth remains an enhancement priority, not a readiness blocker.",
  },
  "orange-county": {
    metro: "Orange County",
    qaStatus: "completed",
    lastQaDate: "2026-07-10",
    validationStatus: "compass_ready_editorial_developing",
    scenarioCount: 12,
    reportPath: "/docs/recommendation-qa/orange-county-pilot/",
    notes: "Orange County pilot scenarios produce differentiated, graph-backed market paths across office, R&D, airport-access professional office, medical, executive office, warehouse/flex, contractor/service industrial, and South OC profiles. Under the Compass operating model, QA and Location Brief quality support Compass Ready status while representative-building enrichment continues as an editorial workstream.",
  },
  denver: {
    metro: "Denver",
    qaStatus: "completed",
    lastQaDate: "2026-07-14",
    validationStatus: "compass_ready_editorial_developing",
    scenarioCount: 12,
    reportPath: "/docs/recommendation-qa/denver-pilot/",
    notes: "Denver pilot scenarios produce differentiated, graph-backed market paths across central office, creative office, client-facing executive office, southeast suburban office, Boulder/US-36 technology, industrial/logistics, medical, west metro professional-service, and flex/R&D support profiles. Representative-building depth remains an editorial enhancement workstream, not a readiness blocker.",
  },
  seattle: {
    metro: "Seattle",
    qaStatus: "completed",
    lastQaDate: "2026-07-26",
    validationStatus: "compass_ready_editorial_developing",
    scenarioCount: 9,
    reportPath: "/docs/recommendation-qa/seattle-pilot/",
    notes: "Seattle pilot scenarios produce differentiated, graph-backed district-level paths across downtown office, historic executive office, creative waterfront office, Bellevue professional office, Eastside technology office, SODO urban warehouse, Georgetown contractor/service industrial, Ballard/Interbay flex, and Kent Valley distribution profiles. Broad city-level Seattle discovery remains a Compass enhancement because a canonical Seattle city starter node is not yet present.",
  },
};
