const operationalCharacteristicCategories = [
  ["access_loading", "Access and Loading"],
  ["parking_vehicles", "Parking and Vehicles"],
  ["configuration", "Space Configuration"],
  ["infrastructure", "Infrastructure"],
  ["market_presence", "Customer and Market Presence"],
  ["location_workforce", "Location and Workforce"],
  ["outdoor_special_use", "Outdoor and Special Use"],
].map(([id, label]) => ({ id, label }));

function characteristic({ id, label, category, description, ecosystems, subtypes = [], activities = [], archetypes = [], observable = true, requiresValidation = true, cautions = [] }) {
  return {
    id,
    label,
    category,
    description,
    applicableEcosystems: ecosystems,
    applicableSubtypes: subtypes,
    relatedActivities: activities,
    relatedBusinessArchetypes: archetypes,
    commonlyObservable: Boolean(observable),
    requiresValidation: Boolean(requiresValidation),
    cautions,
  };
}

const operationalCharacteristics = [
  characteristic({ id: "grade_level_loading", label: "Grade-Level Loading", category: "access_loading", description: "Direct ground-level loading suitable for vans, service vehicles, and smaller commercial deliveries.", ecosystems: ["industrial_flex"], subtypes: ["small_bay_industrial", "flex", "contractor_service", "light_manufacturing"], activities: ["receiving", "shipping", "service_dispatch", "equipment_storage"], archetypes: ["electrician", "hvac_company", "plumbing_company", "building_services_company"] }),
  characteristic({ id: "dock_high_loading", label: "Dock-High Loading", category: "access_loading", description: "Raised loading access for larger freight movement and warehouse or distribution operations.", ecosystems: ["industrial_flex"], subtypes: ["warehouse", "distribution", "last_mile_logistics"], activities: ["receiving", "shipping", "distribution"], archetypes: ["distributor", "wholesaler", "ecommerce_fulfillment_business"] }),
  characteristic({ id: "drive_in_access", label: "Drive-In Access", category: "access_loading", description: "Vehicle-accessible building entry for service vehicles, equipment, or lower-intensity operations.", ecosystems: ["industrial_flex", "special_purpose"], subtypes: ["small_bay_industrial", "flex", "contractor_service", "automotive"], activities: ["service_dispatch", "vehicle_storage", "equipment_storage"], archetypes: ["general_contractor", "auto_repair_business", "equipment_service_company"] }),
  characteristic({ id: "rear_loading", label: "Rear Loading", category: "access_loading", description: "Back-of-building loading that separates deliveries from customer or office arrival.", ecosystems: ["industrial_flex", "retail"], subtypes: ["showroom_flex", "service_retail", "warehouse"], activities: ["receiving", "shipping", "customer_showroom"], archetypes: ["wholesaler", "cabinet_shop"] }),
  characteristic({ id: "shared_loading", label: "Shared Loading", category: "access_loading", description: "Loading facilities shared across tenants or building areas, requiring tenant-level validation.", ecosystems: ["industrial_flex", "office", "retail"], subtypes: ["creative_office", "showroom_flex", "downtown_retail"], activities: ["receiving", "shipping", "food_preparation"], archetypes: ["creative_studio", "food_producer"], cautions: ["Shared access can limit delivery windows or vehicle staging."] }),
  characteristic({ id: "truck_court", label: "Truck Court", category: "access_loading", description: "Dedicated truck maneuvering area supporting larger delivery and distribution operations.", ecosystems: ["industrial_flex"], subtypes: ["warehouse", "distribution", "last_mile_logistics"], activities: ["receiving", "shipping", "distribution"], archetypes: ["distributor", "importer"] }),
  characteristic({ id: "heavy_truck_access", label: "Heavy Truck Access", category: "access_loading", description: "Access pattern appropriate for larger trucks, freight frequency, or heavier goods movement.", ecosystems: ["industrial_flex"], subtypes: ["distribution", "warehouse", "manufacturing"], activities: ["shipping", "receiving", "distribution"], archetypes: ["distributor", "light_manufacturer"] }),
  characteristic({ id: "last_mile_access", label: "Last-Mile Access", category: "access_loading", description: "Location and site pattern supporting local delivery reach and frequent vehicle movement.", ecosystems: ["industrial_flex"], subtypes: ["last_mile_logistics", "distribution"], activities: ["distribution", "shipping", "service_dispatch"], archetypes: ["ecommerce_fulfillment_business", "building_services_company"] }),
  characteristic({ id: "delivery_access", label: "Delivery Access", category: "access_loading", description: "Practical access for routine inbound or outbound deliveries.", ecosystems: ["industrial_flex", "retail", "hospitality"], subtypes: ["warehouse", "service_retail", "food_beverage"], activities: ["receiving", "shipping", "food_preparation"], archetypes: ["food_producer", "wholesaler"] }),
  characteristic({ id: "freight_elevator", label: "Freight Elevator", category: "access_loading", description: "Elevator infrastructure that may support deliveries, equipment, or production-adjacent users in multi-story buildings.", ecosystems: ["office", "industrial_flex", "retail"], subtypes: ["creative_office", "showroom_flex", "downtown_retail"], activities: ["receiving", "equipment_storage", "customer_showroom"], archetypes: ["creative_studio", "furniture_maker"] }),
  characteristic({ id: "loading_constrained", label: "Loading Constrained", category: "access_loading", description: "A representative environment where loading is a known validation topic rather than an assumed strength.", ecosystems: ["office", "retail", "medical", "industrial_flex"], subtypes: ["downtown_office", "neighborhood_retail", "medical_office", "small_bay_industrial", "flex"], activities: ["client_meetings", "walk_in_retail", "healthcare_delivery"], archetypes: ["law_firm", "medical_practice"], requiresValidation: true }),

  characteristic({ id: "employee_parking", label: "Employee Parking", category: "parking_vehicles", description: "Parking pattern relevant to employee commute reliability.", ecosystems: ["office", "medical", "industrial_flex"], subtypes: ["suburban_office", "medical_office", "flex"], activities: ["knowledge_work", "healthcare_delivery", "service_dispatch"], archetypes: ["professional_office", "medical_practice", "hvac_company"] }),
  characteristic({ id: "customer_parking", label: "Customer Parking", category: "parking_vehicles", description: "Parking supporting customer, patient, client, or visitor access.", ecosystems: ["retail", "medical", "office", "industrial_flex", "special_purpose"], subtypes: ["service_retail", "medical_office", "professional_office", "showroom_flex", "education", "automotive"], activities: ["walk_in_service", "healthcare_delivery", "client_meetings"], archetypes: ["dental_practice", "wellness_practice", "accounting_firm"] }),
  characteristic({ id: "service_vehicle_parking", label: "Service-Vehicle Parking", category: "parking_vehicles", description: "Parking or staging relevant to technicians, service vehicles, and field crews.", ecosystems: ["industrial_flex"], subtypes: ["contractor_service", "small_bay_industrial", "contractor_yard"], activities: ["service_dispatch", "vehicle_storage"], archetypes: ["electrician", "plumbing_company", "building_services_company"] }),
  characteristic({ id: "fleet_parking", label: "Fleet Parking", category: "parking_vehicles", description: "Parking pattern for multiple operating vehicles or delivery routes.", ecosystems: ["industrial_flex"], subtypes: ["contractor_yard", "last_mile_logistics", "distribution"], activities: ["vehicle_storage", "distribution", "service_dispatch"], archetypes: ["landscaper", "ecommerce_fulfillment_business"] }),
  characteristic({ id: "secured_vehicle_parking", label: "Secured Vehicle Parking", category: "parking_vehicles", description: "Controlled parking for vehicles, equipment, or sensitive operations.", ecosystems: ["industrial_flex", "special_purpose"], subtypes: ["contractor_yard", "automotive"], activities: ["vehicle_storage", "equipment_storage"], archetypes: ["general_contractor", "auto_repair_business"] }),
  characteristic({ id: "structured_parking", label: "Structured Parking", category: "parking_vehicles", description: "Garage or structured parking relevant to dense office, medical, or retail environments.", ecosystems: ["office", "medical", "retail"], subtypes: ["downtown_office", "medical_office", "shopping_center"], activities: ["client_meetings", "healthcare_delivery", "walk_in_service"], archetypes: ["financial_services_firm", "medical_practice"] }),
  characteristic({ id: "surface_parking", label: "Surface Parking", category: "parking_vehicles", description: "Surface parking field supporting auto-oriented access.", ecosystems: ["office", "medical", "industrial_flex", "retail"], subtypes: ["suburban_office", "medical_office", "flex", "shopping_center"], activities: ["knowledge_work", "healthcare_delivery", "service_dispatch"], archetypes: ["medical_practice", "professional_office"] }),
  characteristic({ id: "limited_parking", label: "Limited Parking", category: "parking_vehicles", description: "Parking is a likely constraint and must be validated for employees, customers, or vehicles.", ecosystems: ["office", "retail", "medical"], subtypes: ["downtown_office", "neighborhood_retail", "medical_office"], activities: ["client_meetings", "walk_in_service", "healthcare_delivery"], archetypes: ["law_firm", "wellness_practice"] }),
  characteristic({ id: "outdoor_vehicle_storage", label: "Outdoor Vehicle Storage", category: "parking_vehicles", description: "Outdoor vehicle storage or staging relevant to operations-heavy businesses.", ecosystems: ["industrial_flex", "special_purpose"], subtypes: ["contractor_yard", "automotive"], activities: ["vehicle_storage", "equipment_storage"], archetypes: ["landscaper", "equipment_service_company"] }),

  characteristic({ id: "small_suite_sizes", label: "Small Suite Sizes", category: "configuration", description: "Smaller divisible spaces that can fit local businesses, trades, or boutique office users.", ecosystems: ["industrial_flex", "office", "retail"], subtypes: ["small_bay_industrial", "professional_office", "neighborhood_retail"], activities: ["service_dispatch", "knowledge_work", "walk_in_service"], archetypes: ["electrician", "nonprofit_office", "wellness_practice"], observable: true, requiresValidation: false }),
  characteristic({ id: "large_floorplates", label: "Large Floorplates", category: "configuration", description: "Large contiguous floor layouts that help explain headquarters, institutional, or scaled operations decisions.", ecosystems: ["office", "industrial_flex", "life_science"], subtypes: ["downtown_office", "office_campus", "warehouse", "innovation_campus"], activities: ["collaboration", "distribution", "research"], archetypes: ["startup", "distributor", "biotech_company"], observable: true, requiresValidation: true }),
  characteristic({ id: "flexible_suite_sizes", label: "Flexible Suite Sizes", category: "configuration", description: "A range of suite sizes or divisibility that may support staged growth or mixed business needs.", ecosystems: ["office", "industrial_flex"], subtypes: ["professional_office", "flex", "creative_office"], activities: ["knowledge_work", "product_development", "storage"], archetypes: ["startup", "creative_studio"] }),
  characteristic({ id: "high_office_percentage", label: "High Office Percentage", category: "configuration", description: "Flex or industrial environments with a substantial office component.", ecosystems: ["industrial_flex"], subtypes: ["flex", "research_development", "showroom_flex"], activities: ["knowledge_work", "product_development", "customer_showroom"], archetypes: ["research_company", "wholesaler"] }),
  characteristic({ id: "low_office_percentage", label: "Low Office Percentage", category: "configuration", description: "Operations-forward industrial environments with limited office buildout.", ecosystems: ["industrial_flex"], subtypes: ["warehouse", "contractor_service", "distribution"], activities: ["storage", "shipping", "service_dispatch"], archetypes: ["distributor", "plumbing_company"] }),
  characteristic({ id: "office_showroom_mix", label: "Office/Showroom Mix", category: "configuration", description: "A hybrid environment that combines workspace, presentation, and product display.", ecosystems: ["industrial_flex", "retail"], subtypes: ["showroom_flex", "showroom_retail"], activities: ["customer_showroom", "client_meetings", "inventory_management"], archetypes: ["cabinet_shop", "furniture_maker", "wholesaler"] }),
  characteristic({ id: "office_warehouse_mix", label: "Office/Warehouse Mix", category: "configuration", description: "A hybrid environment supporting office, storage, service, receiving, or light operations.", ecosystems: ["industrial_flex"], subtypes: ["small_bay_industrial", "flex", "contractor_service"], activities: ["administrative_operations", "storage", "service_dispatch", "receiving"], archetypes: ["general_contractor", "electrician", "equipment_service_company"] }),
  characteristic({ id: "open_workspace", label: "Open Workspace", category: "configuration", description: "Workspace pattern suited to collaboration, creative work, or team-based office planning.", ecosystems: ["office"], subtypes: ["creative_office", "downtown_office", "coworking"], activities: ["collaboration", "knowledge_work"], archetypes: ["startup", "marketing_agency"] }),
  characteristic({ id: "private_office_layout", label: "Private Office Layout", category: "configuration", description: "Office layouts where enclosed offices, client rooms, or confidentiality can matter.", ecosystems: ["office", "medical"], subtypes: ["professional_office", "executive_office", "medical_office"], activities: ["client_meetings", "healthcare_delivery"], archetypes: ["law_firm", "medical_practice"] }),
  characteristic({ id: "high_clearance", label: "High Clearance", category: "configuration", description: "Warehouse clearance relevant to storage density, racking, distribution, or manufacturing validation.", ecosystems: ["industrial_flex"], subtypes: ["warehouse", "distribution", "manufacturing"], activities: ["storage", "distribution", "manufacturing"], archetypes: ["distributor", "light_manufacturer"] }),
  characteristic({ id: "moderate_clearance", label: "Moderate Clearance", category: "configuration", description: "Operational clearance more typical of flex, light manufacturing, or small-bay inventory.", ecosystems: ["industrial_flex"], subtypes: ["flex", "small_bay_industrial", "light_manufacturing"], activities: ["storage", "assembly", "service_dispatch"], archetypes: ["cabinet_shop", "equipment_service_company"] }),
  characteristic({ id: "ground_floor_access", label: "Ground-Floor Access", category: "configuration", description: "Ground-floor entry that can matter for customers, deliveries, patients, or service users.", ecosystems: ["retail", "medical", "industrial_flex"], subtypes: ["neighborhood_retail", "medical_office", "small_bay_industrial"], activities: ["walk_in_service", "healthcare_delivery", "receiving"], archetypes: ["wellness_practice", "electrician"] }),
  characteristic({ id: "multi_tenant", label: "Multi-Tenant", category: "configuration", description: "A multi-tenant environment useful for understanding smaller occupiers and shared building systems.", ecosystems: ["office", "industrial_flex", "retail"], subtypes: ["professional_office", "small_bay_industrial", "shopping_center"], activities: ["knowledge_work", "service_dispatch", "walk_in_service"], archetypes: ["professional_office", "electrician"], observable: true, requiresValidation: false }),
  characteristic({ id: "single_tenant", label: "Single-Tenant", category: "configuration", description: "A building or environment oriented to one primary occupier or campus-style control.", ecosystems: ["office", "industrial_flex", "life_science"], subtypes: ["office_campus", "warehouse", "innovation_campus"], activities: ["collaboration", "distribution", "research"], archetypes: ["startup", "biotech_company"] }),
  characteristic({ id: "divisible_space", label: "Divisible Space", category: "configuration", description: "Floor or suite pattern where subdividing space is a likely planning question.", ecosystems: ["office", "industrial_flex"], subtypes: ["downtown_office", "flex", "warehouse"], activities: ["knowledge_work", "storage"], archetypes: ["consulting_firm", "distributor"] }),

  characteristic({ id: "high_power", label: "High Power", category: "infrastructure", description: "Electrical capacity that may support technical, production, lab, or high-equipment users.", ecosystems: ["industrial_flex", "life_science"], subtypes: ["light_manufacturing", "research_development", "research_lab"], activities: ["product_development", "light_manufacturing", "research"], archetypes: ["research_company", "light_manufacturer"] }),
  characteristic({ id: "heavy_power", label: "Heavy Power", category: "infrastructure", description: "Higher-intensity power needs that usually require property-specific verification.", ecosystems: ["industrial_flex"], subtypes: ["manufacturing", "food_production"], activities: ["manufacturing", "food_production"], archetypes: ["food_producer", "light_manufacturer"] }),
  characteristic({ id: "specialized_ventilation", label: "Specialized Ventilation", category: "infrastructure", description: "Ventilation needs relevant to lab, production, food, or technical uses.", ecosystems: ["industrial_flex", "life_science", "retail", "hospitality"], subtypes: ["food_production", "wet_lab", "food_beverage"], activities: ["research", "food_production", "food_preparation"], archetypes: ["food_producer", "biotech_company"] }),
  characteristic({ id: "food_grade_infrastructure", label: "Food-Grade Infrastructure", category: "infrastructure", description: "Food-production infrastructure that must be verified before any operational assumption.", ecosystems: ["industrial_flex", "hospitality"], subtypes: ["food_production", "food_beverage"], activities: ["food_production", "food_preparation"], archetypes: ["food_producer"] }),
  characteristic({ id: "commercial_kitchen_potential", label: "Commercial Kitchen Potential", category: "infrastructure", description: "Potential food-preparation suitability that depends on zoning, utilities, ventilation, and buildout.", ecosystems: ["retail", "hospitality", "industrial_flex"], subtypes: ["food_beverage", "food_production", "neighborhood_retail"], activities: ["food_preparation", "food_production"], archetypes: ["food_producer"] }),
  characteristic({ id: "lab_infrastructure", label: "Lab Infrastructure", category: "infrastructure", description: "Existing or purpose-built lab infrastructure requiring explicit validation.", ecosystems: ["life_science"], subtypes: ["research_lab", "wet_lab", "biotech_research"], activities: ["research", "product_development"], archetypes: ["biotech_company", "research_company"] }),
  characteristic({ id: "wet_lab_potential", label: "Wet Lab Potential", category: "infrastructure", description: "Possible wet-lab suitability subject to systems, code, and landlord validation.", ecosystems: ["life_science"], subtypes: ["wet_lab", "biotech_research"], activities: ["research"], archetypes: ["biotech_company"] }),
  characteristic({ id: "plumbing_intensive", label: "Plumbing Intensive", category: "infrastructure", description: "Plumbing requirements for dental, medical, wellness, food, or production uses.", ecosystems: ["medical", "retail", "industrial_flex"], subtypes: ["dental", "wellness", "food_production"], activities: ["healthcare_delivery", "food_production"], archetypes: ["dental_practice", "food_producer"] }),
  characteristic({ id: "climate_controlled_storage", label: "Climate-Controlled Storage", category: "infrastructure", description: "Storage environment where temperature, humidity, or controlled conditions may matter.", ecosystems: ["industrial_flex", "special_purpose"], subtypes: ["warehouse", "food_production", "self_storage"], activities: ["storage", "inventory_management"], archetypes: ["food_producer", "distributor"] }),
  characteristic({ id: "enhanced_security", label: "Enhanced Security", category: "infrastructure", description: "Security or access-control considerations for sensitive operations, tenants, patients, or equipment.", ecosystems: ["office", "medical", "industrial_flex", "life_science", "special_purpose"], subtypes: ["executive_office", "medical_office", "warehouse", "research_lab", "education", "institutional"], activities: ["client_meetings", "healthcare_delivery", "storage", "research"], archetypes: ["financial_services_firm", "medical_practice", "research_company"] }),
  characteristic({ id: "fiber_connectivity", label: "Fiber Connectivity", category: "infrastructure", description: "Connectivity considerations for technology, professional, research, or operations-heavy users.", ecosystems: ["office", "industrial_flex", "life_science"], subtypes: ["downtown_office", "flex", "research_development"], activities: ["knowledge_work", "product_development", "research"], archetypes: ["startup", "research_company"] }),
  characteristic({ id: "backup_power", label: "Backup Power", category: "infrastructure", description: "Backup power or redundancy relevant to critical operations, medical, lab, or data-intensive uses.", ecosystems: ["medical", "life_science", "office"], subtypes: ["hospital_adjacent", "research_lab", "executive_office"], activities: ["healthcare_delivery", "research", "administrative_operations"], archetypes: ["outpatient_clinic", "biotech_company"] }),
  characteristic({ id: "crane_or_heavy_equipment_potential", label: "Crane or Heavy-Equipment Potential", category: "infrastructure", description: "Heavy-equipment compatibility that must be validated property by property.", ecosystems: ["industrial_flex"], subtypes: ["manufacturing"], activities: ["manufacturing", "assembly"], archetypes: ["light_manufacturer"] }),

  characteristic({ id: "showroom_frontage", label: "Showroom Frontage", category: "market_presence", description: "Frontage useful for display, appointment-driven product sales, or design/trade visibility.", ecosystems: ["industrial_flex", "retail"], subtypes: ["showroom_flex", "showroom_retail"], activities: ["customer_showroom"], archetypes: ["cabinet_shop", "furniture_maker"] }),
  characteristic({ id: "street_visibility", label: "Street Visibility", category: "market_presence", description: "Visibility from a street or customer path that may support identity, arrival, or retail/service demand.", ecosystems: ["retail", "office", "medical"], subtypes: ["neighborhood_retail", "professional_office", "wellness"], activities: ["walk_in_service", "client_meetings"], archetypes: ["wellness_practice", "marketing_agency"] }),
  characteristic({ id: "signage_opportunity", label: "Signage Opportunity", category: "market_presence", description: "Potential for exterior or building signage subject to lease, code, and landlord approval.", ecosystems: ["retail", "office", "industrial_flex"], subtypes: ["service_retail", "executive_office", "showroom_flex"], activities: ["walk_in_service", "client_meetings", "customer_showroom"], archetypes: ["wellness_practice", "financial_services_firm"] }),
  characteristic({ id: "walk_in_customer_access", label: "Walk-In Customer Access", category: "market_presence", description: "Access pattern for customers or patients who arrive without heavy appointment control.", ecosystems: ["retail", "medical"], subtypes: ["neighborhood_retail", "outpatient_clinic"], activities: ["walk_in_service", "walk_in_retail", "healthcare_delivery"], archetypes: ["wellness_practice", "outpatient_clinic"] }),
  characteristic({ id: "destination_customer_access", label: "Destination Customer Access", category: "market_presence", description: "Access pattern for customers intentionally traveling to the business rather than relying on foot traffic.", ecosystems: ["retail", "industrial_flex", "special_purpose"], subtypes: ["showroom_retail", "showroom_flex", "automotive"], activities: ["customer_showroom", "walk_in_service"], archetypes: ["furniture_maker", "auto_repair_business"] }),
  characteristic({ id: "retail_adjacent", label: "Retail Adjacent", category: "market_presence", description: "Commercial context adjacent to shops, restaurants, or services that shape employee and customer experience.", ecosystems: ["office", "retail", "medical"], subtypes: ["downtown_office", "neighborhood_retail", "medical_office"], activities: ["client_meetings", "walk_in_service"], archetypes: ["consulting_firm", "wellness_practice"] }),
  characteristic({ id: "hospital_adjacent", label: "Hospital Adjacent", category: "market_presence", description: "Proximity to hospital or clinical anchors relevant to medical and life-science decisions.", ecosystems: ["medical", "life_science"], subtypes: ["hospital_adjacent", "life_science_office"], activities: ["healthcare_delivery", "research"], archetypes: ["medical_practice", "biotech_company"] }),
  characteristic({ id: "campus_environment", label: "Campus Environment", category: "market_presence", description: "A campus-like setting with multiple buildings, shared amenities, or controlled environment.", ecosystems: ["office", "life_science", "industrial_flex", "special_purpose"], subtypes: ["office_campus", "innovation_campus", "research_development", "institutional"], activities: ["collaboration", "research", "product_development"], archetypes: ["startup", "biotech_company"] }),
  characteristic({ id: "professional_image", label: "Professional Image", category: "market_presence", description: "Representative environment where client-facing image, address, or arrival matters.", ecosystems: ["office", "medical"], subtypes: ["downtown_office", "executive_office", "medical_office"], activities: ["client_meetings", "healthcare_delivery"], archetypes: ["law_firm", "financial_services_firm"], observable: true, requiresValidation: false }),
  characteristic({ id: "creative_environment", label: "Creative Environment", category: "market_presence", description: "Building or district character useful for creative, design, media, or less formal office users.", ecosystems: ["office", "industrial_flex"], subtypes: ["creative_office", "showroom_flex"], activities: ["collaboration", "product_development"], archetypes: ["creative_studio", "marketing_agency"], observable: true, requiresValidation: false }),
  characteristic({ id: "industrial_identity", label: "Industrial Identity", category: "market_presence", description: "A visible operational or industrial district character distinct from conventional office or retail.", ecosystems: ["industrial_flex"], subtypes: ["small_bay_industrial", "warehouse", "contractor_service"], activities: ["service_dispatch", "storage", "manufacturing"], archetypes: ["general_contractor", "distributor"], observable: true, requiresValidation: false }),

  characteristic({ id: "transit_access", label: "Transit Access", category: "location_workforce", description: "Access to rail, bus, ferry, or transit connections relevant to employees, clients, patients, or customers.", ecosystems: ["office", "medical", "retail", "life_science"], subtypes: ["downtown_office", "medical_office", "downtown_retail", "innovation_campus"], activities: ["knowledge_work", "healthcare_delivery", "walk_in_service"], archetypes: ["consulting_firm", "medical_practice"], observable: true, requiresValidation: false }),
  characteristic({ id: "walkability", label: "Walkability", category: "location_workforce", description: "Walkable surrounding environment that supports employees, customers, restaurants, errands, or daily experience.", ecosystems: ["office", "retail", "medical"], subtypes: ["creative_office", "neighborhood_retail", "medical_office"], activities: ["client_meetings", "walk_in_service"], archetypes: ["marketing_agency", "wellness_practice"], observable: true, requiresValidation: false }),
  characteristic({ id: "freeway_access", label: "Freeway Access", category: "location_workforce", description: "Road access relevant to service territories, commuting, delivery, and regional distribution.", ecosystems: ["industrial_flex", "office", "medical"], subtypes: ["contractor_service", "suburban_office", "medical_office"], activities: ["service_dispatch", "distribution", "healthcare_delivery"], archetypes: ["hvac_company", "distributor", "medical_practice"], observable: true, requiresValidation: false }),
  characteristic({ id: "labor_access", label: "Labor Access", category: "location_workforce", description: "Regional access to workforce geography for operations, production, service, or office users.", ecosystems: ["industrial_flex", "office", "hospitality"], subtypes: ["distribution", "suburban_office", "food_beverage"], activities: ["manufacturing", "collaboration", "hospitality_service"], archetypes: ["light_manufacturer", "professional_office"] }),
  characteristic({ id: "regional_distribution_access", label: "Regional Distribution Access", category: "location_workforce", description: "Location logic supporting regional goods movement across a metro or broader market.", ecosystems: ["industrial_flex"], subtypes: ["distribution", "warehouse", "last_mile_logistics"], activities: ["distribution", "shipping"], archetypes: ["distributor", "importer"] }),
  characteristic({ id: "port_access", label: "Port Access", category: "location_workforce", description: "Port-oriented access relevant to import, distribution, storage, or goods movement where locally applicable.", ecosystems: ["industrial_flex"], subtypes: ["distribution", "warehouse"], activities: ["receiving", "distribution"], archetypes: ["importer", "distributor"] }),
  characteristic({ id: "airport_access", label: "Airport Access", category: "location_workforce", description: "Airport or air-cargo access relevant to regional travel, logistics, or service geography.", ecosystems: ["office", "industrial_flex"], subtypes: ["suburban_office", "last_mile_logistics", "distribution"], activities: ["client_meetings", "shipping", "service_dispatch"], archetypes: ["consulting_firm", "ecommerce_fulfillment_business"] }),
  characteristic({ id: "urban_core_access", label: "Urban Core Access", category: "location_workforce", description: "Central-city access to clients, institutions, amenities, transit, or dense employment.", ecosystems: ["office", "retail", "medical", "industrial_flex"], subtypes: ["downtown_office", "downtown_retail", "medical_office", "small_bay_industrial", "flex"], activities: ["knowledge_work", "client_meetings", "walk_in_service"], archetypes: ["law_firm", "marketing_agency"] }),
  characteristic({ id: "suburban_access", label: "Suburban Access", category: "location_workforce", description: "Auto-oriented suburban access supporting employees, patients, customers, or service areas.", ecosystems: ["office", "medical", "industrial_flex", "retail"], subtypes: ["suburban_office", "medical_office", "flex", "shopping_center"], activities: ["knowledge_work", "healthcare_delivery", "service_dispatch"], archetypes: ["medical_practice", "building_services_company"] }),
  characteristic({ id: "neighborhood_access", label: "Neighborhood Access", category: "location_workforce", description: "Local neighborhood access that can support small teams, local services, retail, or patient/customer relationships.", ecosystems: ["office", "retail", "medical"], subtypes: ["professional_office", "neighborhood_retail", "wellness"], activities: ["client_meetings", "walk_in_service"], archetypes: ["nonprofit_office", "wellness_practice"] }),

  characteristic({ id: "outdoor_storage", label: "Outdoor Storage", category: "outdoor_special_use", description: "Outdoor storage for materials, vehicles, equipment, or inventory, subject to zoning and lease validation.", ecosystems: ["industrial_flex", "special_purpose"], subtypes: ["contractor_yard", "manufacturing"], activities: ["equipment_storage", "vehicle_storage", "storage"], archetypes: ["landscaper", "general_contractor"] }),
  characteristic({ id: "secured_yard", label: "Secured Yard", category: "outdoor_special_use", description: "Fenced or controlled yard environment for operational storage or vehicle staging.", ecosystems: ["industrial_flex"], subtypes: ["contractor_yard", "distribution"], activities: ["vehicle_storage", "equipment_storage"], archetypes: ["landscaper", "equipment_service_company"] }),
  characteristic({ id: "contractor_yard", label: "Contractor Yard", category: "outdoor_special_use", description: "Yard-oriented environment for trades, materials, service vehicles, or equipment.", ecosystems: ["industrial_flex"], subtypes: ["contractor_yard", "contractor_service"], activities: ["service_dispatch", "equipment_storage", "vehicle_storage"], archetypes: ["general_contractor", "plumbing_company"] }),
  characteristic({ id: "equipment_storage", label: "Equipment Storage", category: "outdoor_special_use", description: "Storage capacity for business equipment, tools, machinery, or jobsite materials.", ecosystems: ["industrial_flex"], subtypes: ["contractor_service", "small_bay_industrial", "contractor_yard"], activities: ["equipment_storage", "service_dispatch"], archetypes: ["hvac_company", "electrician"] }),
  characteristic({ id: "material_storage", label: "Material Storage", category: "outdoor_special_use", description: "Storage needs for materials, components, supplies, or product inputs.", ecosystems: ["industrial_flex"], subtypes: ["warehouse", "manufacturing", "contractor_yard"], activities: ["storage", "inventory_management"], archetypes: ["cabinet_shop", "light_manufacturer"] }),
  characteristic({ id: "manufacturing_compatible", label: "Manufacturing Compatible", category: "outdoor_special_use", description: "Environment that may support production subject to zoning, power, ventilation, and buildout checks.", ecosystems: ["industrial_flex"], subtypes: ["manufacturing", "light_manufacturing"], activities: ["manufacturing", "light_manufacturing"], archetypes: ["light_manufacturer"] }),
  characteristic({ id: "assembly_compatible", label: "Assembly Compatible", category: "outdoor_special_use", description: "Environment that may support assembly or fabrication subject to use and building validation.", ecosystems: ["industrial_flex"], subtypes: ["light_manufacturing", "flex"], activities: ["assembly", "light_manufacturing"], archetypes: ["cabinet_shop", "furniture_maker"] }),
  characteristic({ id: "food_production_compatible", label: "Food Production Compatible", category: "outdoor_special_use", description: "Environment that may support food production if utilities, permits, ventilation, and code issues can be validated.", ecosystems: ["industrial_flex"], subtypes: ["food_production"], activities: ["food_production"], archetypes: ["food_producer"] }),
  characteristic({ id: "research_compatible", label: "Research Compatible", category: "outdoor_special_use", description: "Environment that may support research, prototyping, or technical operations subject to systems validation.", ecosystems: ["life_science", "industrial_flex"], subtypes: ["research_lab", "research_development"], activities: ["research", "product_development"], archetypes: ["research_company"] }),
  characteristic({ id: "medical_use_compatible", label: "Medical Use Compatible", category: "outdoor_special_use", description: "Environment that may support medical use if access, plumbing, code, and buildout are appropriate.", ecosystems: ["medical"], subtypes: ["medical_office", "outpatient_clinic"], activities: ["healthcare_delivery"], archetypes: ["medical_practice"] }),
  characteristic({ id: "education_use_compatible", label: "Education Use Compatible", category: "outdoor_special_use", description: "Environment that may support education or training uses subject to access, occupancy, and licensing checks.", ecosystems: ["special_purpose", "office"], subtypes: ["education", "professional_office"], activities: ["education", "training"], archetypes: ["education_provider", "training_center"] }),
  characteristic({ id: "automotive_use_compatible", label: "Automotive Use Compatible", category: "outdoor_special_use", description: "Environment that may support automotive service or vehicle-oriented business subject to zoning, layout, and code validation.", ecosystems: ["special_purpose", "industrial_flex"], subtypes: ["automotive", "contractor_yard"], activities: ["vehicle_storage", "walk_in_service"], archetypes: ["auto_repair_business"] }),
];

function role({ id, label, ecosystemId, subtypeIds = [], activityIds = [], commonOperationalCharacteristics = [], editorialPurpose }) {
  return {
    id,
    label,
    ecosystemId,
    compatibleSubtypes: subtypeIds,
    expectedActivityPatterns: activityIds,
    commonOperationalCharacteristics,
    editorialPurpose,
  };
}

const representativeRoles = [
  role({ id: "small_bay_service_environment", label: "Small-Bay Service Environment", ecosystemId: "industrial_flex", subtypeIds: ["small_bay_industrial", "contractor_service"], activityIds: ["service_dispatch", "equipment_storage", "receiving", "shipping"], commonOperationalCharacteristics: ["grade_level_loading", "small_suite_sizes", "service_vehicle_parking", "office_warehouse_mix", "freeway_access"], editorialPurpose: "Explains smaller industrial spaces used by trades, services, makers, and local operators." }),
  role({ id: "flex_business_park", label: "Flex Business Park", ecosystemId: "industrial_flex", subtypeIds: ["flex", "research_development"], activityIds: ["knowledge_work", "product_development", "assembly", "storage"], commonOperationalCharacteristics: ["flexible_suite_sizes", "high_office_percentage", "surface_parking", "freeway_access"], editorialPurpose: "Shows hybrid office-operational environments for teams that need more than conventional office." }),
  role({ id: "contractor_service_cluster", label: "Contractor / Service Cluster", ecosystemId: "industrial_flex", subtypeIds: ["contractor_service", "contractor_yard"], activityIds: ["service_dispatch", "vehicle_storage", "equipment_storage"], commonOperationalCharacteristics: ["service_vehicle_parking", "outdoor_storage", "contractor_yard", "drive_in_access", "freeway_access"], editorialPurpose: "Represents spaces where trades and service companies stage vehicles, crews, equipment, and dispatch." }),
  role({ id: "warehouse_distribution_environment", label: "Warehouse / Distribution Environment", ecosystemId: "industrial_flex", subtypeIds: ["warehouse", "distribution"], activityIds: ["receiving", "shipping", "distribution", "inventory_management"], commonOperationalCharacteristics: ["dock_high_loading", "truck_court", "high_clearance", "regional_distribution_access"], editorialPurpose: "Explains goods-movement environments where loading, storage, and reach matter most." }),
  role({ id: "last_mile_logistics_environment", label: "Last-Mile Logistics Environment", ecosystemId: "industrial_flex", subtypeIds: ["last_mile_logistics", "distribution"], activityIds: ["shipping", "distribution", "service_dispatch"], commonOperationalCharacteristics: ["last_mile_access", "fleet_parking", "delivery_access", "regional_distribution_access"], editorialPurpose: "Shows local delivery and service-territory environments inside or near a metro." }),
  role({ id: "light_manufacturing_environment", label: "Light Manufacturing Environment", ecosystemId: "industrial_flex", subtypeIds: ["light_manufacturing", "manufacturing"], activityIds: ["assembly", "light_manufacturing", "receiving", "shipping"], commonOperationalCharacteristics: ["grade_level_loading", "moderate_clearance", "high_power", "assembly_compatible"], editorialPurpose: "Represents production spaces for fabrication, assembly, and maker-oriented businesses." }),
  role({ id: "food_production_environment", label: "Food Production Environment", ecosystemId: "industrial_flex", subtypeIds: ["food_production"], activityIds: ["food_production", "receiving", "shipping"], commonOperationalCharacteristics: ["food_grade_infrastructure", "specialized_ventilation", "delivery_access", "food_production_compatible"], editorialPurpose: "Identifies food-production environments where infrastructure and compliance validation matter." }),
  role({ id: "showroom_flex_environment", label: "Showroom Flex Environment", ecosystemId: "industrial_flex", subtypeIds: ["showroom_flex"], activityIds: ["customer_showroom", "inventory_management", "receiving"], commonOperationalCharacteristics: ["showroom_frontage", "office_showroom_mix", "customer_parking", "delivery_access"], editorialPurpose: "Explains properties combining customer presentation with storage or light operations." }),
  role({ id: "research_development_environment", label: "Research and Development Environment", ecosystemId: "industrial_flex", subtypeIds: ["research_development", "flex"], activityIds: ["product_development", "research", "assembly"], commonOperationalCharacteristics: ["high_office_percentage", "fiber_connectivity", "research_compatible", "flexible_suite_sizes"], editorialPurpose: "Represents technical office/flex environments for product, engineering, prototyping, or research users." }),
  role({ id: "large_scale_distribution_environment", label: "Large-Scale Distribution Environment", ecosystemId: "industrial_flex", subtypeIds: ["distribution", "warehouse"], activityIds: ["receiving", "shipping", "distribution"], commonOperationalCharacteristics: ["dock_high_loading", "heavy_truck_access", "truck_court", "high_clearance"], editorialPurpose: "Shows larger logistics facilities that differ from small-bay or local service-industrial inventory." }),
  role({ id: "urban_industrial_environment", label: "Urban Industrial Environment", ecosystemId: "industrial_flex", subtypeIds: ["small_bay_industrial", "light_manufacturing", "flex"], activityIds: ["storage", "service_dispatch", "light_manufacturing"], commonOperationalCharacteristics: ["industrial_identity", "loading_constrained", "urban_core_access", "small_suite_sizes"], editorialPurpose: "Explains industrial utility embedded in denser urban commercial geography." }),
  role({ id: "industrial_campus_environment", label: "Industrial Campus Environment", ecosystemId: "industrial_flex", subtypeIds: ["warehouse", "distribution", "research_development"], activityIds: ["distribution", "product_development", "storage"], commonOperationalCharacteristics: ["campus_environment", "truck_court", "surface_parking", "regional_distribution_access"], editorialPurpose: "Represents multi-building industrial or technical campuses." }),

  role({ id: "downtown_class_a_office", label: "Downtown Class A Office", ecosystemId: "office", subtypeIds: ["downtown_office", "executive_office"], activityIds: ["knowledge_work", "client_meetings", "administrative_operations"], commonOperationalCharacteristics: ["professional_image", "transit_access", "large_floorplates", "structured_parking"], editorialPurpose: "Explains formal downtown towers used by corporate, legal, financial, and professional-service tenants." }),
  role({ id: "professional_office_environment", label: "Professional Office Environment", ecosystemId: "office", subtypeIds: ["professional_office", "executive_office"], activityIds: ["knowledge_work", "client_meetings", "administrative_operations"], commonOperationalCharacteristics: ["private_office_layout", "customer_parking", "professional_image"], editorialPurpose: "Represents client-facing office environments outside pure trophy-tower logic." }),
  role({ id: "creative_office_environment", label: "Creative Office Environment", ecosystemId: "office", subtypeIds: ["creative_office"], activityIds: ["knowledge_work", "collaboration", "product_development"], commonOperationalCharacteristics: ["creative_environment", "open_workspace", "flexible_suite_sizes", "walkability"], editorialPurpose: "Shows buildings where character, adaptability, and neighborhood identity influence office fit." }),
  role({ id: "executive_office_environment", label: "Executive Office Environment", ecosystemId: "office", subtypeIds: ["executive_office", "downtown_office"], activityIds: ["client_meetings", "knowledge_work"], commonOperationalCharacteristics: ["professional_image", "private_office_layout", "enhanced_security"], editorialPurpose: "Explains high-image client-facing office environments." }),
  role({ id: "suburban_office_campus", label: "Suburban Office Campus", ecosystemId: "office", subtypeIds: ["suburban_office", "office_campus"], activityIds: ["knowledge_work", "collaboration", "administrative_operations"], commonOperationalCharacteristics: ["campus_environment", "surface_parking", "suburban_access"], editorialPurpose: "Represents campus-style or auto-accessible suburban office environments." }),
  role({ id: "government_office_environment", label: "Government Office Environment", ecosystemId: "office", subtypeIds: ["government_office", "downtown_office"], activityIds: ["knowledge_work", "client_meetings", "administrative_operations"], commonOperationalCharacteristics: ["professional_image", "urban_core_access", "enhanced_security"], editorialPurpose: "Explains civic, agency, advocacy, and government-adjacent office decisions." }),
  role({ id: "small_tenant_office_environment", label: "Small-Tenant Office Environment", ecosystemId: "office", subtypeIds: ["professional_office", "creative_office"], activityIds: ["knowledge_work", "client_meetings"], commonOperationalCharacteristics: ["small_suite_sizes", "multi_tenant", "neighborhood_access"], editorialPurpose: "Represents office buildings that help smaller teams compare cost, access, and identity." }),
  role({ id: "transit_oriented_office_environment", label: "Transit-Oriented Office Environment", ecosystemId: "office", subtypeIds: ["downtown_office", "professional_office"], activityIds: ["knowledge_work", "client_meetings"], commonOperationalCharacteristics: ["transit_access", "walkability", "professional_image"], editorialPurpose: "Explains office environments chosen primarily for transit and regional access." }),

  role({ id: "medical_office_environment", label: "Medical Office Environment", ecosystemId: "medical", subtypeIds: ["medical_office"], activityIds: ["healthcare_delivery", "administrative_operations"], commonOperationalCharacteristics: ["customer_parking", "medical_use_compatible", "plumbing_intensive"], editorialPurpose: "Shows medical office settings where patient access and buildout validation drive fit." }),
  role({ id: "hospital_adjacent_medical_environment", label: "Hospital-Adjacent Medical Environment", ecosystemId: "medical", subtypeIds: ["hospital_adjacent", "medical_office"], activityIds: ["healthcare_delivery", "administrative_operations"], commonOperationalCharacteristics: ["hospital_adjacent", "patientAccess", "customer_parking", "enhanced_security"].filter((id) => id !== "patientAccess"), editorialPurpose: "Explains medical environments shaped by nearby hospitals or clinical anchors." }),
  role({ id: "outpatient_clinic_environment", label: "Outpatient Clinic Environment", ecosystemId: "medical", subtypeIds: ["outpatient_clinic"], activityIds: ["healthcare_delivery", "walk_in_service"], commonOperationalCharacteristics: ["walk_in_customer_access", "customer_parking", "medical_use_compatible"], editorialPurpose: "Represents patient-facing clinic settings where access and operations must be validated." }),
  role({ id: "research_lab_environment", label: "Research Lab Environment", ecosystemId: "life_science", subtypeIds: ["research_lab", "wet_lab", "biotech_research"], activityIds: ["research", "product_development"], commonOperationalCharacteristics: ["lab_infrastructure", "wet_lab_potential", "specialized_ventilation", "high_power"], editorialPurpose: "Explains lab-capable environments where infrastructure is a core decision factor." }),
  role({ id: "life_science_campus", label: "Life Science Campus", ecosystemId: "life_science", subtypeIds: ["innovation_campus", "life_science_office", "biotech_research"], activityIds: ["research", "product_development", "collaboration"], commonOperationalCharacteristics: ["campus_environment", "research_compatible", "transit_access", "enhanced_security"], editorialPurpose: "Shows institutional or campus-style innovation environments for biotech and research users." }),
  role({ id: "biotech_research_environment", label: "Biotech Research Environment", ecosystemId: "life_science", subtypeIds: ["biotech_research", "wet_lab"], activityIds: ["research", "product_development"], commonOperationalCharacteristics: ["lab_infrastructure", "wet_lab_potential", "backup_power", "specialized_ventilation"], editorialPurpose: "Represents biotech-specific research settings with specialized validation needs." }),

  role({ id: "neighborhood_service_retail", label: "Neighborhood Service Retail", ecosystemId: "retail", subtypeIds: ["neighborhood_retail", "service_retail"], activityIds: ["walk_in_service", "walk_in_retail"], commonOperationalCharacteristics: ["street_visibility", "walk_in_customer_access", "customer_parking"], editorialPurpose: "Explains local-serving storefront or service environments." }),
  role({ id: "destination_retail_environment", label: "Destination Retail Environment", ecosystemId: "retail", subtypeIds: ["lifestyle_retail", "shopping_center", "showroom_retail"], activityIds: ["walk_in_retail", "customer_showroom"], commonOperationalCharacteristics: ["destination_customer_access", "customer_parking", "signage_opportunity"], editorialPurpose: "Represents retail environments chosen for intentional customer trips rather than pure foot traffic." }),
  role({ id: "showroom_retail_environment", label: "Showroom Retail Environment", ecosystemId: "retail", subtypeIds: ["showroom_retail"], activityIds: ["customer_showroom", "walk_in_service"], commonOperationalCharacteristics: ["showroom_frontage", "street_visibility", "destination_customer_access"], editorialPurpose: "Shows design, product, or appointment-driven retail/showroom environments." }),
  role({ id: "education_environment", label: "Education Environment", ecosystemId: "special_purpose", subtypeIds: ["education"], activityIds: ["education", "training"], commonOperationalCharacteristics: ["education_use_compatible", "customer_parking", "enhanced_security"], editorialPurpose: "Represents educational or training uses with access and occupancy questions." }),
  role({ id: "automotive_service_environment", label: "Automotive Service Environment", ecosystemId: "special_purpose", subtypeIds: ["automotive"], activityIds: ["walk_in_service", "vehicle_storage", "equipment_storage"], commonOperationalCharacteristics: ["automotive_use_compatible", "drive_in_access", "customer_parking"], editorialPurpose: "Explains vehicle-oriented service environments." }),
  role({ id: "institutional_environment", label: "Institutional Environment", ecosystemId: "special_purpose", subtypeIds: ["institutional", "nonprofit", "education"], activityIds: ["education", "training", "administrative_operations"], commonOperationalCharacteristics: ["campus_environment", "enhanced_security", "education_use_compatible"], editorialPurpose: "Represents civic, educational, nonprofit, or institutional anchors that shape commercial geography." }),
];

function indexById(items) {
  return items.reduce((result, item) => {
    result[item.id] = item;
    return result;
  }, {});
}

module.exports = {
  schemaVersion: 1,
  operationalCharacteristicCategories,
  operationalCharacteristics,
  representativeRoles,
  operationalCharacteristicCategoryById: indexById(operationalCharacteristicCategories),
  operationalCharacteristicById: indexById(operationalCharacteristics),
  representativeRoleById: indexById(representativeRoles),
};
