// Generated by scripts/build-representative-building-expansion-v1.js
// Internal representative building card expansion derived primarily from raw listing descriptions.

const byDistrictPath = {
  "/commercial-real-estate/NY/long-island-city/long-island-city/": [
    {
      "name": "The Falchi Building, 31-00 47th Avenue",
      "address": "The Falchi Building, 31-00 47th Avenue",
      "building_type_summary": "Office / flex",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / flex use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / flex property pattern within Long Island City's Queens office/flex and production market.",
      "canonical_path": "/commercial-real-estate/building/NY/long-island-city/the-falchi-building-31-00-47th-avenue/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "high",
      "keyword_tags": [
        "office",
        "professional",
        "coworking",
        "manufacturing"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 4,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ],
  "/commercial-real-estate/TX/houston/energy-corridor/": [
    {
      "name": "11111 Katy Freeway",
      "address": "11111 Katy Freeway",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Energy Corridor's west Houston corporate and energy office corridor.",
      "canonical_path": "/commercial-real-estate/building/TX/houston/11111-katy-freeway/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    },
    {
      "name": "Park Row",
      "address": "1400 Broadfield Blvd",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Energy Corridor's west Houston corporate and energy office corridor.",
      "canonical_path": "/commercial-real-estate/building/TX/houston/1400-broadfield-blvd/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    },
    {
      "name": "Park Ten Place",
      "address": "16225 Park Ten Place",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Energy Corridor's west Houston corporate and energy office corridor.",
      "canonical_path": "/commercial-real-estate/building/TX/houston/16225-park-ten-place/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    },
    {
      "name": "800 Town & Country Blvd.",
      "address": "800 Town & Country Blvd.",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Energy Corridor's west Houston corporate and energy office corridor.",
      "canonical_path": "/commercial-real-estate/building/TX/houston/800-town-and-country-blvd/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ],
  "/commercial-real-estate/TX/round-rock/round-rock/": [
    {
      "name": "Old Town Square",
      "address": "1 Chisolm Trail Road",
      "building_type_summary": "Office / flex",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / flex use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / flex property pattern within Round Rock's north Austin office, medical, flex, and manufacturing-support market.",
      "canonical_path": "/commercial-real-estate/building/TX/round-rock/1-chisolm-trail-road/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "high",
      "keyword_tags": [
        "office",
        "professional",
        "coworking",
        "rail"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 4,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ],
  "/commercial-real-estate/CA/oakland/downtown-oakland/": [
    {
      "name": "Lake Merritt",
      "address": "1901 Harrison St",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Downtown Oakland's BART-centered civic and East Bay office core.",
      "canonical_path": "/commercial-real-estate/building/CA/oakland/1901-harrison-st/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    },
    {
      "name": "Oakland City Center",
      "address": "505 14th St",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Downtown Oakland's BART-centered civic and East Bay office core.",
      "canonical_path": "/commercial-real-estate/building/CA/oakland/505-14th-st/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ],
  "/commercial-real-estate/TX/austin/the-domain/": [
    {
      "name": "3220 Feathergrass Ct",
      "address": "3220 Feathergrass Ct",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within The Domain's north Austin tech office and mixed-use campus district.",
      "canonical_path": "/commercial-real-estate/building/TX/austin/3220-feathergrass-ct/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ],
  "/commercial-real-estate/AZ/chandler/chandler/": [
    {
      "name": "San Tan Corporate Center II",
      "address": "3100 West Ray Road",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Chandler's East Valley office, semiconductor, flex, and professional market.",
      "canonical_path": "/commercial-real-estate/building/AZ/chandler/3100-west-ray-road/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ],
  "/commercial-real-estate/CO/denver/denver-tech-center/": [
    {
      "name": "DTC Tech",
      "address": "4600 S Syracuse St",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Denver Tech Center's southeast Denver corporate office core.",
      "canonical_path": "/commercial-real-estate/building/CO/denver/4600-s-syracuse-st/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    },
    {
      "name": "DTC Corporate Center III",
      "address": "7900 E Union Ave",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Denver Tech Center's southeast Denver corporate office core.",
      "canonical_path": "/commercial-real-estate/building/CO/denver/7900-e-union-ave/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    },
    {
      "name": "6795 - 6825 East Tennessee Ave",
      "address": "6795 - 6825 East Tennessee Ave",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Denver Tech Center's southeast Denver corporate office core.",
      "canonical_path": "/commercial-real-estate/building/CO/denver/6795-6825-east-tennessee-ave/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ],
  "/commercial-real-estate/CA/palo-alto/downtown-palo-alto/": [
    {
      "name": "Hamilton Avenue",
      "address": "228 Hamilton Ave",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Downtown Palo Alto's walkable Peninsula professional and startup office district.",
      "canonical_path": "/commercial-real-estate/building/CA/palo-alto/228-hamilton-ave/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    },
    {
      "name": "Downtown Lytton Avenue",
      "address": "530 Lytton Ave",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within Downtown Palo Alto's walkable Peninsula professional and startup office district.",
      "canonical_path": "/commercial-real-estate/building/CA/palo-alto/530-lytton-ave/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ],
  "/commercial-real-estate/CA/san-jose/north-san-jose/": [
    {
      "name": "2033 Gateway Place",
      "address": "2033 Gateway Place",
      "building_type_summary": "Office / flex",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / flex use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / flex property pattern within North San Jose's technology office, R&D, and flex business-park district.",
      "canonical_path": "/commercial-real-estate/building/CA/san-jose/2033-gateway-place/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "high",
      "keyword_tags": [
        "office",
        "professional",
        "coworking",
        "freeway access"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 4,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    },
    {
      "name": "2880 Zanker Rd",
      "address": "2880 Zanker Rd",
      "building_type_summary": "Office / coworking",
      "size": null,
      "descriptor": "Recurring historical listings at this address point to office / coworking use, including office, professional, coworking.",
      "representative_reason": "Represents a recurring office / coworking property pattern within North San Jose's technology office, R&D, and flex business-park district.",
      "canonical_path": "/commercial-real-estate/building/CA/san-jose/2880-zanker-rd/",
      "image": null,
      "source_basis": "listing_corpus_keyword_extraction_v1",
      "source_confidence": "medium",
      "keyword_tags": [
        "office",
        "professional",
        "coworking"
      ],
      "evidence": {
        "listing_frequency": 5,
        "recent_activity": 3,
        "keyword_relevance": 3,
        "building_prominence": 3,
        "multiple_listing_references": 5,
        "district_consistency": 5,
        "commercial_relevance": 5
      }
    }
  ]
};

module.exports = {
  byDistrictPath,
  summary: [
  {
    "name": "Long Island City",
    "path": "/commercial-real-estate/NY/long-island-city/long-island-city/",
    "existing_card_count": 0,
    "generated_card_count": 1,
    "raw_listing_record_count": 9,
    "unique_address_group_count": 1,
    "status": "thin_listing_depth",
    "examples": [
      {
        "name": "The Falchi Building, 31-00 47th Avenue",
        "address": "The Falchi Building, 31-00 47th Avenue",
        "keywords": [
          "office",
          "professional",
          "coworking",
          "manufacturing"
        ],
        "confidence": "high"
      }
    ],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Energy Corridor",
    "path": "/commercial-real-estate/TX/houston/energy-corridor/",
    "existing_card_count": 0,
    "generated_card_count": 4,
    "raw_listing_record_count": 42,
    "unique_address_group_count": 4,
    "status": "moderate_listing_depth",
    "examples": [
      {
        "name": "11111 Katy Freeway",
        "address": "11111 Katy Freeway",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      },
      {
        "name": "Park Row",
        "address": "1400 Broadfield Blvd",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      },
      {
        "name": "Park Ten Place",
        "address": "16225 Park Ten Place",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      }
    ],
    "caution": null
  },
  {
    "name": "Round Rock",
    "path": "/commercial-real-estate/TX/round-rock/round-rock/",
    "existing_card_count": 0,
    "generated_card_count": 1,
    "raw_listing_record_count": 11,
    "unique_address_group_count": 1,
    "status": "thin_listing_depth",
    "examples": [
      {
        "name": "Old Town Square",
        "address": "1 Chisolm Trail Road",
        "keywords": [
          "office",
          "professional",
          "coworking",
          "rail"
        ],
        "confidence": "high"
      }
    ],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Downtown Oakland",
    "path": "/commercial-real-estate/CA/oakland/downtown-oakland/",
    "existing_card_count": 0,
    "generated_card_count": 2,
    "raw_listing_record_count": 22,
    "unique_address_group_count": 2,
    "status": "thin_listing_depth",
    "examples": [
      {
        "name": "Lake Merritt",
        "address": "1901 Harrison St",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      },
      {
        "name": "Oakland City Center",
        "address": "505 14th St",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      }
    ],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "The Domain",
    "path": "/commercial-real-estate/TX/austin/the-domain/",
    "existing_card_count": 0,
    "generated_card_count": 1,
    "raw_listing_record_count": 11,
    "unique_address_group_count": 1,
    "status": "thin_listing_depth",
    "examples": [
      {
        "name": "3220 Feathergrass Ct",
        "address": "3220 Feathergrass Ct",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      }
    ],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Chandler",
    "path": "/commercial-real-estate/AZ/chandler/chandler/",
    "existing_card_count": 0,
    "generated_card_count": 1,
    "raw_listing_record_count": 11,
    "unique_address_group_count": 1,
    "status": "thin_listing_depth",
    "examples": [
      {
        "name": "San Tan Corporate Center II",
        "address": "3100 West Ray Road",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      }
    ],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Denver Tech Center",
    "path": "/commercial-real-estate/CO/denver/denver-tech-center/",
    "existing_card_count": 0,
    "generated_card_count": 3,
    "raw_listing_record_count": 41,
    "unique_address_group_count": 3,
    "status": "thin_listing_depth",
    "examples": [
      {
        "name": "DTC Tech",
        "address": "4600 S Syracuse St",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      },
      {
        "name": "DTC Corporate Center III",
        "address": "7900 E Union Ave",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      },
      {
        "name": "6795 - 6825 East Tennessee Ave",
        "address": "6795 - 6825 East Tennessee Ave",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      }
    ],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Downtown Palo Alto",
    "path": "/commercial-real-estate/CA/palo-alto/downtown-palo-alto/",
    "existing_card_count": 10,
    "generated_card_count": 2,
    "raw_listing_record_count": 22,
    "unique_address_group_count": 2,
    "status": "thin_listing_depth",
    "examples": [
      {
        "name": "Hamilton Avenue",
        "address": "228 Hamilton Ave",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      },
      {
        "name": "Downtown Lytton Avenue",
        "address": "530 Lytton Ave",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      }
    ],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "North San Jose",
    "path": "/commercial-real-estate/CA/san-jose/north-san-jose/",
    "existing_card_count": 11,
    "generated_card_count": 2,
    "raw_listing_record_count": 22,
    "unique_address_group_count": 2,
    "status": "thin_listing_depth",
    "examples": [
      {
        "name": "2033 Gateway Place",
        "address": "2033 Gateway Place",
        "keywords": [
          "office",
          "professional",
          "coworking",
          "freeway access"
        ],
        "confidence": "high"
      },
      {
        "name": "2880 Zanker Rd",
        "address": "2880 Zanker Rd",
        "keywords": [
          "office",
          "professional",
          "coworking"
        ],
        "confidence": "medium"
      }
    ],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Commerce City",
    "path": "/commercial-real-estate/CO/commerce-city/commerce-city/",
    "existing_card_count": 0,
    "generated_card_count": 0,
    "raw_listing_record_count": 0,
    "unique_address_group_count": 0,
    "status": "no_publishable_listing_cards",
    "examples": [],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Elizabeth Industrial",
    "path": "/commercial-real-estate/NJ/elizabeth/elizabeth-industrial/",
    "existing_card_count": 0,
    "generated_card_count": 0,
    "raw_listing_record_count": 0,
    "unique_address_group_count": 0,
    "status": "no_publishable_listing_cards",
    "examples": [],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Industry City / Sunset Park",
    "path": "/commercial-real-estate/NY/new-york/industry-city-sunset-park/",
    "existing_card_count": 0,
    "generated_card_count": 0,
    "raw_listing_record_count": 0,
    "unique_address_group_count": 0,
    "status": "no_publishable_listing_cards",
    "examples": [],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "JFK Airport Area",
    "path": "/commercial-real-estate/NY/new-york/jfk-airport-area/",
    "existing_card_count": 0,
    "generated_card_count": 0,
    "raw_listing_record_count": 0,
    "unique_address_group_count": 0,
    "status": "no_publishable_listing_cards",
    "examples": [],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  },
  {
    "name": "Port Newark / Elizabeth",
    "path": "/commercial-real-estate/NJ/newark/port-newark-elizabeth/",
    "existing_card_count": 0,
    "generated_card_count": 0,
    "raw_listing_record_count": 0,
    "unique_address_group_count": 0,
    "status": "no_publishable_listing_cards",
    "examples": [],
    "caution": "Raw listing evidence is too thin for a full representative card set; avoid padding with address-only cards until additional corpus recovery or public building review is available."
  }
],
};
