function clean(value) {
  return String(value || "").trim();
}

function slugify(value) {
  return clean(value)
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildingPath(citySlug, address) {
  return `/commercial-real-estate/building/CA/${citySlug}/${slugify(address)}/`;
}

function district({ id, name, city, slug }) {
  return {
    id,
    name,
    slug,
    city,
    state_abbr: "CA",
    area_type: "district",
    path: `/commercial-real-estate/CA/${slugify(city)}/${slug}/`,
  };
}

const districts = {
  natomas: district({ id: "natomas", name: "Natomas", city: "Sacramento", slug: "natomas" }),
  powerInn: district({ id: "power-inn-industrial", name: "Power Inn Industrial", city: "Sacramento", slug: "power-inn-industrial" }),
  ranchoCordova: district({ id: "rancho-cordova-commercial-core", name: "Rancho Cordova Commercial Core", city: "Rancho Cordova", slug: "rancho-cordova-commercial-core" }),
  westSacramento: district({ id: "west-sacramento-industrial", name: "West Sacramento Industrial", city: "West Sacramento", slug: "west-sacramento-industrial" }),
};

const districtCopy = {
  natomas: {
    workplaceCharacter: "North Sacramento industrial and flex environment shaped by I-5, I-80, airport access, and service-territory coverage.",
    neighborhoodCharacter: "Auto-oriented office/flex and industrial geography where freeway access often matters more than street activity.",
    transit: "Freeway and airport access are stronger decision drivers than pedestrian or transit access.",
    parking: "Parking and vehicle movement are usually part of the operating question and should be validated by suite.",
    amenities: "Amenities are more practical and auto-oriented than downtown; users should evaluate employee convenience by shift pattern.",
  },
  powerInn: {
    workplaceCharacter: "Sacramento industrial corridor with small-bay, warehouse, service, and light-production environments tied to Highway 50 and south/east Sacramento access.",
    neighborhoodCharacter: "Operational district where loading, service access, power, yard, and permitted use questions matter more than office image.",
    transit: "Highway 50 access is the main regional access advantage; transit and walkability are secondary.",
    parking: "Parking, truck movement, and service-vehicle needs vary by property and should be validated early.",
    amenities: "The surrounding environment is work-focused, with fewer client-facing amenities than downtown or suburban office districts.",
  },
  ranchoCordova: {
    workplaceCharacter: "Highway 50 office/flex and service-industrial environment where parking, larger footprints, and suburban access shape fit.",
    neighborhoodCharacter: "Suburban commercial core with a mix of office parks, flex buildings, and service-oriented industrial properties.",
    transit: "Highway 50 and regional drive access are the main advantages; transit usefulness depends on the exact address.",
    parking: "Surface parking and vehicle logistics are often stronger than central Sacramento, but allocation still needs confirmation.",
    amenities: "Amenities are distributed across an auto-oriented commercial corridor rather than concentrated around a walkable downtown.",
  },
  westSacramento: {
    workplaceCharacter: "Industrial and warehouse environment near the Sacramento core where I-80, I-5, and regional goods movement shape decisions.",
    neighborhoodCharacter: "Operational industrial district with stronger warehouse, distribution, and service utility than client-facing office identity.",
    transit: "Regional freeway access is the primary access story; employee commute patterns and truck routes should be validated.",
    parking: "Vehicle, trailer, and truck circulation needs can be central and must be evaluated at the property level.",
    amenities: "Amenities are secondary to operational access, loading, storage, and distribution utility.",
  },
};

const sourceDocs = {
  cbre: "data-sources/company-exports/raw/cbre__sacramento-region.csv",
  colliers: "data-sources/company-exports/raw/colliers__sacramento.csv",
};

function industrialBrief(fields) {
  return {
    status: "published",
    ecosystemContext: {
      primaryEcosystem: "industrial_flex",
      ecosystemSubtypes: fields.ecosystemSubtypes,
      representativeRole: fields.representativeRole,
    },
    businessFit: {
      archetypes: fields.businessArchetypes,
      activities: fields.businessActivities,
      fitSummary: fields.fitSummary,
    },
    operationalProfile: fields.operationalProfile,
    environmentExplanation: fields.environmentExplanation,
    comparisonContext: {
      relatedDistricts: fields.relatedDistricts || [],
    },
    evidence: {
      confidence: fields.confidence || "editorially_supported",
      provenance: {
        ecosystem: "representative-building",
        operationalCharacteristics: "mixed",
        editorialInterpretation: "building-brief",
      },
      sourceNotes: fields.sourceNotes || [],
    },
    validationChecklist: fields.validationNotes,
    ...fields,
  };
}

function record(fields) {
  const canonicalDistrict = districts[fields.districtKey];
  const defaults = districtCopy[fields.districtKey];
  const path = buildingPath(fields.citySlug, fields.address);
  const brief = industrialBrief(fields.brief);

  return {
    id: `sacramento-industrial-flex-${slugify(fields.address)}`,
    building_path: path,
    identity: {
      name: fields.name,
      address: fields.address,
      city: fields.city,
      state_abbr: "CA",
      district: canonicalDistrict.name,
      canonicalDistrict,
      secondaryDistricts: [],
      buildingType: fields.buildingType || "Industrial / flex",
      primarySpaceType: fields.primarySpaceType || "industrial",
      assetClass: "Representative Industrial & Flex Building",
    },
    editorial: {
      editorialRole: fields.editorialRole,
      editorialReason: fields.editorialReason,
      representativeThemes: fields.representativeThemes,
    },
    business: {
      businessFit: fields.businessFit,
      idealCompanyProfiles: brief.idealFor,
      companySizes: fields.companySizes || ["small and mid-sized businesses", "operations teams", "service and distribution users"],
    },
    experience: {
      workplaceCharacter: defaults.workplaceCharacter,
      neighborhoodCharacter: defaults.neighborhoodCharacter,
      executivePresence: "low",
      innovationScore: fields.innovationScore || "moderate",
    },
    operations: {
      transit: defaults.transit,
      parking: defaults.parking,
      amenities: defaults.amenities,
      foodEnvironment: "Food and service amenities are secondary to operational access and should be evaluated by employee schedule.",
    },
    tradeoffs: {
      strengths: brief.advantages,
      limitations: brief.tradeoffs,
      businessesThatShouldCompare: brief.mayNotFit,
      nearbyAlternatives: fields.relatedDistrictPaths || [],
    },
    validation: {
      questionsToValidate: brief.validationNotes,
      tourObservations: brief.validationNotes.slice(0, 3),
    },
    relationships: {
      nearbyBuildings: (fields.nearbyBuildingPaths || []).slice(0, 5),
      comparisonBuildings: (fields.comparisonBuildingPaths || []).slice(0, 5),
      relatedDistricts: fields.relatedDistrictPaths || [],
    },
    quality: {
      sourceConfidence: fields.sourceConfidence || "high",
      publicationStatus: "published",
      sourceBasis: "Sacramento Industrial & Flex Building Brief Standard v1",
    },
    buildingBrief: brief,
  };
}

const cityInsight = {
  title: "Choosing the Right Commercial Location",
  url: "/commercial-real-estate/lease-guide/choosing-the-right-commercial-location/",
  summary: "Use location fit, access, customers, employees, operations, and validation needs before narrowing the building list.",
};

const compareSpaces = {
  title: "How to Compare Commercial Spaces",
  url: "/commercial-real-estate/lease-guide/how-to-compare-commercial-spaces/",
  summary: "Compare options by operating needs, total occupancy cost, access, buildout, and future flexibility.",
};

const tenantImprovements = {
  title: "Tenant Improvements",
  url: "/commercial-real-estate/lease-guide/tenant-improvements/",
  summary: "Pressure-test buildout scope, utility requirements, timing, landlord approvals, and improvement responsibility.",
};

const records = [
  record({
    name: "3100 Ramco St",
    address: "3100 Ramco St",
    city: "West Sacramento",
    citySlug: "west-sacramento",
    districtKey: "westSacramento",
    buildingType: "Large-format industrial / distribution",
    primarySpaceType: "warehouse",
    editorialRole: "Large-Scale Distribution Environment",
    editorialReason: "Represents West Sacramento's larger logistics and distribution environment, where loading, clear height, trailer movement, and regional freeway access become central search questions.",
    representativeThemes: ["Distribution", "Warehouse", "Regional access", "Large-format operations"],
    businessFit: ["distribution", "warehouse", "e-commerce fulfillment", "wholesale operations"],
    relatedDistrictPaths: [districts.powerInn.path, districts.natomas.path, districts.ranchoCordova.path],
    nearbyBuildingPaths: [
      buildingPath("west-sacramento", "2928 Ramco St"),
      buildingPath("west-sacramento", "3380 Industrial Blvd"),
      buildingPath("sacramento", "1329 N Market Blvd"),
    ],
    comparisonBuildingPaths: [
      buildingPath("west-sacramento", "2928 Ramco St"),
      buildingPath("sacramento", "8583 Elder Creek Rd"),
      buildingPath("rancho-cordova", "11201 Sun Center Dr"),
    ],
    brief: {
      buildingSummary: "3100 Ramco St is a large-format West Sacramento industrial building for businesses comparing distribution, warehouse, and fulfillment environments near I-80 and I-5. It is most useful as a benchmark for users whose decision depends on loading, clear height, trailer movement, power, and regional goods movement rather than office image.",
      buildingImportance: "This property matters because it shows the scale end of Sacramento industrial/flex decision-making. It helps separate a true distribution search from small-bay service, contractor, or showroom-flex needs. The source record identifies multiple logistics-oriented characteristics, but a tenant still needs to validate the exact operating fit before treating any available suite as workable.",
      quickFacts: [
        { label: "Primary ecosystem", value: "Industrial & flex" },
        { label: "Representative role", value: "Large-scale distribution environment" },
        { label: "District", value: "West Sacramento Industrial" },
        { label: "Source-supported form", value: "Tilt-up concrete industrial building with large-format distribution configuration" },
        { label: "Loading context", value: "CBRE source identifies dock doors and grade-level doors; exact access should be confirmed" },
        { label: "Clear-height context", value: "CBRE source identifies approximately 36-foot clear height" },
        { label: "Power context", value: "CBRE source identifies 6,000 amps, 277/480v, 3-phase power; tenant requirements still need verification" },
        { label: "Parking context", value: "CBRE source identifies passenger and trailer parking counts; allocation and availability should be verified" },
      ],
      idealFor: [
        "Distributors, wholesalers, importers, and e-commerce fulfillment users that need a larger warehouse platform rather than compact service space.",
        "Operations teams that evaluate buildings by loading, clear height, trailer movement, and freeway access before office presentation.",
        "Businesses comparing West Sacramento for central regional access to Sacramento, I-80, I-5, and westside logistics routes.",
        "Users that may need divisibility or larger contiguous industrial capacity, subject to current suite configuration.",
      ],
      mayNotFit: [
        "Small contractors or service businesses that mainly need modest storage, a small office, and vehicle dispatch rather than a large logistics platform.",
        "Customer-facing showroom or service-retail users whose success depends on visibility, walk-in access, or a polished visitor experience.",
        "Production users whose power, ventilation, hazardous-material, or permitting needs cannot be confirmed from the available property information.",
      ],
      buildingExperience: "The experience is operational and logistics-oriented. A tour should focus less on arrival polish and more on whether trucks, trailers, employees, inventory, and outbound orders can move through the site without friction. For many users, the building's value depends on matching the exact door mix, circulation, and suite size to the operating model.",
      districtContext: "3100 Ramco St sits in West Sacramento Industrial, a district that gives Sacramento users a downtown-edge industrial alternative with regional freeway access. Compare Power Inn when Highway 50 and south/east Sacramento reach matter more, Natomas when airport and north Sacramento access matter more, and Rancho Cordova when the search needs more office/flex balance.",
      advantages: [
        "Represents larger distribution functionality rather than small-bay or contractor-service space.",
        "Source-backed loading, clear-height, power, parking, trailer-parking, and divisibility signals make it useful for operational due diligence.",
        "West Sacramento location can support regional access without moving deep into a suburban office/flex corridor.",
        "Strong benchmark for deciding whether a business truly needs large-format warehouse infrastructure.",
      ],
      tradeoffs: [
        "The scale and logistics orientation may exceed what smaller service or storage users actually need.",
        "Customer-facing image, walkability, and surrounding amenities are secondary to operational utility.",
        "Even with strong source facts, the exact suite, truck path, trailer staging, power availability, and sprinkler requirements must be validated.",
        "Regional access may be strong, but employee commute and labor geography still need to match the operation.",
      ],
      operationalProfile: [
        { label: "Loading and truck movement", summary: "Source material identifies dock and grade-level loading. Treat the door count, staging pattern, and truck circulation as core validation items, not assumptions." },
        { label: "Warehouse configuration", summary: "The building helps explain larger-format distribution needs, including clear height, divisibility, and storage density questions." },
        { label: "Power and systems", summary: "Source material identifies substantial electrical service and ESFR sprinklers. Tenant-specific power, insurance, and system requirements still require property validation." },
        { label: "Parking and trailers", summary: "Passenger and trailer parking are part of the source record, but allocation, timing, and operational rules should be confirmed." },
      ],
      environmentExplanation: {
        whyItExists: "Large-scale distribution environments exist for businesses that move goods through a region and need loading, storage, truck access, and building systems to work together.",
        whyChooseThisEnvironment: "Choose this environment over small-bay service or flex space when inventory movement, trailer access, clear height, and regional distribution efficiency matter more than office image or customer presentation.",
        representativeValue: "3100 Ramco St is the Sacramento calibration benchmark for larger logistics requirements.",
      },
      nearbyAlternatives: [
        { label: "2928 Ramco St", url: buildingPath("west-sacramento", "2928 Ramco St"), reason: "Prefer this when a warehouse/distribution setting in the same district may offer a smaller or more focused distribution-center comparison." },
        { label: "8583 Elder Creek Rd", url: buildingPath("sacramento", "8583 Elder Creek Rd"), reason: "Prefer this when light manufacturing, technical infrastructure, and Highway 50 access matter more than large-format logistics scale." },
        { label: "11201 Sun Center Dr", url: buildingPath("rancho-cordova", "11201 Sun Center Dr"), reason: "Prefer this when yard-oriented contractor or service operations matter more than warehouse distribution throughput." },
        { label: "1329 N Market Blvd", url: buildingPath("sacramento", "1329 N Market Blvd"), reason: "Prefer this when north Sacramento last-mile access and a smaller warehouse footprint may fit better." },
      ],
      relatedDistricts: [
        { districtId: "power-inn-industrial", reason: "Compare Power Inn for a Highway 50 industrial corridor with more small-bay and light-production context." },
        { districtId: "natomas", reason: "Compare Natomas when airport access, I-5/I-80 reach, and north Sacramento service coverage matter more." },
        { districtId: "rancho-cordova-commercial-core", reason: "Compare Rancho Cordova when the search needs more office/flex or contractor-service orientation." },
      ],
      validationNotes: [
        "Confirm the available suite's dock and grade-level door access.",
        "Verify truck circulation, trailer parking, and delivery-hour rules.",
        "Confirm clear height, sprinkler requirements, and storage-racking assumptions.",
        "Verify power capacity for the specific use and equipment load.",
        "Confirm permitted use, employee parking, trailer allocation, and any exterior storage limits.",
      ],
      relatedInsights: [cityInsight, compareSpaces, tenantImprovements],
      representativeCompanies: [
        "Relevant company categories include distributors, wholesalers, importers, e-commerce fulfillment users, and regional operations teams.",
        "These categories describe environmental fit; they are not claims about current occupants.",
      ],
      ecosystemSubtypes: ["distribution", "warehouse", "last_mile_logistics"],
      representativeRole: "large_scale_distribution_environment",
      businessActivities: ["receiving", "shipping", "distribution", "inventory_management", "storage"],
      businessArchetypes: ["distributor", "wholesaler", "importer", "ecommerce_fulfillment_business"],
      operationalCharacteristics: ["dock_high_loading", "grade_level_loading", "truck_court", "high_clearance", "high_power", "large_floorplates", "divisible_space", "regional_distribution_access", "freeway_access"],
      fitSummary: "Large-format distribution fit depends on loading, clear height, truck movement, and freeway reach.",
      confidence: "verified_property_fact",
      sourceNotes: [`${sourceDocs.cbre}: source rows for 3100 Ramco St identify dock doors, grade-level doors, clear height, power, parking, trailer parking, ESFR sprinklers, and divisibility.`],
    },
  }),
  record({
    name: "8583 Elder Creek Rd",
    address: "8583 Elder Creek Rd",
    city: "Sacramento",
    citySlug: "sacramento",
    districtKey: "powerInn",
    buildingType: "Light industrial / manufacturing",
    primarySpaceType: "industrial",
    editorialRole: "Light Manufacturing Environment",
    editorialReason: "Represents Power Inn's light-manufacturing and technical-industrial side, where power, clear height, yard, and loading questions matter more than office image.",
    representativeThemes: ["Light manufacturing", "Power", "Yard", "Highway 50 industrial"],
    businessFit: ["light manufacturing", "assembly", "technical industrial", "equipment service"],
    relatedDistrictPaths: [districts.westSacramento.path, districts.ranchoCordova.path, districts.natomas.path],
    nearbyBuildingPaths: [
      buildingPath("sacramento", "5711 Florin Perkins Rd"),
      buildingPath("sacramento", "4949 Florin Perkins Rd"),
      buildingPath("rancho-cordova", "11353 Pyrites Way"),
    ],
    comparisonBuildingPaths: [
      buildingPath("west-sacramento", "3100 Ramco St"),
      buildingPath("rancho-cordova", "11201 Sun Center Dr"),
      buildingPath("sacramento", "5711 Florin Perkins Rd"),
    ],
    brief: {
      buildingSummary: "8583 Elder Creek Rd is a Power Inn industrial property that helps explain Sacramento light-manufacturing and technical-service environments. It is most useful for businesses comparing buildings where grade-level loading, power, clear height, yard context, and Highway 50 access may be more important than customer-facing image.",
      buildingImportance: "This property matters because it gives Sacramento's industrial/flex model a production-oriented reference point. Power Inn is not just warehouse geography; it can also support users whose daily work involves assembly, equipment, service, or technical operations. The source record provides several useful property signals, while permitted use and buildout still require validation.",
      quickFacts: [
        { label: "Primary ecosystem", value: "Industrial & flex" },
        { label: "Representative role", value: "Light manufacturing environment" },
        { label: "District", value: "Power Inn Industrial" },
        { label: "Source-supported year", value: "1985, per Colliers source export" },
        { label: "Loading context", value: "Colliers source identifies one grade-level door" },
        { label: "Clear-height context", value: "Colliers source identifies approximately 27-foot clear height" },
        { label: "Power context", value: "Colliers source identifies 800A, 277/480v, 3-phase, 4-wire power and stepdown transformer" },
        { label: "Yard and parking context", value: "Colliers source identifies surface parking and fenced yard; rights and allocation require validation" },
      ],
      idealFor: [
        "Light manufacturers, cabinet shops, furniture makers, and equipment-service users that need more technical utility than a basic storage suite.",
        "Businesses that evaluate buildings by power, loading, clear height, and yard context before office image.",
        "Production-adjacent teams comparing Power Inn against West Sacramento distribution or Rancho Cordova flex alternatives.",
        "Operators that need Highway 50 access for employees, suppliers, service territories, or outbound movement.",
      ],
      mayNotFit: [
        "Pure office, showroom, or client-facing users that need polished arrival and customer visibility.",
        "Large distributors that need deeper dock loading, trailer parking, and a larger logistics platform.",
        "Food, hazardous-material, or specialized manufacturing users without direct confirmation of permits, ventilation, utilities, and landlord approvals.",
      ],
      buildingExperience: "The experience is practical and technical. A user should walk the property with an operational checklist: where deliveries arrive, how equipment moves, where vehicles park, how power is delivered, and whether the existing shell can support the intended use. The building is best understood as an operating environment, not a branding decision.",
      districtContext: "8583 Elder Creek Rd sits in Power Inn Industrial, one of Sacramento's clearest industrial corridors for service, warehouse, and light-production users. It differs from West Sacramento's larger distribution examples and from Rancho Cordova's office/flex pattern. Users comparing it should decide whether Highway 50 access and production utility matter more than larger logistics scale.",
      advantages: [
        "Source-backed power, clear-height, grade-level loading, parking, fenced-yard, and fire-sprinkler context make it useful for operational validation.",
        "Represents light-manufacturing and technical-service uses that are not well explained by office or warehouse-only examples.",
        "Power Inn location supports Highway 50 access for south/east Sacramento service territories and supplier movement.",
        "Useful benchmark for deciding whether a business needs production-capable industrial space rather than small-bay storage.",
      ],
      tradeoffs: [
        "Production potential depends on permitted use, ventilation, power distribution, and buildout details that must be confirmed.",
        "The district is more operational than customer-facing, with fewer walkable amenities than office or showroom settings.",
        "A single-building technical fit can be hard to compare without current suite condition and utility verification.",
        "Larger distribution users may need more dock, trailer, and warehouse capacity than this environment represents.",
      ],
      operationalProfile: [
        { label: "Loading", summary: "The source identifies grade-level loading, which can be relevant to production, equipment, or service operations. Confirm door dimensions and access pattern." },
        { label: "Power and infrastructure", summary: "The source identifies substantial electrical service. Users should verify delivery to the suite, panel capacity, equipment loads, ventilation, and code constraints." },
        { label: "Yard and vehicles", summary: "The source identifies fenced yard and surface parking. Confirm yard rights, security, outdoor storage approval, and vehicle circulation." },
        { label: "Production fit", summary: "The building can teach light-manufacturing evaluation, but permitted use and process-specific requirements must be validated." },
      ],
      environmentExplanation: {
        whyItExists: "Light-manufacturing environments exist for businesses that need production, assembly, equipment, and storage capability without necessarily occupying a large distribution warehouse.",
        whyChooseThisEnvironment: "Choose this environment over small-bay service when power, clear height, and production utility matter; choose it over large distribution when manufacturing or technical work matters more than trailer throughput.",
        representativeValue: "8583 Elder Creek Rd is the Power Inn calibration example for production-oriented industrial fit.",
      },
      nearbyAlternatives: [
        { label: "5711 Florin Perkins Rd", url: buildingPath("sacramento", "5711 Florin Perkins Rd"), reason: "Prefer this when a smaller warehouse-suite service environment fits better than a technical light-manufacturing property." },
        { label: "3100 Ramco St", url: buildingPath("west-sacramento", "3100 Ramco St"), reason: "Prefer this when large-format distribution, trailer movement, and warehouse scale matter more than production utility." },
        { label: "11201 Sun Center Dr", url: buildingPath("rancho-cordova", "11201 Sun Center Dr"), reason: "Prefer this when contractor yard, vehicle staging, and office-industrial mixed use are the main search drivers." },
        { label: "11353 Pyrites Way", url: buildingPath("rancho-cordova", "11353 Pyrites Way"), reason: "Prefer this when a compact suite and smaller-service or maker format may fit better." },
      ],
      relatedDistricts: [
        { districtId: "west-sacramento-industrial", reason: "Compare West Sacramento for larger distribution and I-80/I-5 industrial access." },
        { districtId: "rancho-cordova-commercial-core", reason: "Compare Rancho Cordova when office/flex, contractor service, and Highway 50 access overlap." },
        { districtId: "natomas", reason: "Compare Natomas when airport access and north Sacramento service coverage matter more." },
      ],
      validationNotes: [
        "Confirm permitted use for the exact production, assembly, or technical operation.",
        "Verify power capacity, panel delivery, and equipment compatibility.",
        "Confirm ventilation, exhaust, HVAC, plumbing, and fire-safety requirements.",
        "Validate grade-level loading dimensions, access, and truck circulation.",
        "Confirm fenced-yard rights, outdoor storage approval, parking allocation, and security responsibilities.",
      ],
      relatedInsights: [compareSpaces, tenantImprovements, cityInsight],
      representativeCompanies: [
        "Relevant company categories include light manufacturers, cabinet shops, furniture makers, equipment-service companies, and technical industrial users.",
        "These categories describe operating-model fit and do not identify current tenants.",
      ],
      ecosystemSubtypes: ["light_manufacturing", "manufacturing", "contractor_service"],
      representativeRole: "light_manufacturing_environment",
      businessActivities: ["assembly", "light_manufacturing", "receiving", "shipping", "equipment_storage"],
      businessArchetypes: ["light_manufacturer", "cabinet_shop", "furniture_maker", "equipment_service_company"],
      operationalCharacteristics: ["grade_level_loading", "high_clearance", "high_power", "surface_parking", "secured_yard", "manufacturing_compatible"],
      fitSummary: "Production-oriented fit depends on power, loading, yard, clear height, and use approval.",
      confidence: "verified_property_fact",
      sourceNotes: [`${sourceDocs.colliers}: source row for 8583 Elder Creek Rd identifies grade-level loading, clear height, power, surface parking, fenced yard, and fire sprinkler details.`],
    },
  }),
  record({
    name: "11201 Sun Center Dr",
    address: "11201 Sun Center Dr",
    city: "Rancho Cordova",
    citySlug: "rancho-cordova",
    districtKey: "ranchoCordova",
    buildingType: "Contractor/service industrial",
    primarySpaceType: "industrial",
    editorialRole: "Contractor / Service Cluster",
    editorialReason: "Represents the Highway 50 contractor/service environment where mixed office-industrial zoning, yard area, and vehicle staging can matter as much as interior warehouse area.",
    representativeThemes: ["Contractor service", "Yard", "Vehicle staging", "Highway 50"],
    businessFit: ["contractor operations", "service dispatch", "equipment service", "building services"],
    relatedDistrictPaths: [districts.powerInn.path, districts.westSacramento.path, districts.natomas.path],
    nearbyBuildingPaths: [
      buildingPath("rancho-cordova", "11353 Pyrites Way"),
      buildingPath("rancho-cordova", "11300 Trade Center Dr"),
      buildingPath("sacramento", "8583 Elder Creek Rd"),
    ],
    comparisonBuildingPaths: [
      buildingPath("sacramento", "4205-s-market-ct"),
      buildingPath("sacramento", "8583 Elder Creek Rd"),
      buildingPath("west-sacramento", "3100 Ramco St"),
    ],
    brief: {
      buildingSummary: "11201 Sun Center Dr is a Rancho Cordova contractor-service industrial property for users that need office support, vehicle staging, yard utility, and Highway 50 access. It helps explain a Sacramento operating model where the exterior site, parking, and service-dispatch pattern can matter as much as the building interior.",
      buildingImportance: "This property matters because it prevents Rancho Cordova from being understood only as office/flex. The source record identifies office-industrial mixed-use zoning, office area, parking, and fenced yard context, making it a strong calibration example for contractors and service businesses whose real estate decision starts with crews, vehicles, equipment, and daily dispatch.",
      quickFacts: [
        { label: "Primary ecosystem", value: "Industrial & flex" },
        { label: "Representative role", value: "Contractor / service cluster" },
        { label: "District", value: "Rancho Cordova Commercial Core" },
        { label: "Source-supported size", value: "CBRE source identifies approximately 13,500 total building square feet" },
        { label: "Office context", value: "CBRE source identifies approximately 1,290 square feet of office" },
        { label: "Zoning context", value: "CBRE source identifies OIMU, Office/Industrial Mixed Use, City of Rancho Cordova" },
        { label: "Yard context", value: "CBRE source identifies concrete parking and yard plus fenced yard; rights must be verified" },
        { label: "Access context", value: "Source describes location less than one mile south of Highway 50 at Sunrise Boulevard" },
      ],
      idealFor: [
        "General contractors, electricians, HVAC companies, plumbing companies, and equipment-service users that need yard-oriented service operations.",
        "Businesses that dispatch crews or service vehicles and need a practical base near Highway 50.",
        "Operators that need some office function but are primarily solving storage, parking, yard, and field-service logistics.",
        "Companies comparing Rancho Cordova for suburban workforce access and lower-friction industrial utility.",
      ],
      mayNotFit: [
        "Warehouse distributors that need dock-heavy logistics, high clear height, and trailer throughput as the main decision factor.",
        "Office-heavy flex users that prioritize employee amenities, customer presentation, or a polished business-park setting.",
        "Businesses whose yard, storage, vehicle, or outdoor operations are not allowed by zoning, lease terms, or landlord approval.",
      ],
      buildingExperience: "The experience should be evaluated from the yard inward. A tour should answer where crews arrive, where vehicles stage, how materials are secured, how the office supports dispatch and administration, and whether the site rules match the company's daily operating rhythm.",
      districtContext: "11201 Sun Center Dr sits in Rancho Cordova Commercial Core, where Highway 50 access supports office, flex, contractor-service, and operations users. It is a stronger contractor/service example than the district's office-oriented buildings. Compare Power Inn for deeper industrial identity, West Sacramento for larger warehouse/distribution, and Natomas for airport and north Sacramento access.",
      advantages: [
        "Source-backed yard, parking, office, zoning, and Highway 50 context make it useful for contractor-service due diligence.",
        "Shows how exterior site utility can drive fit for trades and service companies.",
        "Rancho Cordova location can serve eastern Sacramento suburbs without moving into a purely warehouse district.",
        "Clear contrast to both small-bay suites and large distribution buildings.",
      ],
      tradeoffs: [
        "Yard-oriented utility may be more important than customer-facing image or walkable amenities.",
        "Outdoor storage, vehicle staging, security, and material handling require specific approval and lease validation.",
        "The office component may be too limited for administrative-heavy users.",
        "Distribution or production users may need different loading, clear height, or power conditions.",
      ],
      operationalProfile: [
        { label: "Yard and vehicles", summary: "The source identifies concrete parking and yard plus fenced yard. Confirm yard rights, vehicle staging, overnight rules, and security." },
        { label: "Office and dispatch", summary: "The source identifies an office component, making the property useful for administration-plus-field-operations questions." },
        { label: "Use and zoning", summary: "Office/industrial mixed-use zoning is source-supported, but each business still needs permitted-use and lease approval." },
        { label: "Access", summary: "Highway 50 and Sunrise Boulevard proximity help frame service-territory coverage and employee access." },
      ],
      environmentExplanation: {
        whyItExists: "Contractor/service environments exist because trades and field-service businesses need office administration, equipment storage, service vehicles, materials, and dispatch to work together.",
        whyChooseThisEnvironment: "Choose this environment over a warehouse when vehicles and yard utility matter more than dock throughput; choose it over office/flex when the business needs a true operating base.",
        representativeValue: "11201 Sun Center Dr is the Sacramento calibration example for yard-oriented contractor/service operations.",
      },
      nearbyAlternatives: [
        { label: "8583 Elder Creek Rd", url: buildingPath("sacramento", "8583 Elder Creek Rd"), reason: "Prefer this when light manufacturing, power, and technical industrial requirements matter more than yard-oriented service dispatch." },
        { label: "11353 Pyrites Way", url: buildingPath("rancho-cordova", "11353 Pyrites Way"), reason: "Prefer this when a smaller industrial suite can handle the operation without a dedicated yard-oriented site." },
        { label: "3100 Ramco St", url: buildingPath("west-sacramento", "3100 Ramco St"), reason: "Prefer this when distribution scale, dock loading, and trailer movement matter more than contractor-service utility." },
        { label: "5711 Florin Perkins Rd", url: buildingPath("sacramento", "5711 Florin Perkins Rd"), reason: "Prefer this when compact service suites in Power Inn fit better than a dedicated Highway 50 service property." },
      ],
      relatedDistricts: [
        { districtId: "power-inn-industrial", reason: "Compare Power Inn for a stronger industrial corridor and small-bay service alternatives." },
        { districtId: "west-sacramento-industrial", reason: "Compare West Sacramento for distribution scale and I-80/I-5 warehouse access." },
        { districtId: "natomas", reason: "Compare Natomas when north Sacramento, airport, and I-5/I-80 access matter more." },
      ],
      validationNotes: [
        "Confirm permitted use for the exact contractor, service, storage, or field-operation activity.",
        "Verify yard rights, outdoor storage approval, fencing, lighting, and security responsibilities.",
        "Confirm parking allocation for employees, service vehicles, and visitor or vendor access.",
        "Validate office and warehouse split against dispatch, administration, and equipment needs.",
        "Confirm loading, delivery, and truck-circulation limits for daily operations.",
      ],
      relatedInsights: [compareSpaces, tenantImprovements, cityInsight],
      representativeCompanies: [
        "Relevant company categories include contractors, trade businesses, equipment-service companies, and building-services operators.",
        "Archetype fit describes operating needs, not current tenancy.",
      ],
      ecosystemSubtypes: ["contractor_service", "contractor_yard", "flex"],
      representativeRole: "contractor_service_cluster",
      businessActivities: ["service_dispatch", "equipment_storage", "vehicle_storage", "receiving", "shipping"],
      businessArchetypes: ["general_contractor", "electrician", "hvac_company", "plumbing_company", "equipment_service_company"],
      operationalCharacteristics: ["office_warehouse_mix", "secured_yard", "contractor_yard", "service_vehicle_parking", "surface_parking", "freeway_access", "suburban_access"],
      fitSummary: "Contractor/service fit depends on yard, vehicle staging, office support, and permitted use.",
      confidence: "verified_property_fact",
      sourceNotes: [`${sourceDocs.cbre}: source row for 11201 Sun Center Dr identifies building size, office area, OIMU zoning, auto stalls, concrete parking and yard, fenced yard, and Highway 50 access context.`],
    },
  }),
  record({
    name: "2928 Ramco St",
    address: "2928 Ramco St",
    city: "West Sacramento",
    citySlug: "west-sacramento",
    districtKey: "westSacramento",
    buildingType: "Warehouse / distribution",
    primarySpaceType: "warehouse",
    editorialRole: "Warehouse / Distribution Environment",
    editorialReason: "Adds a West Sacramento distribution-center example that helps users compare warehouse function with smaller service-industrial and contractor-yard properties.",
    representativeThemes: ["Warehouse", "Distribution", "Loading", "West Sacramento"],
    businessFit: ["warehouse", "distribution", "service distribution", "regional operations"],
    relatedDistrictPaths: [districts.powerInn.path, districts.natomas.path, districts.ranchoCordova.path],
    nearbyBuildingPaths: [
      buildingPath("west-sacramento", "3100 Ramco St"),
      buildingPath("west-sacramento", "3380 Industrial Blvd"),
      buildingPath("sacramento", "1329 N Market Blvd"),
    ],
    comparisonBuildingPaths: [
      buildingPath("west-sacramento", "3100 Ramco St"),
      buildingPath("sacramento", "1329 N Market Blvd"),
      buildingPath("rancho-cordova", "11201 Sun Center Dr"),
    ],
    brief: {
      buildingSummary: "2928 Ramco St is a West Sacramento warehouse and distribution example for businesses comparing dock and grade-level loading, clear height, and light-industrial utility. It is useful for users that need goods movement and storage capacity but may not require the full scale represented by the largest Ramco Street logistics buildings.",
      buildingImportance: "This property matters because it provides a middle warehouse/distribution reference inside West Sacramento. It helps users distinguish distribution-center requirements from small-bay service space, showroom/flex, or contractor-yard environments. The source record supports several core logistics characteristics, but truck movement, suite condition, and operating rules still need validation.",
      quickFacts: [
        { label: "Primary ecosystem", value: "Industrial & flex" },
        { label: "Representative role", value: "Warehouse / distribution environment" },
        { label: "District", value: "West Sacramento Industrial" },
        { label: "Source-supported form", value: "CBRE source describes a distribution-center environment" },
        { label: "Loading context", value: "CBRE source identifies dock-high and grade-level loading" },
        { label: "Clear-height context", value: "CBRE source identifies approximately 28-foot minimum clear height" },
        { label: "Zoning context", value: "CBRE source identifies M-1 / Light Industrial zoning, per City of West Sacramento" },
        { label: "Systems context", value: "CBRE source identifies ESFR fire sprinklers" },
      ],
      idealFor: [
        "Warehouse, service-distribution, and regional operations users that need loading and storage without necessarily occupying a very large logistics platform.",
        "Businesses comparing West Sacramento for I-80/I-5 access and practical industrial utility near the Sacramento core.",
        "Distributors and wholesalers that need to pressure-test dock, grade-level, clear-height, and sprinkler requirements.",
        "Operators that want a distribution-center comparison before deciding whether small-bay or large-scale distribution is the better model.",
      ],
      mayNotFit: [
        "Contractors whose primary need is yard, vehicle staging, and field-service dispatch rather than warehouse throughput.",
        "Showroom or customer-facing flex users that need visitor presentation and office/showroom balance.",
        "Users with specialized manufacturing, food, or hazardous-material requirements that need deeper infrastructure validation.",
      ],
      buildingExperience: "The experience is warehouse-oriented. Users should evaluate how inventory arrives, how it is staged, how trucks circulate, and whether the building's door mix and clear height support the actual movement of goods. Office image is secondary to whether the space reduces friction in receiving, storage, and shipping.",
      districtContext: "2928 Ramco St is part of West Sacramento Industrial, where warehouse, service-industrial, and distribution users can remain close to the Sacramento core while using I-80 and I-5 access. It should be compared with 3100 Ramco for larger distribution scale, 3380 Industrial for showroom/flex needs, and Power Inn for Highway 50 industrial access.",
      advantages: [
        "Source-backed dock-high, grade-level, clear-height, sprinkler, and light-industrial zoning context support warehouse due diligence.",
        "Gives West Sacramento a distribution-center example distinct from contractor-service and showroom/flex properties.",
        "Can help users decide whether they need warehouse function without moving to the largest logistics option.",
        "Strong comparison point for businesses evaluating goods movement near the Sacramento core.",
      ],
      tradeoffs: [
        "Distribution-center function depends on exact door access, truck circulation, and parking configuration.",
        "Customer-facing image and walkability are limited compared with flex or office districts.",
        "Light-industrial zoning does not by itself confirm every intended use.",
        "Businesses with yard or service-vehicle needs may need a contractor/service property instead.",
      ],
      operationalProfile: [
        { label: "Loading", summary: "The source identifies dock-high and grade-level loading, making loading configuration a central comparison point." },
        { label: "Warehouse form", summary: "Clear-height and sprinkler context support warehouse/distribution evaluation, but racking and storage plans need validation." },
        { label: "Use approval", summary: "Light-industrial zoning is identified in the source, but permitted use and lease restrictions remain separate checks." },
        { label: "Regional access", summary: "West Sacramento location supports users comparing central regional access with Power Inn, Natomas, and Rancho Cordova." },
      ],
      environmentExplanation: {
        whyItExists: "Warehouse/distribution environments exist for businesses that need inventory movement, loading, storage, and regional access to work predictably.",
        whyChooseThisEnvironment: "Choose this environment over small-bay service when receiving and shipping matter more than compact suite size; choose it over very large distribution when the operation needs warehouse function without maximum logistics scale.",
        representativeValue: "2928 Ramco St calibrates the middle distribution-center decision inside West Sacramento.",
      },
      nearbyAlternatives: [
        { label: "3100 Ramco St", url: buildingPath("west-sacramento", "3100 Ramco St"), reason: "Prefer this when larger-format logistics scale, trailer parking, and more extensive warehouse infrastructure are the main needs." },
        { label: "3380 Industrial Blvd", url: buildingPath("west-sacramento", "3380 Industrial Blvd"), reason: "Prefer this when showroom, office/warehouse balance, or customer-facing flex matters more than distribution-center function." },
        { label: "1329 N Market Blvd", url: buildingPath("sacramento", "1329 N Market Blvd"), reason: "Prefer this when north Sacramento last-mile access and a smaller warehouse base may fit the service territory better." },
        { label: "11201 Sun Center Dr", url: buildingPath("rancho-cordova", "11201 Sun Center Dr"), reason: "Prefer this when contractor-service yard utility and vehicle staging matter more than warehouse throughput." },
      ],
      relatedDistricts: [
        { districtId: "power-inn-industrial", reason: "Compare Power Inn for Highway 50 industrial utility and smaller service or production formats." },
        { districtId: "natomas", reason: "Compare Natomas for north Sacramento and airport-access warehouse or service coverage." },
        { districtId: "rancho-cordova-commercial-core", reason: "Compare Rancho Cordova for more office/flex and contractor-service orientation." },
      ],
      validationNotes: [
        "Confirm dock-high and grade-level door access for the specific suite.",
        "Verify truck circulation, parking, and delivery-hour rules.",
        "Confirm clear height, sprinkler suitability, and racking assumptions.",
        "Validate permitted use under zoning, lease, and landlord requirements.",
        "Confirm whether office area, restroom, and employee-support needs match the operation.",
      ],
      relatedInsights: [compareSpaces, tenantImprovements, cityInsight],
      representativeCompanies: [
        "Relevant company categories include distributors, wholesalers, importers, service-distribution users, and regional operations teams.",
        "These categories describe likely evaluation needs and do not identify current tenants.",
      ],
      ecosystemSubtypes: ["warehouse", "distribution"],
      representativeRole: "warehouse_distribution_environment",
      businessActivities: ["storage", "inventory_management", "receiving", "shipping", "distribution"],
      businessArchetypes: ["distributor", "wholesaler", "importer", "ecommerce_fulfillment_business"],
      operationalCharacteristics: ["dock_high_loading", "grade_level_loading", "high_clearance", "large_floorplates", "enhanced_security", "regional_distribution_access", "industrial_identity"],
      fitSummary: "Warehouse/distribution fit depends on loading, storage, truck movement, and use approval.",
      confidence: "verified_property_fact",
      sourceNotes: [`${sourceDocs.cbre}: source row for 2928 Ramco St identifies distribution-center context, dock-high and grade-level loading, clear height, ESFR sprinklers, and light-industrial zoning.`],
    },
  }),
  record({
    name: "1329 N Market Blvd",
    address: "1329 N Market Blvd",
    city: "Sacramento",
    citySlug: "sacramento",
    districtKey: "natomas",
    buildingType: "Warehouse / last-mile logistics",
    primarySpaceType: "industrial",
    editorialRole: "Last-Mile Logistics Environment",
    editorialReason: "Shows a north Sacramento warehouse environment where I-5 and I-80 access can matter more than office image for local delivery, service distribution, or inventory movement.",
    representativeThemes: ["Last mile", "Warehouse", "I-5 access", "I-80 access"],
    businessFit: ["last-mile logistics", "warehouse", "service distribution", "inventory operations"],
    relatedDistrictPaths: [districts.westSacramento.path, districts.powerInn.path, districts.ranchoCordova.path],
    nearbyBuildingPaths: [
      buildingPath("sacramento", "1060 National Dr"),
      buildingPath("sacramento", "1235 Blumenfeld Dr"),
      buildingPath("west-sacramento", "2928 Ramco St"),
    ],
    comparisonBuildingPaths: [
      buildingPath("west-sacramento", "2928 Ramco St"),
      buildingPath("west-sacramento", "3100 Ramco St"),
      buildingPath("sacramento", "5711 Florin Perkins Rd"),
    ],
    brief: {
      buildingSummary: "1329 N Market Blvd is a Natomas warehouse example for businesses comparing north Sacramento last-mile, service-distribution, and inventory environments. It is most useful for users that value I-5 and I-80 access and need to evaluate dock access, grade-level loading, clear height, and electrical service at a smaller warehouse scale.",
      buildingImportance: "This property matters because it gives Natomas an industrial/flex example that is not just suburban office or airport-adjacent flex. It helps users compare north Sacramento access against West Sacramento distribution and Power Inn industrial utility. The source record supports loading, clear-height, and electrical context, but daily delivery patterns still require validation.",
      quickFacts: [
        { label: "Primary ecosystem", value: "Industrial & flex" },
        { label: "Representative role", value: "Last-mile logistics environment" },
        { label: "District", value: "Natomas" },
        { label: "Source-supported suite scale", value: "Colliers source identifies an approximately 5,196 square foot suite" },
        { label: "Loading context", value: "Colliers source identifies one dock-high door and one grade-level door" },
        { label: "Clear-height context", value: "Colliers source identifies approximately 27-foot clear height" },
        { label: "Power context", value: "Colliers source identifies 277/480v electrical service to the building" },
        { label: "Access context", value: "Colliers source describes easy access to Interstates 5 and 80" },
      ],
      idealFor: [
        "Service-distribution, inventory, and local delivery users that need north Sacramento access without a large warehouse footprint.",
        "Distributors, wholesalers, and e-commerce fulfillment users comparing smaller last-mile environments against larger West Sacramento facilities.",
        "Service companies that need receiving, shipping, and inventory functions near I-5 and I-80.",
        "Businesses whose customer or delivery geography is stronger north of downtown than along Highway 50.",
      ],
      mayNotFit: [
        "Large distribution users that need substantial trailer parking, multiple docks, or a deeper logistics platform.",
        "Contractors that need secure yard, fleet staging, or outdoor equipment storage as the primary requirement.",
        "Customer-facing or showroom businesses that need visibility, product display, or a more polished visitor environment.",
      ],
      buildingExperience: "The experience is compact and logistics-focused. Users should evaluate how quickly goods move in and out, whether the door mix matches delivery vehicles, how inventory is staged, and whether the smaller warehouse scale supports the business without constraining growth.",
      districtContext: "1329 N Market Blvd sits in Natomas, where freeway and airport access shape the industrial/flex decision. It is a useful contrast to West Sacramento's larger warehouse buildings, Power Inn's production and service-industrial corridor, and Rancho Cordova's office/flex and contractor-service environments.",
      advantages: [
        "Source-backed dock-high, grade-level, clear-height, electrical, and I-5/I-80 access details support last-mile evaluation.",
        "Provides a north Sacramento logistics example distinct from larger West Sacramento distribution facilities.",
        "Smaller warehouse scale can fit businesses that do not need a large-format logistics building.",
        "Useful for comparing local delivery and service-territory coverage around Natomas.",
      ],
      tradeoffs: [
        "The smaller scale may limit expansion, storage density, or trailer-heavy operations.",
        "Last-mile utility depends on actual vehicle routes, loading access, and parking allocation.",
        "Customer-facing image is limited compared with flex or showroom environments.",
        "Warehouse characteristics still need suite-level validation before shortlisting.",
      ],
      operationalProfile: [
        { label: "Loading", summary: "The source identifies one dock-high door and one grade-level door. Confirm dimensions, access, shared use, and delivery timing." },
        { label: "Warehouse scale", summary: "The source-supported suite size makes this a smaller logistics example rather than a large distribution platform." },
        { label: "Power and clear height", summary: "Clear height and electrical service are source-supported context, but tenant-specific equipment and storage plans still require validation." },
        { label: "Location reach", summary: "I-5 and I-80 access are central to the property's representative value for north Sacramento distribution." },
      ],
      environmentExplanation: {
        whyItExists: "Last-mile logistics environments exist because businesses need smaller warehouse bases that can reach local customers, routes, and service territories efficiently.",
        whyChooseThisEnvironment: "Choose this environment over West Sacramento scale when north Sacramento access and a smaller warehouse footprint matter more; choose it over small-bay service when dock and grade-level loading are more important.",
        representativeValue: "1329 N Market Blvd calibrates the north Sacramento last-mile and small-warehouse decision.",
      },
      nearbyAlternatives: [
        { label: "2928 Ramco St", url: buildingPath("west-sacramento", "2928 Ramco St"), reason: "Prefer this when West Sacramento distribution-center function matters more than north Sacramento last-mile access." },
        { label: "3100 Ramco St", url: buildingPath("west-sacramento", "3100 Ramco St"), reason: "Prefer this when larger distribution scale, trailer movement, and extensive warehouse infrastructure are required." },
        { label: "5711 Florin Perkins Rd", url: buildingPath("sacramento", "5711 Florin Perkins Rd"), reason: "Prefer this when a smaller service-industrial suite in Power Inn fits better than a warehouse/logistics environment." },
        { label: "11201 Sun Center Dr", url: buildingPath("rancho-cordova", "11201 Sun Center Dr"), reason: "Prefer this when contractor-service yard and vehicle-staging needs outrank warehouse loading." },
      ],
      relatedDistricts: [
        { districtId: "west-sacramento-industrial", reason: "Compare West Sacramento for larger distribution and I-80/I-5 warehouse depth." },
        { districtId: "power-inn-industrial", reason: "Compare Power Inn for Highway 50 industrial, service, and light-production environments." },
        { districtId: "rancho-cordova-commercial-core", reason: "Compare Rancho Cordova for office/flex and contractor-service alternatives." },
      ],
      validationNotes: [
        "Confirm whether the dock-high and grade-level doors are dedicated, shared, or constrained.",
        "Verify truck access, delivery windows, and vehicle parking for the route pattern.",
        "Confirm clear height, electrical capacity, and storage-racking assumptions.",
        "Validate permitted use for shipping, distribution, inventory, or service dispatch.",
        "Confirm expansion options if inventory or route volume grows.",
      ],
      relatedInsights: [compareSpaces, cityInsight, tenantImprovements],
      representativeCompanies: [
        "Relevant company categories include distributors, wholesalers, e-commerce fulfillment users, and service-distribution companies.",
        "These categories are archetype guidance and do not identify current tenants.",
      ],
      ecosystemSubtypes: ["warehouse", "last_mile_logistics", "distribution"],
      representativeRole: "last_mile_logistics_environment",
      businessActivities: ["receiving", "shipping", "distribution", "inventory_management", "service_dispatch"],
      businessArchetypes: ["distributor", "wholesaler", "ecommerce_fulfillment_business", "equipment_service_company"],
      operationalCharacteristics: ["dock_high_loading", "grade_level_loading", "high_clearance", "delivery_access", "last_mile_access", "freeway_access", "regional_distribution_access"],
      fitSummary: "Last-mile fit depends on route geography, door access, warehouse scale, and vehicle movement.",
      confidence: "verified_property_fact",
      sourceNotes: [`${sourceDocs.colliers}: source row for 1329 N Market Blvd identifies suite size, dock-high and grade-level doors, clear height, electrical service, and I-5/I-80 access.`],
    },
  }),
  record({
    name: "3380 Industrial Blvd",
    address: "3380 Industrial Blvd",
    city: "West Sacramento",
    citySlug: "west-sacramento",
    districtKey: "westSacramento",
    buildingType: "Showroom flex / office-warehouse",
    primarySpaceType: "industrial",
    editorialRole: "Showroom Flex Environment",
    editorialReason: "Shows West Sacramento's smaller office-and-warehouse flex inventory, a different operating model from large-format distribution centers on Ramco Street.",
    representativeThemes: ["Showroom flex", "Office/warehouse", "Grade-level loading", "West Sacramento"],
    businessFit: ["showroom flex", "office/warehouse", "service operations", "product display"],
    relatedDistrictPaths: [districts.powerInn.path, districts.ranchoCordova.path, districts.natomas.path],
    nearbyBuildingPaths: [
      buildingPath("west-sacramento", "2928 Ramco St"),
      buildingPath("west-sacramento", "3100 Ramco St"),
      buildingPath("sacramento", "5711 Florin Perkins Rd"),
    ],
    comparisonBuildingPaths: [
      buildingPath("west-sacramento", "2928 Ramco St"),
      buildingPath("rancho-cordova", "11353 Pyrites Way"),
      buildingPath("rancho-cordova", "11201 Sun Center Dr"),
    ],
    brief: {
      buildingSummary: "3380 Industrial Blvd is a West Sacramento showroom/flex and office-warehouse example for businesses that need operational space with some customer or administrative function. It helps distinguish smaller flex environments from the larger warehouse and distribution buildings that also define the West Sacramento industrial market.",
      buildingImportance: "This property matters because industrial/flex searches are not all warehouse searches. The source record identifies office/warehouse context and grade-level loading possibility, making 3380 Industrial Blvd useful for users whose decision blends storage, service, administration, and occasional customer interaction. It is a contrast to both Ramco Street logistics and Power Inn small-bay service space.",
      quickFacts: [
        { label: "Primary ecosystem", value: "Industrial & flex" },
        { label: "Representative role", value: "Showroom flex environment" },
        { label: "District", value: "West Sacramento Industrial" },
        { label: "Source-supported use context", value: "CBRE source identifies industrial space in West Sacramento" },
        { label: "Office/warehouse context", value: "CBRE source identifies office-and-warehouse suite context" },
        { label: "Loading context", value: "CBRE source identifies grade-level loading in suite context; exact access requires validation" },
        { label: "Customer presence", value: "Showroom/flex role is editorially supported by office/warehouse configuration, not a tenant claim" },
      ],
      idealFor: [
        "Service, equipment, product, or trade businesses that need office, warehouse, and limited customer-facing function in one environment.",
        "Showroom-oriented users that need storage or receiving in addition to product presentation or appointments.",
        "Businesses comparing West Sacramento for operational access but needing more office or customer presence than a warehouse-only building.",
        "Operators that want a smaller flex format near the Sacramento core rather than a large distribution facility.",
      ],
      mayNotFit: [
        "Large distribution users that require extensive dock loading, trailer parking, and clear-height-driven storage efficiency.",
        "Pure office users that need walkable amenities, transit, and a polished client-arrival sequence.",
        "Manufacturing or food-production users without confirmation of power, ventilation, plumbing, and permitted use.",
      ],
      buildingExperience: "The experience is hybrid. A tour should evaluate where customers or vendors arrive, how the office and warehouse portions connect, whether loading interrupts customer-facing use, and whether the suite can support both administrative work and operational storage without compromising either.",
      districtContext: "3380 Industrial Blvd sits in West Sacramento Industrial but represents a more flexible operating model than the larger Ramco Street distribution properties. Compare Rancho Cordova for suburban office/flex, Power Inn for stronger industrial identity and production utility, and Natomas for north Sacramento access.",
      advantages: [
        "Shows an office/warehouse and showroom/flex model inside an otherwise warehouse-oriented district.",
        "Grade-level loading context can support service, storage, or product movement if confirmed for the suite.",
        "West Sacramento location gives users operational access near the Sacramento core.",
        "Useful contrast for businesses deciding whether customer-facing flex is more appropriate than distribution space.",
      ],
      tradeoffs: [
        "The office, warehouse, and showroom balance can vary sharply by suite.",
        "Heavy warehouse users may find the flex format inefficient compared with distribution-center space.",
        "Customer-facing value depends on signage, parking, access, and the actual suite layout.",
        "Operational capacity still depends on loading, power, and permitted-use validation.",
      ],
      operationalProfile: [
        { label: "Office/warehouse balance", summary: "The source identifies office/warehouse context, making suite layout and office percentage central diligence items." },
        { label: "Customer presence", summary: "Showroom/flex suitability should be validated through visibility, customer parking, signage, and arrival path." },
        { label: "Loading", summary: "Grade-level loading is source-supported in suite context, but access, dimensions, and sharing rules need confirmation." },
        { label: "Operating scale", summary: "This environment teaches smaller flex utility rather than large-format distribution." },
      ],
      environmentExplanation: {
        whyItExists: "Showroom/flex environments exist because some businesses need office, customer presentation, storage, and light operations in proportions that office or warehouse buildings alone do not support.",
        whyChooseThisEnvironment: "Choose this environment over warehouse/distribution when customers, vendors, office use, or product presentation matter; choose it over office when loading and storage remain part of the operation.",
        representativeValue: "3380 Industrial Blvd calibrates West Sacramento's customer-adjacent flex decision.",
      },
      nearbyAlternatives: [
        { label: "2928 Ramco St", url: buildingPath("west-sacramento", "2928 Ramco St"), reason: "Prefer this when warehouse/distribution function matters more than office/showroom balance." },
        { label: "11353 Pyrites Way", url: buildingPath("rancho-cordova", "11353 Pyrites Way"), reason: "Prefer this when a compact small-bay service or maker suite fits better than showroom/flex." },
        { label: "11201 Sun Center Dr", url: buildingPath("rancho-cordova", "11201 Sun Center Dr"), reason: "Prefer this when yard, vehicle staging, and contractor-service operations are more important." },
        { label: "5711 Florin Perkins Rd", url: buildingPath("sacramento", "5711 Florin Perkins Rd"), reason: "Prefer this when small warehouse-suite service utility in Power Inn matters more than customer presentation." },
      ],
      relatedDistricts: [
        { districtId: "power-inn-industrial", reason: "Compare Power Inn for stronger industrial utility and less showroom-oriented service space." },
        { districtId: "rancho-cordova-commercial-core", reason: "Compare Rancho Cordova for suburban office/flex and contractor-service environments." },
        { districtId: "natomas", reason: "Compare Natomas for north Sacramento access and airport-adjacent service or logistics needs." },
      ],
      validationNotes: [
        "Confirm the office, warehouse, and showroom split in the available suite.",
        "Verify customer access, signage, visitor parking, and delivery separation.",
        "Confirm grade-level loading access, dimensions, and hours.",
        "Validate permitted use for showroom, service, storage, or light operations.",
        "Confirm whether power, HVAC, restrooms, and office condition support the intended mix of uses.",
      ],
      relatedInsights: [compareSpaces, cityInsight, tenantImprovements],
      representativeCompanies: [
        "Relevant company categories include equipment-service firms, building-services companies, product distributors, and showroom-oriented trade users.",
        "The fit categories do not identify current tenants.",
      ],
      ecosystemSubtypes: ["showroom_flex", "flex", "small_bay_industrial"],
      representativeRole: "showroom_flex_environment",
      businessActivities: ["customer_showroom", "knowledge_work", "service_dispatch", "storage", "receiving"],
      businessArchetypes: ["equipment_service_company", "building_services_company", "distributor", "general_contractor"],
      operationalCharacteristics: ["office_showroom_mix", "office_warehouse_mix", "grade_level_loading", "small_suite_sizes", "showroom_frontage", "urban_core_access"],
      fitSummary: "Showroom/flex fit depends on office/warehouse balance, customer access, loading, and permitted use.",
      confidence: "editorially_supported",
      sourceNotes: [`${sourceDocs.cbre}: source rows for 3380 Industrial Blvd identify office/warehouse suite context and grade-level loading possibility.`],
    },
  }),
  record({
    name: "5711 Florin Perkins Rd",
    address: "5711 Florin Perkins Rd",
    city: "Sacramento",
    citySlug: "sacramento",
    districtKey: "powerInn",
    buildingType: "Small-bay industrial",
    primarySpaceType: "industrial",
    editorialRole: "Small-Bay Service Environment",
    editorialReason: "Represents the smaller warehouse-suite format used by local trades, service companies, and compact operators in the Power Inn industrial corridor.",
    representativeThemes: ["Small bay", "Service industrial", "Warehouse suites", "Power Inn"],
    businessFit: ["small contractors", "service dispatch", "equipment storage", "compact warehouse"],
    relatedDistrictPaths: [districts.ranchoCordova.path, districts.natomas.path, districts.westSacramento.path],
    nearbyBuildingPaths: [
      buildingPath("sacramento", "8583 Elder Creek Rd"),
      buildingPath("rancho-cordova", "11353 Pyrites Way"),
      buildingPath("west-sacramento", "3380 Industrial Blvd"),
    ],
    comparisonBuildingPaths: [
      buildingPath("rancho-cordova", "11353 Pyrites Way"),
      buildingPath("sacramento", "1329 N Market Blvd"),
      buildingPath("west-sacramento", "2928 Ramco St"),
    ],
    brief: {
      buildingSummary: "5711 Florin Perkins Rd is a Power Inn small-bay industrial example for local service, trade, storage, and dispatch users. It helps explain why many Sacramento businesses need modest warehouse suites with small office support rather than downtown office space, showroom flex, or larger warehouse/distribution buildings.",
      buildingImportance: "This property matters because small-bay industrial is one of the most important environments for small and medium-sized operators. The source record describes warehouse suites around 2,500 square feet with small offices and restrooms, making it a practical reference for businesses that need utility and affordability more than building image.",
      quickFacts: [
        { label: "Primary ecosystem", value: "Industrial & flex" },
        { label: "Representative role", value: "Small-bay service environment" },
        { label: "District", value: "Power Inn Industrial" },
        { label: "Source-supported suite pattern", value: "Colliers source describes approximately 2,500 square foot warehouse suites" },
        { label: "Office context", value: "Colliers source identifies a small office and restroom in each suite" },
        { label: "Operating context", value: "Best understood as compact service-industrial inventory, not conventional office or large distribution space" },
      ],
      idealFor: [
        "Electricians, HVAC companies, plumbing companies, and building-services users needing modest storage and dispatch space.",
        "Small contractors or equipment-service companies that need warehouse utility with limited office support.",
        "Local operators comparing Power Inn for practical Highway 50 industrial access.",
        "Businesses that need a compact base before expanding into larger warehouse, yard, or manufacturing space.",
      ],
      mayNotFit: [
        "Distribution users that need dock loading, trailer access, high clear height, or larger storage capacity.",
        "Customer-facing showroom users that need stronger visibility, product display, or visitor parking.",
        "Production users whose power, ventilation, equipment, or permitted-use needs exceed a typical small suite.",
      ],
      buildingExperience: "The experience is compact and utility-driven. Users should evaluate whether the suite can handle everyday storage, dispatch, small office work, restroom needs, deliveries, and employee parking without creating operational friction. This type of building often succeeds when the business does not overpay for space it does not need.",
      districtContext: "5711 Florin Perkins Rd sits in Power Inn Industrial, a Sacramento corridor where small-bay, service, warehouse, and light-production users can compare practical building formats. It should be compared with Rancho Cordova small-bay space when east-suburban access matters, Natomas when northside access matters, and West Sacramento when warehouse scale becomes more important.",
      advantages: [
        "Source-backed smaller suite pattern makes it a useful small-business industrial benchmark.",
        "Combines warehouse utility with small office and restroom support.",
        "Power Inn location helps service businesses access south and east Sacramento routes.",
        "Strong contrast to large distribution, showroom/flex, and contractor-yard environments.",
      ],
      tradeoffs: [
        "Small suites can limit storage growth, equipment staging, and future expansion.",
        "Loading, parking, power, and permitted use still need suite-specific confirmation.",
        "Customer-facing image is secondary to operational utility.",
        "Users with yard, fleet, or heavier production needs may outgrow this format quickly.",
      ],
      operationalProfile: [
        { label: "Suite scale", summary: "The source describes smaller warehouse suites, making right-sized storage and dispatch the key decision." },
        { label: "Office support", summary: "Small office and restroom context are source-supported, but exact layout and condition require validation." },
        { label: "Loading and parking", summary: "Small-bay users should confirm loading, parking, and service-vehicle access for the exact suite." },
        { label: "Growth path", summary: "This environment can be efficient for compact operators but may constrain businesses with rapid storage or fleet growth." },
      ],
      environmentExplanation: {
        whyItExists: "Small-bay industrial environments exist because many local service businesses need modest warehouse or storage space, vehicle access, dispatch capability, and a small office without the scale of a regional distribution facility.",
        whyChooseThisEnvironment: "Choose this environment over larger warehouse space when compact utility and cost discipline matter; choose it over office/flex when storage and dispatch are more important than customer presentation.",
        representativeValue: "5711 Florin Perkins Rd calibrates Sacramento's small-bay service decision.",
      },
      nearbyAlternatives: [
        { label: "11353 Pyrites Way", url: buildingPath("rancho-cordova", "11353 Pyrites Way"), reason: "Prefer this when a Rancho Cordova small-suite environment and Highway 50 east access better fit the service territory." },
        { label: "1329 N Market Blvd", url: buildingPath("sacramento", "1329 N Market Blvd"), reason: "Prefer this when dock access, grade-level loading, and north Sacramento logistics reach matter more." },
        { label: "3380 Industrial Blvd", url: buildingPath("west-sacramento", "3380 Industrial Blvd"), reason: "Prefer this when office/showroom balance and customer presence matter more than compact service-industrial utility." },
        { label: "8583 Elder Creek Rd", url: buildingPath("sacramento", "8583 Elder Creek Rd"), reason: "Prefer this when light manufacturing, power, and technical industrial requirements matter more than small-suite efficiency." },
      ],
      relatedDistricts: [
        { districtId: "rancho-cordova-commercial-core", reason: "Compare Rancho Cordova for small-suite service and office/flex alternatives along Highway 50." },
        { districtId: "natomas", reason: "Compare Natomas for north Sacramento service coverage and airport/freeway access." },
        { districtId: "west-sacramento-industrial", reason: "Compare West Sacramento when warehouse or distribution scale becomes more important." },
      ],
      validationNotes: [
        "Confirm loading access, door dimensions, and delivery path for the exact suite.",
        "Verify office percentage, restroom condition, and employee-support needs.",
        "Confirm parking allocation for employees, service vehicles, and vendors.",
        "Validate permitted use for storage, service dispatch, assembly, or equipment operations.",
        "Confirm whether power, ventilation, and suite depth can support the business's tools or equipment.",
      ],
      relatedInsights: [cityInsight, compareSpaces, tenantImprovements],
      representativeCompanies: [
        "Relevant company categories include electricians, HVAC companies, plumbing companies, contractors, equipment-service users, and building-services businesses.",
        "These are business-fit archetypes, not claims about current occupants.",
      ],
      ecosystemSubtypes: ["small_bay_industrial", "contractor_service"],
      representativeRole: "small_bay_service_environment",
      businessActivities: ["service_dispatch", "equipment_storage", "receiving", "inventory_management", "storage"],
      businessArchetypes: ["electrician", "hvac_company", "plumbing_company", "building_services_company", "equipment_service_company"],
      operationalCharacteristics: ["small_suite_sizes", "office_warehouse_mix", "service_vehicle_parking", "freeway_access"],
      fitSummary: "Small-bay fit depends on suite scale, office support, storage, loading, and service-vehicle needs.",
      confidence: "verified_property_fact",
      sourceNotes: [`${sourceDocs.colliers}: source rows for 5711 Florin Perkins Rd describe approximately 2,500 square foot warehouse suites with small office and restroom in each suite.`],
    },
  }),
  record({
    name: "11353 Pyrites Way",
    address: "11353 Pyrites Way",
    city: "Rancho Cordova",
    citySlug: "rancho-cordova",
    districtKey: "ranchoCordova",
    buildingType: "Small-suite industrial",
    primarySpaceType: "industrial",
    editorialRole: "Small-Bay Service Environment",
    editorialReason: "Represents Rancho Cordova's compact industrial suites for small service, storage, maker, and light-production users that need Highway 50 access without a large warehouse footprint.",
    representativeThemes: ["Small suite", "Service industrial", "Maker", "Rancho Cordova"],
    businessFit: ["small trade users", "maker operations", "light production", "equipment support"],
    relatedDistrictPaths: [districts.powerInn.path, districts.natomas.path, districts.westSacramento.path],
    nearbyBuildingPaths: [
      buildingPath("rancho-cordova", "11201 Sun Center Dr"),
      buildingPath("sacramento", "5711 Florin Perkins Rd"),
      buildingPath("sacramento", "8583 Elder Creek Rd"),
    ],
    comparisonBuildingPaths: [
      buildingPath("sacramento", "5711 Florin Perkins Rd"),
      buildingPath("rancho-cordova", "11201 Sun Center Dr"),
      buildingPath("west-sacramento", "3380 Industrial Blvd"),
    ],
    brief: {
      buildingSummary: "11353 Pyrites Way is a Rancho Cordova small-suite industrial example for service, storage, maker, and light-production users. It helps businesses compare compact industrial space along the Highway 50 corridor, where suite size, clear height, storefront character, zoning, power, and permitted use must be validated before shortlisting.",
      buildingImportance: "This property matters because it shows that industrial/flex value is not limited to large warehouses. The source record identifies small suites, tilt-up construction, storefront, clear-height range, and M2 zoning context. That makes it useful for businesses that need practical industrial utility but cannot justify a large building or yard-oriented site.",
      quickFacts: [
        { label: "Primary ecosystem", value: "Industrial & flex" },
        { label: "Representative role", value: "Small-bay service environment" },
        { label: "District", value: "Rancho Cordova Commercial Core" },
        { label: "Source-supported suite scale", value: "CBRE source identifies small suite records around 1,062 and 1,455 square feet" },
        { label: "Clear-height context", value: "CBRE source identifies approximately 14-16 foot clear height" },
        { label: "Construction context", value: "CBRE source identifies concrete tilt-up construction" },
        { label: "Frontage context", value: "CBRE source identifies glass and metal storefront" },
        { label: "Zoning context", value: "CBRE source identifies M2 zoning" },
      ],
      idealFor: [
        "Small trade, service, equipment-support, and building-services users that need a compact industrial suite.",
        "Cabinet shops, furniture makers, or light-production users that need to validate a small maker-oriented environment.",
        "Businesses that want Highway 50 access but do not need a larger warehouse or dedicated yard.",
        "Operators comparing a storefront-adjacent industrial suite against more warehouse-oriented Power Inn or West Sacramento properties.",
      ],
      mayNotFit: [
        "Storage-intensive users that need larger floor area, dock loading, trailer access, or high-clear warehouse functionality.",
        "Contractor users whose primary requirement is secure yard, fleet parking, or material storage.",
        "Production users with power, ventilation, noise, dust, or code requirements that exceed what a compact suite can support.",
      ],
      buildingExperience: "The experience is small, practical, and use-sensitive. A business should evaluate whether the suite can support the daily operation without forcing compromises around storage, deliveries, equipment, or customer arrival. The storefront context may help some users, but it does not replace validation of loading, power, and permitted use.",
      districtContext: "11353 Pyrites Way sits in Rancho Cordova Commercial Core, a Highway 50 market with office/flex, service, and industrial-adjacent inventory. It should be compared with Power Inn small-bay space for deeper industrial identity, 11201 Sun Center for yard-oriented contractor operations, and West Sacramento when warehouse/distribution needs become larger.",
      advantages: [
        "Source-backed small-suite, clear-height, construction, storefront, and zoning context make it useful for compact industrial evaluation.",
        "Represents a smaller Rancho Cordova alternative to larger service, yard, and warehouse properties.",
        "Can help trade, service, maker, or equipment-support users test whether a small suite is enough.",
        "Highway 50 corridor location supports eastern Sacramento service and workforce access.",
      ],
      tradeoffs: [
        "Small suites can constrain storage, equipment, staging, and expansion.",
        "Storefront character does not guarantee customer-facing suitability or signage rights.",
        "Manufacturing or maker uses require direct confirmation of power, ventilation, noise, and permitted use.",
        "Users needing yard or fleet parking may need a different contractor-service environment.",
      ],
      operationalProfile: [
        { label: "Suite size", summary: "The source identifies compact suites, so users should compare operational needs against limited footprint." },
        { label: "Clear height and construction", summary: "Clear-height and tilt-up context are source-supported, but storage, equipment, and buildout plans must be validated." },
        { label: "Storefront and access", summary: "Storefront context can support presentation or visitor needs, but customer access, signage, and parking remain separate checks." },
        { label: "Use approval", summary: "M2 zoning is source-supported, but permitted use for each business remains a due-diligence item." },
      ],
      environmentExplanation: {
        whyItExists: "Small-suite industrial environments exist for businesses that need practical workspace, storage, and light operations without the cost or scale of larger industrial buildings.",
        whyChooseThisEnvironment: "Choose this environment over a larger warehouse when compact utility matters most; choose it over office/flex when the business needs industrial character and potential maker or service function.",
        representativeValue: "11353 Pyrites Way calibrates the compact Rancho Cordova industrial-suite decision.",
      },
      nearbyAlternatives: [
        { label: "5711 Florin Perkins Rd", url: buildingPath("sacramento", "5711 Florin Perkins Rd"), reason: "Prefer this when Power Inn's small-bay service environment better fits the service territory or industrial identity." },
        { label: "11201 Sun Center Dr", url: buildingPath("rancho-cordova", "11201 Sun Center Dr"), reason: "Prefer this when yard, vehicle staging, and contractor-service operations are more important than compact suite size." },
        { label: "3380 Industrial Blvd", url: buildingPath("west-sacramento", "3380 Industrial Blvd"), reason: "Prefer this when office/showroom balance and West Sacramento core access matter more." },
        { label: "8583 Elder Creek Rd", url: buildingPath("sacramento", "8583 Elder Creek Rd"), reason: "Prefer this when power, clear height, and light-manufacturing validation matter more than small-suite flexibility." },
      ],
      relatedDistricts: [
        { districtId: "power-inn-industrial", reason: "Compare Power Inn for stronger service-industrial identity and more production-oriented examples." },
        { districtId: "west-sacramento-industrial", reason: "Compare West Sacramento when warehouse, distribution, or showroom/flex alternatives matter." },
        { districtId: "natomas", reason: "Compare Natomas for north Sacramento access and smaller logistics or service environments." },
      ],
      validationNotes: [
        "Confirm permitted use for the exact service, maker, storage, or light-production operation.",
        "Verify power, ventilation, noise, dust, and buildout requirements.",
        "Confirm loading access, delivery path, and service-vehicle parking.",
        "Validate storefront, signage, customer access, and parking expectations.",
        "Confirm expansion options if storage, staff, or equipment needs grow.",
      ],
      relatedInsights: [compareSpaces, tenantImprovements, cityInsight],
      representativeCompanies: [
        "Relevant company categories include small trade businesses, building-services companies, cabinet shops, furniture makers, and equipment-support users.",
        "These categories describe environmental fit and do not imply current occupancy.",
      ],
      ecosystemSubtypes: ["small_bay_industrial", "light_manufacturing", "contractor_service"],
      representativeRole: "small_bay_service_environment",
      businessActivities: ["service_dispatch", "storage", "equipment_storage", "assembly", "light_manufacturing"],
      businessArchetypes: ["electrician", "hvac_company", "cabinet_shop", "furniture_maker", "building_services_company"],
      operationalCharacteristics: ["small_suite_sizes", "moderate_clearance", "showroom_frontage", "manufacturing_compatible", "ground_floor_access", "freeway_access"],
      fitSummary: "Compact industrial fit depends on suite size, use approval, loading, power, and expansion limits.",
      confidence: "verified_property_fact",
      sourceNotes: [`${sourceDocs.cbre}: source rows for 11353 Pyrites Way identify small suite sizes, clear-height range, concrete tilt-up construction, storefront, and M2 zoning.`],
    },
  }),
];

module.exports = {
  schemaVersion: 1,
  standard: "industrial-flex-building-brief-standard-v1",
  calibrationSet: records.map((item) => item.building_path),
  canonicalBuildings: records,
};
