module.exports = {
  schemaVersion: "search-console-opportunity-snapshot-v1",
  source: "Manual Search Console observations",
  dateRange: "recent-observed",
  updatedAt: "2026-08-07",
  note: "Phase 1 supports manual or imported GSC snapshots. Records without complete metrics are still useful as demand-theme evidence, but should not be treated as precise rankings.",
  records: [
    {
      marketId: "san-francisco",
      marketName: "San Francisco",
      state: "CA",
      impressions: null,
      clicks: null,
      averagePosition: null,
      topQueries: [
        { query: "san francisco office space", impressions: null, clicks: null, position: null },
        { query: "san francisco retail space for lease", impressions: null, clicks: null, position: null },
        { query: "financial district san francisco office space", impressions: null, clicks: null, position: null },
        { query: "san francisco commercial buildings", impressions: null, clicks: null, position: null },
      ],
    },
    {
      marketId: "gainesville",
      marketName: "Gainesville",
      state: "FL",
      impressions: null,
      clicks: null,
      averagePosition: null,
      topQueries: [
        { query: "gainesville retail space for lease", impressions: null, clicks: null, position: null },
        { query: "gainesville storefront for lease", impressions: null, clicks: null, position: null },
        { query: "gainesville warehouse space", impressions: null, clicks: null, position: null },
        { query: "gainesville industrial space for lease", impressions: null, clicks: null, position: null },
      ],
    },
    {
      marketId: "aliso-viejo",
      marketName: "Aliso Viejo",
      state: "CA",
      impressions: null,
      clicks: null,
      averagePosition: null,
      topQueries: [
        { query: "aliso viejo commercial market trends", impressions: null, clicks: null, position: null },
        { query: "aliso viejo lease rates", impressions: null, clicks: null, position: null },
        { query: "aliso viejo market analysis", impressions: null, clicks: null, position: null },
      ],
    },
    {
      marketId: "indianapolis",
      marketName: "Indianapolis",
      state: "IN",
      impressions: null,
      clicks: null,
      averagePosition: null,
      topQueries: [
        { query: "indianapolis commercial pricing", impressions: null, clicks: null, position: null },
        { query: "indianapolis commercial market data", impressions: null, clicks: null, position: null },
        { query: "indianapolis warehouse building sizes", impressions: null, clicks: null, position: null },
      ],
    },
    {
      marketId: "salinas",
      marketName: "Salinas",
      state: "CA",
      impressions: 242,
      clicks: null,
      averagePosition: 15.3,
      topQueries: [
        { query: "salinas retail space for lease", impressions: null, clicks: null, position: null },
        { query: "salinas office space", impressions: null, clicks: null, position: null },
        { query: "salinas industrial space", impressions: null, clicks: null, position: null },
        { query: "salinas commercial property for lease", impressions: null, clicks: null, position: null },
      ],
    },
    {
      marketId: "fort-wayne",
      marketName: "Fort Wayne",
      state: "IN",
      impressions: null,
      clicks: null,
      averagePosition: null,
      topQueries: [
        { query: "fort wayne warehouses for lease", impressions: null, clicks: null, position: null },
        { query: "fort wayne industrial space", impressions: null, clicks: null, position: null },
        { query: "fort wayne flex space", impressions: null, clicks: null, position: null },
        { query: "fort wayne retail space", impressions: null, clicks: null, position: null },
      ],
    },
    {
      marketId: "san-rafael",
      marketName: "San Rafael",
      state: "CA",
      impressions: null,
      clicks: null,
      averagePosition: null,
      topQueries: [
        { query: "san rafael office space", impressions: null, clicks: null, position: null },
        { query: "san rafael retail space", impressions: null, clicks: null, position: null },
        { query: "san rafael commercial space for lease", impressions: null, clicks: null, position: null },
      ],
    },
    {
      marketId: "houston",
      marketName: "Houston",
      state: "TX",
      impressions: null,
      clicks: null,
      averagePosition: 45,
      topQueries: [
        { query: "houston commercial real estate", impressions: null, clicks: null, position: 45 },
        { query: "houston commercial property", impressions: null, clicks: null, position: 47 },
      ],
    },
  ],
};
