module.exports = {
  schemaVersion: "sf-office-editorial-recommendation-model-v1",
  modelKey: "san-francisco:office",
  marketId: "san-francisco",
  marketName: "San Francisco",
  regionId: "bay-area",
  regionName: "Bay Area",
  spaceType: "office",
  sourceDocuments: [
    "docs/product/rofo-product-experience-vision.md",
    "docs/product/commercial-location-decision-model.md",
    "docs/product/sf-office-location-decision-model.md",
    "docs/product/sf-office-editorial-recommendation-model.md",
  ],
  unsupportedRankingSignals: [
    "exactBudget",
    "budget",
    "cost",
    "costSensitivity",
    "currentRents",
    "askingRates",
    "concessions",
    "currentAvailability",
    "landlordMotivation",
    "leaseEconomics",
    "costPosition",
  ],
  initialConsiderationSet: [
    "financial-district",
    "soma",
    "mission-bay",
    "jackson-square",
    "south-beach",
  ],
  districtOrder: [
    "financial-district",
    "soma",
    "mission-bay",
    "jackson-square",
    "south-beach",
    "showplace-square",
    "dogpatch",
    "design-district",
    "potrero-hill",
    "mission-district",
  ],
  districts: {
    "financial-district": {
      districtName: "Financial District",
      launchRole: "default_initial",
      strategyRole: "Traditional downtown and client-facing office core.",
      stableAttributes: {
        transitOrientation: "high",
        parkingPattern: "low",
        walkability: "high",
        clientAccessibility: "high",
        districtImage: "traditional_professional",
        growthFlexibility: "medium",
        amenityEnvironment: "high",
        talentAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "low",
        lowerRiseCharacter: "low",
        neighborhoodOrientation: "low",
      },
      ecosystems: ["professional_services", "financial_services", "client_facing"],
      buildingCharacter: ["traditional_professional", "high_rise", "corporate"],
      nearbyAlternatives: ["jackson-square", "soma", "south-beach", "mission-bay"],
    },
    soma: {
      districtName: "SoMa",
      launchRole: "default_initial",
      strategyRole: "Central technology, creative, and adaptive office district.",
      stableAttributes: {
        transitOrientation: "high",
        parkingPattern: "low",
        walkability: "high",
        clientAccessibility: "high",
        districtImage: "creative_central",
        growthFlexibility: "medium",
        amenityEnvironment: "high",
        talentAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "high",
        lowerRiseCharacter: "medium",
        neighborhoodOrientation: "medium",
      },
      ecosystems: ["technology", "creative", "product"],
      buildingCharacter: ["creative_informal", "historic_distinctive", "modern_polished"],
      nearbyAlternatives: ["financial-district", "mission-bay", "jackson-square", "south-beach", "showplace-square"],
    },
    "mission-bay": {
      districtName: "Mission Bay",
      launchRole: "default_initial",
      strategyRole: "Modern growth, innovation, and UCSF-adjacent office district.",
      stableAttributes: {
        transitOrientation: "high",
        parkingPattern: "medium",
        walkability: "medium",
        clientAccessibility: "medium",
        districtImage: "modern_growth",
        growthFlexibility: "high",
        amenityEnvironment: "high",
        talentAccess: "high",
        modernEnvironment: "high",
        creativeCharacter: "medium",
        lowerRiseCharacter: "low",
        neighborhoodOrientation: "medium",
      },
      ecosystems: ["technology", "life_science", "innovation"],
      buildingCharacter: ["modern_polished", "campus_like"],
      nearbyAlternatives: ["soma", "south-beach", "dogpatch", "potrero-hill"],
    },
    "jackson-square": {
      districtName: "Jackson Square",
      launchRole: "default_initial",
      strategyRole: "Boutique, polished, lower-rise professional office district.",
      stableAttributes: {
        transitOrientation: "high",
        parkingPattern: "low",
        walkability: "high",
        clientAccessibility: "high",
        districtImage: "polished_boutique",
        growthFlexibility: "low",
        amenityEnvironment: "high",
        talentAccess: "high",
        modernEnvironment: "low",
        creativeCharacter: "high",
        lowerRiseCharacter: "high",
        neighborhoodOrientation: "medium",
      },
      ecosystems: ["professional_services", "design_creative", "client_facing"],
      buildingCharacter: ["historic_distinctive", "traditional_professional", "lower_rise_neighborhood"],
      nearbyAlternatives: ["financial-district", "soma", "south-beach"],
    },
    "south-beach": {
      districtName: "South Beach",
      launchRole: "default_initial",
      strategyRole: "Access-oriented waterfront and Transbay-adjacent office bridge.",
      stableAttributes: {
        transitOrientation: "high",
        parkingPattern: "low",
        walkability: "high",
        clientAccessibility: "high",
        districtImage: "access_oriented",
        growthFlexibility: "medium",
        amenityEnvironment: "high",
        talentAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "medium",
        lowerRiseCharacter: "low",
        neighborhoodOrientation: "medium",
      },
      ecosystems: ["client_facing", "technology", "central_access"],
      buildingCharacter: ["modern_polished", "traditional_professional", "waterfront_access"],
      nearbyAlternatives: ["financial-district", "soma", "mission-bay", "jackson-square"],
    },
    "showplace-square": {
      districtName: "Showplace Square",
      launchRole: "signal_specific",
      strategyRole: "Creative, product-oriented, design-adjacent, less conventional office district.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "medium",
        walkability: "medium",
        clientAccessibility: "medium",
        districtImage: "creative_product",
        growthFlexibility: "medium",
        amenityEnvironment: "medium",
        talentAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "high",
        lowerRiseCharacter: "high",
        neighborhoodOrientation: "medium",
      },
      ecosystems: ["technology", "product", "design_creative", "hardware"],
      buildingCharacter: ["creative_informal", "lower_rise_neighborhood", "adaptive"],
      nearbyAlternatives: ["soma", "design-district", "potrero-hill", "dogpatch"],
      entrySignals: ["creative_informal", "lower_rise_neighborhood", "technology", "design_creative", "parking", "potrero_dogpatch_access"],
    },
    dogpatch: {
      districtName: "Dogpatch",
      launchRole: "signal_specific",
      strategyRole: "Industrial-heritage, innovation, office/R&D, and Mission Bay-adjacent district.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "medium",
        walkability: "medium",
        clientAccessibility: "medium",
        districtImage: "industrial_creative",
        growthFlexibility: "medium",
        amenityEnvironment: "medium",
        talentAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "high",
        lowerRiseCharacter: "high",
        neighborhoodOrientation: "high",
      },
      ecosystems: ["technology", "product", "life_science", "hardware", "creative"],
      buildingCharacter: ["creative_informal", "lower_rise_neighborhood", "adaptive"],
      nearbyAlternatives: ["mission-bay", "potrero-hill", "showplace-square"],
      entrySignals: ["creative_informal", "lower_rise_neighborhood", "life_science", "technology", "parking", "ucsf_proximity"],
    },
    "design-district": {
      districtName: "Design District",
      launchRole: "signal_specific",
      strategyRole: "Design, showroom, product, and creative commercial district.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "medium",
        walkability: "medium",
        clientAccessibility: "medium",
        districtImage: "design_creative",
        growthFlexibility: "medium",
        amenityEnvironment: "medium",
        talentAccess: "high",
        modernEnvironment: "medium",
        creativeCharacter: "high",
        lowerRiseCharacter: "high",
        neighborhoodOrientation: "medium",
      },
      ecosystems: ["design_creative", "product", "showroom"],
      buildingCharacter: ["creative_informal", "lower_rise_neighborhood", "adaptive"],
      nearbyAlternatives: ["showplace-square", "potrero-hill", "soma"],
      entrySignals: ["design_creative", "creative_informal", "lower_rise_neighborhood", "parking"],
    },
    "potrero-hill": {
      districtName: "Potrero Hill",
      launchRole: "signal_specific",
      strategyRole: "Neighborhood-scale creative office near Mission Bay, Dogpatch, and Showplace Square.",
      stableAttributes: {
        transitOrientation: "medium",
        parkingPattern: "medium",
        walkability: "medium",
        clientAccessibility: "medium",
        districtImage: "neighborhood_creative",
        growthFlexibility: "medium",
        amenityEnvironment: "medium",
        talentAccess: "high",
        modernEnvironment: "low",
        creativeCharacter: "high",
        lowerRiseCharacter: "high",
        neighborhoodOrientation: "high",
      },
      ecosystems: ["creative", "product", "neighborhood"],
      buildingCharacter: ["lower_rise_neighborhood", "creative_informal"],
      nearbyAlternatives: ["dogpatch", "showplace-square", "mission-bay", "design-district"],
      entrySignals: ["lower_rise_neighborhood", "creative_informal", "parking", "ucsf_proximity"],
    },
    "mission-district": {
      districtName: "Mission District",
      launchRole: "signal_specific",
      strategyRole: "Neighborhood, creative, nonprofit, mission-driven, walkable office district.",
      stableAttributes: {
        transitOrientation: "high",
        parkingPattern: "low",
        walkability: "high",
        clientAccessibility: "high",
        districtImage: "neighborhood_creative",
        growthFlexibility: "low",
        amenityEnvironment: "high",
        talentAccess: "high",
        modernEnvironment: "low",
        creativeCharacter: "high",
        lowerRiseCharacter: "high",
        neighborhoodOrientation: "high",
      },
      ecosystems: ["creative", "nonprofit", "mission_driven", "local_services"],
      buildingCharacter: ["creative_informal", "lower_rise_neighborhood"],
      nearbyAlternatives: ["soma", "potrero-hill", "design-district"],
      entrySignals: ["creative_informal", "lower_rise_neighborhood", "nonprofit", "mission_driven", "amenities", "bart_walkability"],
    },
  },
  businessFacts: {
    city: { required: true, behavior: "defines_market" },
    spaceType: { required: true, behavior: "defines_space_type_model" },
    headcount: { required: false, behavior: "influences_scale_and_inventory_depth" },
    regularOccupancy: { required: false, behavior: "influences_commute_and_amenity_weight" },
    hybridWorkPattern: { required: false, behavior: "influences_commute_and_daily_use" },
    expectedGrowth: { required: false, behavior: "influences_growth_flexibility" },
    clientVisitFrequency: { required: false, behavior: "influences_client_access_and_image" },
    recruitingImportance: { required: false, behavior: "influences_talent_access_and_environment" },
    businessType: { required: false, behavior: "influences_ecosystem_fit" },
    operationalUse: { required: false, behavior: "influences_office_job_to_be_done" },
    approximateSquareFootage: { required: false, behavior: "compatibility_only" },
  },
  officeEnvironmentTaxonomy: {
    modern_polished: {
      label: "Modern and polished",
      attributes: ["modernEnvironment", "growthFlexibility", "districtImage"],
      rise: ["mission-bay", "south-beach", "soma", "financial-district"],
      fall: ["mission-district", "potrero-hill"],
    },
    historic_distinctive: {
      label: "Historic and distinctive",
      attributes: ["creativeCharacter", "lowerRiseCharacter", "districtImage"],
      rise: ["jackson-square", "soma"],
      fall: ["mission-bay"],
    },
    creative_informal: {
      label: "Creative and informal",
      attributes: ["creativeCharacter", "ecosystems", "buildingCharacter"],
      rise: ["soma", "showplace-square", "dogpatch", "design-district", "potrero-hill", "mission-district"],
      fall: ["financial-district"],
      enter: ["showplace-square", "dogpatch", "design-district", "potrero-hill", "mission-district"],
    },
    traditional_professional: {
      label: "Traditional and professional",
      attributes: ["clientAccessibility", "districtImage", "modernEnvironment"],
      rise: ["financial-district", "jackson-square", "south-beach"],
      fall: ["showplace-square", "dogpatch", "design-district", "mission-district"],
    },
    lower_rise_neighborhood: {
      label: "Lower-rise and neighborhood-oriented",
      attributes: ["lowerRiseCharacter", "neighborhoodOrientation", "parkingPattern"],
      rise: ["jackson-square", "potrero-hill", "dogpatch", "design-district", "mission-district"],
      fall: ["financial-district", "mission-bay"],
      enter: ["potrero-hill", "dogpatch", "design-district", "mission-district"],
    },
    not_sure: {
      label: "Not sure yet",
      attributes: [],
      rise: [],
      fall: [],
      enter: [],
    },
  },
  constraints: {
    districtAnchor: {
      effect: "strong_weight_anchor",
      explanation: "User-selected anchors strongly weight the named district and can introduce known nearby alternatives when comparison is allowed.",
    },
    nearbyAlternatives: {
      effect: "introduce_known_nearby",
      explanation: "Nearby alternatives enter only from explicit model relationships.",
    },
    commuteOrientation: {
      effect: "strong_weight_access_pattern",
      values: {
        marin: {
          rise: ["financial-district", "jackson-square", "south-beach"],
          fall: ["mission-bay", "dogpatch", "potrero-hill"],
          attributes: ["transitOrientation", "parkingPattern"],
        },
        east_bay: {
          rise: ["financial-district", "soma", "south-beach"],
          fall: ["showplace-square", "dogpatch", "design-district", "potrero-hill"],
          attributes: ["transitOrientation"],
        },
        peninsula_south_bay: {
          rise: ["soma", "mission-bay", "south-beach"],
          fall: ["jackson-square"],
          attributes: ["transitOrientation"],
        },
      },
    },
    institutionProximity: {
      values: {
        ucsf: {
          rise: ["mission-bay"],
          enter: ["dogpatch", "potrero-hill"],
          fall: ["financial-district", "jackson-square"],
          attributes: ["ecosystems", "nearbyAlternatives"],
        },
      },
    },
  },
  priorities: {
    regional_transit: {
      label: "Regional transit",
      attributes: ["transitOrientation"],
      riseHigh: ["financial-district", "soma", "mission-bay", "jackson-square", "south-beach", "mission-district"],
      fallLow: [],
    },
    parking: {
      label: "Parking and driving practicality",
      attributes: ["parkingPattern"],
      riseHigh: ["mission-bay", "showplace-square", "dogpatch", "design-district", "potrero-hill"],
      fallLow: ["financial-district", "soma", "jackson-square", "south-beach", "mission-district"],
      enter: ["showplace-square", "dogpatch", "design-district", "potrero-hill"],
    },
    client_access: {
      label: "Client access",
      attributes: ["clientAccessibility", "districtImage"],
      riseHigh: ["financial-district", "jackson-square", "south-beach", "soma"],
      fallLow: ["dogpatch", "potrero-hill", "showplace-square"],
    },
    recruiting: {
      label: "Recruiting and employee attraction",
      attributes: ["talentAccess", "amenityEnvironment", "creativeCharacter"],
      riseHigh: ["soma", "mission-bay", "south-beach", "financial-district"],
    },
    walkability_amenities: {
      label: "Walkability and amenities",
      attributes: ["walkability", "amenityEnvironment"],
      riseHigh: ["financial-district", "soma", "jackson-square", "south-beach", "mission-district"],
      enter: ["mission-district"],
    },
    growth_flexibility: {
      label: "Growth flexibility",
      attributes: ["growthFlexibility"],
      riseHigh: ["mission-bay", "soma", "financial-district", "south-beach"],
      fallLow: ["jackson-square", "mission-district", "potrero-hill"],
    },
  },
  businessTypeEffects: {
    technology: {
      rise: ["soma", "mission-bay", "south-beach", "showplace-square", "dogpatch"],
      enter: ["showplace-square", "dogpatch"],
      attributes: ["ecosystems", "talentAccess"],
    },
    professional_services: {
      rise: ["financial-district", "jackson-square", "south-beach"],
      fall: ["mission-district", "dogpatch"],
      attributes: ["clientAccessibility", "districtImage"],
    },
    life_science: {
      rise: ["mission-bay"],
      enter: ["dogpatch", "potrero-hill"],
      attributes: ["ecosystems", "nearbyAlternatives"],
    },
    design_creative: {
      rise: ["design-district", "showplace-square", "soma", "jackson-square", "potrero-hill"],
      enter: ["design-district", "showplace-square", "potrero-hill", "mission-district"],
      attributes: ["creativeCharacter", "ecosystems"],
    },
    nonprofit: {
      rise: ["mission-district"],
      enter: ["mission-district", "potrero-hill"],
      attributes: ["neighborhoodOrientation", "ecosystems"],
    },
    mission_driven: {
      rise: ["mission-district"],
      enter: ["mission-district", "potrero-hill"],
      attributes: ["neighborhoodOrientation", "ecosystems"],
    },
  },
  operationalUseEffects: {
    client_meetings: { priorityAlias: "client_access" },
    team_collaboration: { priorityAlias: "recruiting" },
    recruiting: { priorityAlias: "recruiting" },
    lab_rd_adjacency: { constraintAlias: "institutionProximity", value: "ucsf" },
    showroom_presentation: {
      rise: ["design-district", "showplace-square", "jackson-square"],
      enter: ["design-district", "showplace-square"],
      attributes: ["ecosystems", "creativeCharacter"],
    },
    quiet_focused_work: {
      rise: ["jackson-square", "potrero-hill"],
      enter: ["potrero-hill"],
      attributes: ["lowerRiseCharacter", "neighborhoodOrientation"],
    },
  },
  confidenceStates: {
    starting_set: {
      label: "Starting set",
      description: "Rofo knows city and space type and can identify credible office districts, but should not imply a precise ranking.",
      ordered: false,
    },
    emerging_ranking: {
      label: "Emerging ranking",
      description: "Rofo has enough business context to show which districts are separating and why, while preserving near ties.",
      ordered: true,
    },
    refined_shortlist: {
      label: "Refined shortlist",
      description: "Rofo can defend a smaller shortlist because multiple user signals point toward the same district attributes.",
      ordered: true,
    },
  },
  nextQuestions: {
    commuteOrientation: {
      questionId: "commuteOrientation",
      prompt: "Where are most employees commuting from?",
      targets: ["transitOrientation", "parkingPattern"],
    },
    officeEnvironment: {
      questionId: "officeEnvironment",
      prompt: "What kind of office environment would fit the business?",
      targets: ["creativeCharacter", "modernEnvironment", "lowerRiseCharacter", "districtImage"],
    },
    clientVisitFrequency: {
      questionId: "clientVisitFrequency",
      prompt: "How often will clients or partners visit the office?",
      targets: ["clientAccessibility", "districtImage"],
    },
    expectedGrowth: {
      questionId: "expectedGrowth",
      prompt: "Do you expect the team to grow meaningfully in the next 12 to 24 months?",
      targets: ["growthFlexibility"],
    },
    businessType: {
      questionId: "businessType",
      prompt: "Which description is closest to your business?",
      targets: ["ecosystems"],
    },
  },
  explanationTemplates: {
    rise: "{districtName} moved up because {signalLabel} aligns with {attributeLabel}.",
    fall: "{districtName} moved down because {signalLabel} makes {attributeLabel} less aligned than stronger candidates.",
    enter: "{districtName} entered consideration because {signalLabel} matches {attributeLabel}.",
    tie: "{districtA} and {districtB} remain close because both support {sharedSignal}.",
    excluded: "{districtName} was excluded because {reason}.",
    costIgnored: "Cost sensitivity was preserved for broker review but did not affect district ranking.",
  },
};
