const crypto = require("node:crypto");
const readiness = require("../lib/recommendations/private-recommendation-readiness");
const accessFoundation = require("./sfAccessFoundationV0");
const compositionFoundation = require("./sfOfficeCompositionFoundation");
const sfOfficeModel = require("./sfOfficeRecommendationModel");
const sfRetailFoundation = require("./sfRetailCompositionFoundation");
const sfIndustrialFlexFoundation = require("./sfIndustrialFlexCompositionFoundation");
const districtGeography = require("./requirementPrototypeDistrictGeography");
const representativeContent = require("./sfRepresentativeContent");
const publicSurfaces = require("./sfPublicDecisionSurfaces");

const dependencies = { accessFoundation, compositionFoundation, sfOfficeModel, sfRetailFoundation, sfIndustrialFlexFoundation, districtGeography };
const BASE = "/commercial-real-estate/CA/san-francisco/";
const criterion = (dimension, value) => ({ dimension, status: "PREFERRED", value: Array.isArray(value) ? { list: value, text: "" } : { text: value, list: [] } });
const locationLogic = () => ({ marketAnchor: { marketId: "san-francisco", geographyId: "san-francisco", displayName: "San Francisco" }, specificPreference: { candidateDistrictIds: [], candidateDistrictNames: [] } });
const office = (id, business, origins, clients, environment, transit, parking) => ({ id, schemaVersion: "requirement:v1", propertyTypes: ["office"], activities: ["work"], businessContext: { summary: business }, locationLogic: locationLogic(), criteria: [criterion("universal.location.employee_origins", origins), criterion("office.access.client_visits", clients), criterion("office.environment.image", environment), criterion("universal.access.transit_importance", transit), criterion("universal.access.parking_importance", parking)] });
const retail = (id, identity, destination, customers, activities = []) => ({ id, schemaVersion: "requirement:v1", propertyTypes: ["retail_service"], activities: ["host_visitors", "sell_serve", ...activities], businessContext: { summary: identity }, locationLogic: locationLogic(), criteria: [criterion("universal.business.type", [identity, identity.replaceAll("_", " ")]), criterion("retail.customer.destination_visibility", destination), criterion("universal.location.customer_origins", customers)] });
const industrialFlex = (id, activities, summary) => ({ id, schemaVersion: "requirement:v1", propertyTypes: ["industrial_flex"], activities, businessContext: { summary }, locationLogic: locationLogic(), criteria: [] });

const fixtures = [
  { id: "client-facing-professional-east-bay", group: "Office", title: "Client-facing professional firm with East Bay access", description: "A professional-services office balancing frequent client meetings, East Bay access, regional transit, and a credible business setting.", profile: "A client-facing professional-services firm seeking San Francisco Office space for a workforce split between San Francisco and the East Bay. Clients visit frequently, transit is important, and parking is not.", requirement: office("sample-office-professional", "Accounting / professional services", ["San Francisco", "East Bay"], "Clients visit frequently", "Established and professional", "Public transit is very important", "Parking is not important"), expected: ["financial-district", "south-beach", "jackson-square"] },
  { id: "technology-product-peninsula", group: "Office", title: "Technology product team with Peninsula access", description: "A technology team comparing modern environments and Peninsula-oriented employee access.", profile: "A technology and product team seeking a modern San Francisco Office with meaningful Peninsula and South Bay employee access, strong transit, and room to support growth.", requirement: office("sample-office-technology", "Technology / product company", ["Peninsula", "South Bay"], "Clients visit occasionally", "Modern and energetic", "Public transit is very important", "Convenient parking is helpful"), expected: ["soma", "mission-bay", "south-beach"] },
  { id: "creative-company-marin-sf", group: "Office", title: "Creative company with a Marin and SF workforce", description: "A creative Office search balancing character, northern access, parking, and neighborhood scale.", profile: "An architecture and creative-services company with employees in San Francisco and Marin. It values a distinctive environment, northern access, and practical parking more than regional transit.", requirement: office("sample-office-creative", "Architecture, Design & Creative Services", ["San Francisco", "Marin / North Bay"], "Clients rarely or never visit", "Creative and distinctive", "Public transit is not important", "Convenient parking is helpful"), expected: ["marina-district", "presidio", "jackson-square"] },
  { id: "premium-design-retailer", group: "Retail", title: "Premium and design-oriented retailer", description: "A destination-oriented design retailer comparing premium corridors, showrooms, and lifestyle environments.", profile: "A premium design and showroom retailer expecting planned visits from across the Bay Area and needing a location whose customer environment reinforces the concept.", requirement: retail("sample-retail-premium", "showroom_design", "Primarily destination-driven", ["Across the Bay Area / mixed"], ["display_present"]), expected: ["sacramento-street", "showplace-square", "hayes-valley"] },
  { id: "neighborhood-wellness-service", group: "Retail", title: "Neighborhood wellness and service business", description: "A repeat-visit neighborhood business comparing resident demand, visibility, services, and access.", profile: "A wellness and neighborhood-service business relying on repeat San Francisco customers, useful visibility, and a storefront environment that supports frequent local visits.", requirement: retail("sample-retail-wellness", "neighborhood_service", "Visibility materially supports customer visits", ["San Francisco"]), expected: ["chestnut-street", "chinatown", "valencia-street"] },
  { id: "visitor-food-specialty", group: "Retail", title: "Visitor, food, and specialty concept", description: "A destination food concept comparing visitor activity, evening demand, specialty commerce, and operating tradeoffs.", profile: "A food and specialty concept drawing planned visitors from across the Bay Area and depending on a distinctive day-to-evening customer environment.", requirement: retail("sample-retail-food", "food_beverage", "Primarily destination-driven", ["Across the Bay Area / mixed"], ["prepare_produce_food"]), expected: ["north-beach", "union-street-cow-hollow", "valencia-street"] },
  { id: "city-serving-warehouse-contractor", group: "Industrial", title: "City-serving warehouse and contractor operation", description: "An operational search led by storage, service vehicles, dispatch, and city-serving access.", profile: "A city-serving contractor and warehouse operation needing storage, dispatch, service-vehicle access, and an environment where practical operations lead the decision.", requirement: industrialFlex("sample-industrial-contractor", ["dispatch", "operate_vehicles", "repair_service", "store"], "City-serving warehouse and contractor operation"), expected: ["bayview-industrial", "central-waterfront", "dogpatch"], expectedModel: "industrial" },
  { id: "design-showroom-flex", group: "Flex", title: "Design showroom", description: "A customer-facing Flex search combining display, office work, and operational support.", profile: "A design showroom combining customer presentations, office work, and light operational support rather than conventional warehouse use.", requirement: industrialFlex("sample-flex-showroom", ["display_present", "host_visitors", "work"], "Design showroom and office"), expected: ["showplace-square", "central-waterfront", "dogpatch"], expectedModel: "flex" },
  { id: "office-production-maker-flex", group: "Flex", title: "Office, production, and maker business", description: "A hybrid search balancing product development, making, employee workspace, and operational access.", profile: "A maker and product-development business combining office work, prototyping, assembly, and light production in one San Francisco location.", requirement: industrialFlex("sample-flex-maker", ["work", "make_assemble", "prototype", "product_development"], "Office and production maker business"), expected: ["bayview-industrial", "central-waterfront", "dogpatch"], expectedModel: "mixed" },
];

const surfaceById = new Map(publicSurfaces.surfaces.map((item) => [item.id, item]));
function titleFor(id, fallback) { return surfaceById.get(id)?.name || fallback || id.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join(" "); }
function pathFor(id) { return surfaceById.get(id)?.path || `${BASE}${id}/`; }
function project(fixture) {
  const result = readiness.evaluateRecommendationReadiness(fixture.requirement, dependencies);
  const ids = result.shortlist.map((item) => item.districtId);
  if (!["FULL", "BOUNDED"].includes(result.readiness) || ids.join("|") !== fixture.expected.join("|")) throw new Error(`Public sample ${fixture.id} requires review: ${result.readiness} ${ids.join(",")}`);
  if (fixture.expectedModel && result.candidateComposition?.resolvedModel !== fixture.expectedModel) throw new Error(`Public sample ${fixture.id} applicability drifted.`);
  const locations = result.shortlist.map((item) => ({
    districtId: item.districtId,
    name: titleFor(item.districtId, item.districtName),
    path: pathFor(item.districtId),
    reason: item.propertyTypeFit?.summary || item.office?.summary || item.retail?.summary || item.industrialFlex?.summary || item.environment?.reasons?.[0] || "Reviewed location fit for this example profile.",
    strengths: [...(item.environment?.reasons || []), ...(item.access?.strengths || [])].slice(0, 3),
    tradeoffs: [...(item.propertyTypeFit?.tradeoffs || []), ...(item.access?.tradeoffs || []), ...(item.unknowns || [])].slice(0, 3),
    access: item.access?.overall || "UNKNOWN",
    representativeContent: (representativeContent.byDistrictId[item.districtId] || []).slice(0, 2),
  }));
  const signature = crypto.createHash("sha256").update(JSON.stringify({ requirement: fixture.requirement, readiness: result.readiness, model: result.candidateComposition?.resolvedModel || fixture.requirement.propertyTypes[0], ids })).digest("hex");
  const spaceType = fixture.group === "Industrial" || fixture.group === "Flex" ? "Industrial / warehouse / flex" : fixture.group === "Retail" ? "Retail / service" : "Office";
  return Object.freeze({ ...fixture, requirement: Object.freeze(fixture.requirement), readiness: result.readiness, resolvedApplicability: result.candidateComposition?.resolvedModel || fixture.group.toLowerCase(), locations: Object.freeze(locations), signature, url: `/example-location-brief/${fixture.id}/`, spaceType, cta: `/location-requirement/?journey=new&city=San%20Francisco&state=CA&marketId=san-francisco&spaceType=${encodeURIComponent(spaceType)}&source=example&sourcePath=${encodeURIComponent(`/example-location-brief/${fixture.id}/`)}` });
}

const briefs = Object.freeze(fixtures.map(project));
module.exports = Object.freeze({ schemaVersion: "sf-public-sample-briefs:v1", marketId: "san-francisco", status: "CERTIFIED", briefs, byId: Object.freeze(Object.fromEntries(briefs.map((brief) => [brief.id, brief]))) });
