const BASE = "/commercial-real-estate/CA/san-francisco/";

const related = (...items) => items.map(([name, slug, reason]) => ({
  name,
  path: `${BASE}${slug}/`,
  reason,
}));

const retail = (id, name, options) => ({
  id,
  name,
  slug: id,
  path: `${BASE}${id}/`,
  areaType: options.areaType || "retail corridor",
  spaceTypes: ["retail"],
  defaultSpaceType: "Retail / service",
  ...options,
});

// Public projections of already-certified SF intelligence. These records do
// not participate in recommendation eligibility, composition, or ordering.
const surfaces = [
  retail("sacramento-street", "Sacramento Street", {
    classification: "Situational retail decision",
    lead: "Compare Sacramento Street as a small-scale premium, design, home, and service-retail corridor within north-central San Francisco.",
    identity: "Sacramento Street is a focused neighborhood-commercial corridor rather than a broad district. Its useful decision boundary is the concentration of shops, design businesses, services, and customer destinations along the street—not an exact claim about every adjacent block.",
    character: "The corridor combines premium and design-oriented shopping with neighborhood services and a quieter, more deliberate destination pattern than downtown retail.",
    useCases: ["Home, interiors, and design-oriented retail", "Premium boutiques and destination specialty concepts", "Selective personal and professional services"],
    strengths: ["A distinctive premium and design context", "Smaller-scale storefront character", "Neighborhood setting that can support planned customer visits"],
    tradeoffs: ["A narrow corridor with limited storefront depth", "Less regional transit reach than downtown", "Parking and curb access require property-level review"],
    access: "Best understood as a neighborhood and destination corridor. Customers are more likely to arrive through local travel or a planned visit than through a single regional transit gateway.",
    related: related(["Fillmore Street", "fillmore-street", "Compare a broader lifestyle, dining, wellness, and service corridor."], ["Hayes Valley", "hayes-valley", "Compare a more energetic central neighborhood-shopping environment."], ["Union Street / Cow Hollow", "union-street-cow-hollow", "Compare specialty retail with more dining, wellness, and weekend activity."], ["Showplace Square / Design District", "showplace-square", "Compare a trade- and showroom-oriented design environment."]),
  }),
  retail("fillmore-street", "Fillmore Street", {
    classification: "Core retail decision",
    lead: "Compare Fillmore Street for lifestyle retail, dining, wellness, services, and premium neighborhood demand.",
    identity: "Fillmore Street is a recognizable commercial corridor with its own customer and storefront environment. It is not interchangeable with nearby Hayes Valley or the broader Western Addition.",
    character: "Lifestyle shopping, food, wellness, and services serve neighborhood customers while also drawing planned visits from a wider trade area.",
    useCases: ["Boutique and lifestyle retail", "Fitness, wellness, and personal services", "Dining and neighborhood-oriented consumer concepts"],
    strengths: ["Affluent neighborhood and lifestyle context", "A useful mix of shopping, food, wellness, and services", "Customer environment that is less visitor-dependent than downtown"],
    tradeoffs: ["Storefronts and curb access can be constrained", "Regional access depends more on local connections than rail gateways", "Block and frontage conditions need property-level validation"],
    access: "Fillmore is primarily a local and neighborhood customer environment. Transit supports city access, but it does not offer the direct regional gateways of downtown districts.",
    related: related(["Sacramento Street", "sacramento-street", "Compare a narrower premium, home, and design destination."], ["Hayes Valley", "hayes-valley", "Compare a more central, design-conscious neighborhood environment."], ["Chestnut Street", "chestnut-street", "Compare a denser daily-use, service, food, and wellness corridor."], ["Union Street / Cow Hollow", "union-street-cow-hollow", "Compare a specialty and weekend-oriented lifestyle corridor."]),
  }),
  retail("union-street-cow-hollow", "Union Street / Cow Hollow", {
    parent: { name: "Marina District", path: `${BASE}marina-district/` },
    classification: "Core retail decision",
    lead: "Compare Union Street / Cow Hollow as a specialty, wellness, dining, and lifestyle-retail corridor within the broader Marina area.",
    identity: "Union Street and Cow Hollow form one customer-facing Retail decision within the broader Marina umbrella. For Retail comparison, it is distinct from Chestnut Street's more daily-use and convenience-oriented environment.",
    character: "Specialty shops, dining, wellness, and weekend activity support boutique and destination concepts that benefit from a recognizable lifestyle setting.",
    useCases: ["Boutique and specialty retail", "Wellness and personal services", "Dining and planned-visit lifestyle concepts"],
    strengths: ["Recognizable specialty and lifestyle identity", "Dining, wellness, and weekend activity", "A wider planned-visit role than a purely convenience corridor"],
    tradeoffs: ["Traffic and parking friction can be material", "Less suited to high-volume convenience retail than Chestnut Street", "Storefront scale and servicing vary by property"],
    access: "The corridor is strongest for neighborhood and planned customer visits. Northern geography can help some Marin-oriented trips, but parking and local circulation still require practical review.",
    related: related(["Chestnut Street", "chestnut-street", "Compare broader daily-use, service, food, and resident demand."], ["Fillmore Street", "fillmore-street", "Compare another premium lifestyle corridor with a different neighborhood catchment."], ["Sacramento Street", "sacramento-street", "Compare a quieter design and premium destination corridor."], ["Hayes Valley", "hayes-valley", "Compare a more central creative and design-conscious setting."]),
  }),
  retail("chestnut-street", "Chestnut Street", {
    parent: { name: "Marina District", path: `${BASE}marina-district/` },
    classification: "Core retail decision",
    lead: "Compare Chestnut Street for neighborhood-serving retail, food, fitness, wellness, services, and daily-use customer demand.",
    identity: "Chestnut Street is a dense Retail corridor within the Marina umbrella. It competes as the practical daily-use and service-oriented choice, while Union Street / Cow Hollow has a stronger specialty and destination pattern.",
    character: "A continuous mix of food, services, wellness, and storefront retail serves residents and supports frequent neighborhood use.",
    useCases: ["Neighborhood services and convenience retail", "Fitness, wellness, and personal care", "Food, beverage, and daily-use concepts"],
    strengths: ["Dense resident-serving commercial environment", "Broad mix of food, service, wellness, and retail", "Visible neighborhood storefront context"],
    tradeoffs: ["Parking, loading, and curb competition are important", "Neighborhood scale limits some larger formats", "Exact block and frontage quality remain consequential"],
    access: "Chestnut Street is chiefly a neighborhood customer environment. It can serve northern San Francisco and planned Marin visitors, but it is not a regional transit-oriented retail center.",
    related: related(["Union Street / Cow Hollow", "union-street-cow-hollow", "Compare specialty, destination, dining, and weekend activity."], ["Fillmore Street", "fillmore-street", "Compare premium lifestyle demand in a different neighborhood catchment."], ["Hayes Valley", "hayes-valley", "Compare a central creative and design-conscious retail environment."]),
  }),
  retail("valencia-street", "Valencia Street", {
    parent: { name: "Mission District", path: `${BASE}mission-district/` },
    classification: "Core retail decision",
    lead: "Compare Valencia Street for food, experiential, wellness, furnishings, and destination-oriented storefront concepts within the broader Mission.",
    identity: "Valencia Street is the reviewed Retail decision corridor within the Mission parent geography. Its pedestrian-oriented customer pattern should not be generalized to every Mission block.",
    character: "Food, independent retail, wellness, furnishings, evening activity, and visible storefronts create a neighborhood and destination environment.",
    useCases: ["Food, beverage, and evening concepts", "Experiential and destination specialty retail", "Wellness, furnishings, and visible storefront businesses"],
    strengths: ["Strong food and experiential context", "Pedestrian-oriented storefront environment", "Evening activity and planned destination behavior"],
    tradeoffs: ["Parking and loading are constrained", "Conditions can change materially by block and storefront", "The corridor does not suit every convenience or large-format concept"],
    access: "Valencia combines city transit and neighborhood access, but customer parking and receiving require careful property-level evaluation.",
    related: related(["Hayes Valley", "hayes-valley", "Compare a central design-conscious shopping and dining environment."], ["Upper Market / Castro", "upper-market-castro", "Compare a transit-oriented community, service, dining, and nightlife context."], ["North Beach", "north-beach", "Compare a more visitor-oriented food and specialty environment."], ["Mission District", "mission-district", "Understand the broader parent geography and nearby commercial context."]),
  }),
  retail("upper-market-castro", "Upper Market / Castro", {
    classification: "Core retail decision",
    lead: "Compare Upper Market / Castro for neighborhood services, dining, entertainment, community-oriented businesses, and transit-visible storefronts.",
    identity: "Upper Market / Castro is a connected neighborhood-commercial and transit corridor with a customer context distinct from Valencia Street and Hayes Valley.",
    character: "Local services, food, nightlife, community identity, and destination activity combine with visible transit-oriented commercial blocks.",
    useCases: ["Neighborhood services and personal care", "Food, beverage, and evening concepts", "Community-oriented and experiential retail"],
    strengths: ["Strong neighborhood and community identity", "Useful transit visibility and city access", "Day-to-evening service, dining, and destination activity"],
    tradeoffs: ["Fit varies between Market Street and side-street storefronts", "Parking and curb access are constrained", "Evening activity may not support every operating model"],
    access: "Local and city transit are meaningful parts of the corridor's customer access. Parking, loading, and the exact storefront position remain building-level questions.",
    related: related(["Valencia Street", "valencia-street", "Compare a more food-, experiential-, and independent-retail-oriented Mission corridor."], ["Hayes Valley", "hayes-valley", "Compare a central design and lifestyle environment."], ["Fillmore Street", "fillmore-street", "Compare premium neighborhood shopping, wellness, and services."]),
  }),
  retail("north-beach", "North Beach", {
    classification: "Core retail decision",
    lead: "Compare North Beach for visitor-facing food, neighborhood demand, cafes, evening activity, and fine-grained specialty retail.",
    identity: "North Beach is a pedestrian-scaled neighborhood and visitor destination centered on food, cafes, specialty commerce, and evening activity. It is a distinct decision from nearby Jackson Square and Chinatown.",
    character: "Visitor demand and resident use overlap across restaurants, cafes, specialty shops, entertainment, and small storefronts.",
    useCases: ["Food, beverage, and hospitality-adjacent concepts", "Visitor-facing specialty retail", "Independent neighborhood and evening businesses"],
    strengths: ["Distinct visitor and neighborhood demand", "Strong food, cafe, and evening context", "Recognizable fine-grained storefront identity"],
    tradeoffs: ["Parking, loading, and servicing are constrained", "Small storefronts limit some formats", "Visitor dependence and evening patterns do not suit every concept"],
    access: "North Beach is walkable within its local context and connected by city transit, but it is not directly served by BART. Customer arrival, loading, and parking need practical validation.",
    related: related(["Chinatown", "chinatown", "Compare visitor-specialty and community-serving commerce with a different cultural and demand pattern."], ["Jackson Square", "jackson-square", "Compare a quieter design, boutique, and professional-commercial edge."], ["Union Square", "union-square", "Compare larger-scale downtown visitor, shopping, hotel, and transit context."], ["Valencia Street", "valencia-street", "Compare a more neighborhood-led food and experiential corridor."]),
  }),
  retail("chinatown", "Chinatown", {
    classification: "Core retail decision",
    lead: "Compare Chinatown for visitor-specialty, food, culturally specific, and community-serving retail in a dense central San Francisco setting.",
    identity: "Chinatown combines the visitor-oriented Grant Avenue corridor with broader resident- and Bay Area-serving commerce. Those patterns differ from Union Square's general destination-shopping environment.",
    character: "Specialty retail, food, community services, visitor demand, and compact storefronts create materially different customer patterns across the district.",
    useCases: ["Specialty and culturally specific retail", "Food and visitor-oriented concepts", "Community-serving shops and services"],
    strengths: ["Distinct resident, Bay Area, and visitor demand", "Strong specialty and food identity", "Central position near Union Square, North Beach, and downtown"],
    tradeoffs: ["Small-scale buildings constrain some formats", "Loading and parking are difficult", "Grant Avenue visitor blocks and community-serving blocks require different strategies"],
    access: "Chinatown has central city transit access and strong pedestrian connections to nearby districts. It lacks direct BART service within the district, and loading or driving requirements need property-level review.",
    related: related(["North Beach", "north-beach", "Compare another visitor and food environment with stronger evening and neighborhood-destination patterns."], ["Union Square", "union-square", "Compare broader downtown shopping, hotel, and regional-transit context."], ["Jackson Square", "jackson-square", "Compare a quieter boutique, design, and professional-commercial setting."]),
  }),
  {
    id: "south-beach", name: "South Beach", slug: "south-beach", path: `${BASE}south-beach/`, areaType: "district", spaceTypes: ["office", "retail"], defaultSpaceType: "Office", classification: "Office and selective Retail decision",
    lead: "Compare South Beach as a waterfront and Transbay-adjacent business district with office, residential, visitor, and event-driven demand.",
    identity: "South Beach sits between the Financial District, SoMa, Mission Bay, the waterfront, and the ballpark. Its commercial identity varies by block rather than behaving like a uniform downtown core.",
    character: "Office and residential demand overlap with waterfront, visitor, restaurant, and event activity. The environment is less formal than the northern Financial District and more mixed than Mission Bay.",
    useCases: ["Professional and technology office users", "Client-facing teams valuing downtown and waterfront adjacency", "Selective food, service, and mixed-use Retail"],
    strengths: ["Transbay and downtown adjacency", "Waterfront and mixed-use environment", "Connections toward SoMa and Mission Bay"],
    tradeoffs: ["Office, residential, and event conditions vary by block", "Less traditional CBD identity than Financial District", "Parking and event-day circulation require review"],
    access: "South Beach benefits from downtown transit gateways and proximity to regional routes, while local access and event patterns vary across the district.",
    related: related(["Financial District", "financial-district", "Compare a more formal office core and direct regional-transit concentration."], ["SoMa", "soma", "Compare broader adaptive office and creative-commercial inventory."], ["Mission Bay", "mission-bay", "Compare newer institutional and modern commercial context."], ["Jackson Square", "jackson-square", "Compare smaller-scale historic office character."]),
  },
  {
    id: "mission-district", name: "Mission District", slug: "mission-district", path: `${BASE}mission-district/`, areaType: "parent district", spaceTypes: ["office", "retail", "flex"], defaultSpaceType: "Retail / service", classification: "Parent Retail identity and situational Office context",
    lead: "Understand the Mission as a broad commercial parent geography, with Valencia Street representing its independently reviewed Retail corridor.",
    identity: "The Mission is a broad neighborhood and commercial context. Rofo treats Valencia Street as the distinct ranked Retail corridor; the Mission parent remains useful for navigation, Office context, and bounded Northeast Mission production context.",
    character: "Neighborhood services, food, creative businesses, independent commerce, and mixed commercial buildings vary substantially across the Mission.",
    useCases: ["Small creative and neighborhood-oriented offices", "Parent context for Valencia Street Retail", "Selective maker, service, and office-production uses in supported northeast PDR blocks"],
    strengths: ["Strong neighborhood and independent-business identity", "Varied food, service, creative, and customer context", "Central city location with multiple local transit connections"],
    tradeoffs: ["Commercial conditions vary too much to treat the entire Mission as one Retail corridor", "Parking, loading, and building formats vary by block", "Production relevance is bounded and property-specific"],
    access: "The Mission has meaningful BART and Muni access, but the exact benefit depends on the subarea. Driving, loading, and parking differ substantially across the parent geography.",
    children: [{ name: "Valencia Street", path: `${BASE}valencia-street/`, reason: "The reviewed food, experiential, wellness, and destination Retail corridor within the Mission." }],
    related: related(["Hayes Valley", "hayes-valley", "Compare a more compact design-conscious neighborhood environment."], ["Upper Market / Castro", "upper-market-castro", "Compare a distinct transit, community, service, and evening corridor."], ["Showplace Square / Design District", "showplace-square", "Compare a more explicit design-trade, showroom, and PDR setting."], ["SoMa", "soma", "Compare broader office and adaptive-commercial inventory."]),
  },
  {
    id: "marina-district", name: "Marina District", slug: "marina-district", path: `${BASE}marina-district/`, areaType: "parent district", spaceTypes: ["office", "retail"], defaultSpaceType: "Retail / service", classification: "Parent Retail identity and situational Office decision",
    lead: "Understand the Marina as a broader location context, with Chestnut Street and Union Street / Cow Hollow representing two distinct Retail decisions.",
    identity: "The Marina remains useful as a neighborhood, navigation, and Office identity. Retail comparison occurs through its reviewed corridor children rather than treating the parent as a third competing Retail vote.",
    character: "Northern neighborhood demand, lifestyle businesses, food, wellness, and smaller commercial spaces appear across the area, but Chestnut and Union Street serve different customer patterns.",
    useCases: ["Small professional and client-facing offices", "Parent context for daily-use Chestnut Street Retail", "Parent context for specialty and destination Union Street Retail"],
    strengths: ["Northern San Francisco and Marin-oriented context", "Strong neighborhood lifestyle and service demand", "Two distinct, understandable Retail corridors"],
    tradeoffs: ["Regional transit is weaker than downtown", "Parking and traffic remain material", "The parent label is too broad for a single Retail recommendation"],
    access: "Northern geography can be useful for Marin-oriented trips and local driving, while regional rail access is limited. Parking remains a practical tradeoff rather than a guaranteed advantage.",
    children: [{ name: "Chestnut Street", path: `${BASE}chestnut-street/`, reason: "Daily-use, food, service, wellness, and resident demand." }, { name: "Union Street / Cow Hollow", path: `${BASE}union-street-cow-hollow/`, reason: "Specialty, lifestyle, dining, wellness, and planned destination demand." }],
    related: related(["Fillmore Street", "fillmore-street", "Compare a premium lifestyle and neighborhood-service corridor."], ["Sacramento Street", "sacramento-street", "Compare a quieter premium and design destination."], ["Presidio", "presidio", "Compare a more campus-like Office environment with northern access."]),
  },
  {
    id: "civic-center", name: "Civic Center", slug: "civic-center", path: `${BASE}civic-center/`, areaType: "district", spaceTypes: ["office", "retail"], defaultSpaceType: "Office", classification: "Situational Office and Retail decision",
    lead: "Compare Civic Center for civic, government, nonprofit, institutional, arts, and regional-transit adjacency.",
    identity: "Civic Center is a narrow situational commercial decision shaped by government, courts, cultural institutions, public services, and major transit—not a general substitute for every central-office district.",
    character: "Institutional and civic activity creates a specialized weekday environment, with selective service, food, nonprofit, legal, and public-facing demand.",
    useCases: ["Nonprofit and civic-adjacent organizations", "Government, legal, and institutional users", "Selective service and food businesses tied to daytime activity"],
    strengths: ["Civic and institutional adjacency", "Strong BART and Muni access", "Central position near Hayes Valley, SoMa, and Mid-Market"],
    tradeoffs: ["A narrow ecosystem fit rather than broad Office or Retail appeal", "Street conditions and customer environment vary materially", "Parking and driving are constrained"],
    access: "Civic Center offers strong regional and local transit through BART and Muni. Driving and parking are more constrained and should be treated as tradeoffs.",
    related: related(["Hayes Valley", "hayes-valley", "Compare a smaller-scale creative, retail, and neighborhood environment."], ["SoMa", "soma", "Compare broader office and adaptive-commercial inventory."], ["Financial District", "financial-district", "Compare a formal client-facing office core."], ["Mission District", "mission-district", "Compare a broader neighborhood and independent-business setting."]),
  },
  {
    id: "bayview-industrial", name: "Bayview Industrial", slug: "bayview-industrial", path: `${BASE}bayview-industrial/`, areaType: "industrial district", spaceTypes: ["industrial", "flex"], defaultSpaceType: "Industrial / warehouse / flex", classification: "Core Industrial and operational Flex decision",
    lead: "Compare Bayview Industrial for city-serving warehouse, distribution, food, contractor, fleet, production, and operational Flex requirements.",
    identity: "Bayview Industrial is the operational decision geography. Broader Bayview remains neighborhood and presentation context and does not create a second recommendation vote.",
    character: "Warehouse, service, food, production, contractor, fleet, and practical office/operational uses form San Francisco's broadest city-serving industrial setting.",
    useCases: ["Warehouse, distribution, and city-serving logistics", "Contractor, service, repair, fleet, and dispatch operations", "Food production, light manufacturing, and operational Flex"],
    strengths: ["Broadest operational Industrial depth inside San Francisco", "Strong fit for service vehicles, distribution, and production", "Southeast geography supporting regional road access"],
    tradeoffs: ["Large regional logistics requirements may need East Bay scale", "Customer-facing and employee-environment priorities may favor other districts", "Loading, yards, systems, use, and shoreline conditions remain property-specific"],
    access: "The southeast position supports US-101 and I-280-oriented movement and city-serving operations. Exact truck circulation, fleet parking, and regional practicality must be verified at the property.",
    contexts: [{ name: "Broader Bayview", reason: "Neighborhood and presentation context; Bayview Industrial owns the operational recommendation decision." }, { name: "Southern Waterfront / Piers 80–96", reason: "Specialized port, maritime, cargo, and heavy-commercial investigation—not an ordinary shortlist geography." }],
    related: related(["Central Waterfront", "central-waterfront", "Compare production, fabrication, maker, prototyping, and practical Flex context."], ["Dogpatch", "dogpatch", "Compare a more adaptive mixed-use and office/R&D environment."], ["Showplace Square / Design District", "showplace-square", "Compare customer-facing showroom and design-trade Flex."]),
  },
  {
    id: "central-waterfront", name: "Central Waterfront", slug: "central-waterfront", path: `${BASE}central-waterfront/`, areaType: "industrial district", spaceTypes: ["industrial", "flex"], defaultSpaceType: "Industrial / warehouse / flex", classification: "Core Industrial and Flex decision",
    lead: "Compare Central Waterfront for production, fabrication, maker, prototyping, product-development, service-industrial, and office-production requirements.",
    identity: "Central Waterfront is the reviewed operational PDR decision south of mixed-use Dogpatch. It is distinct from Bayview's warehouse/logistics depth and Showplace Square's showroom orientation.",
    character: "Production, fabrication, maker, practical Flex, prototyping, maritime-support, and office-production activity define the commercial environment.",
    useCases: ["Urban production, fabrication, and maker businesses", "Prototyping and product-development teams", "Practical Flex and office-production hybrids"],
    strengths: ["Protected production and PDR context", "Useful balance of fabrication, product development, and office-production", "Proximity to Dogpatch and Mission Bay ecosystems"],
    tradeoffs: ["Less warehouse and fleet depth than Bayview Industrial", "Less neighborhood and adaptive-office character than Dogpatch", "Power, ventilation, loading, use, environmental, and shoreline conditions are property-specific"],
    access: "Central Waterfront has southeast road and Third Street transit connections, but loading, truck circulation, employee access, and parking depend on the exact property and subarea.",
    contexts: [{ name: "Southern Waterfront", reason: "Maritime and port context may matter to specialized users, but it is not a separate ordinary recommendation vote." }],
    related: related(["Bayview Industrial", "bayview-industrial", "Compare deeper warehouse, fleet, food, distribution, and city-serving operational context."], ["Dogpatch", "dogpatch", "Compare adaptive buildings, neighborhood context, and office/R&D adjacency."], ["Showplace Square / Design District", "showplace-square", "Compare showroom, trade, and customer-facing Flex."], ["Potrero Hill", "potrero-hill", "Compare selective smaller production and Flex at the eastern/base edge."]),
  },
  {
    id: "potrero-hill", name: "Potrero Hill", slug: "potrero-hill", path: `${BASE}potrero-hill/`, areaType: "district", spaceTypes: ["office", "retail", "industrial", "flex"], defaultSpaceType: "Industrial / warehouse / flex", classification: "Situational Industrial/Flex edge",
    lead: "Understand Potrero Hill's neighborhood context and the selective Industrial/Flex relevance of its eastern and base PDR edges.",
    identity: "Industrial and Flex relevance applies to reviewed eastern/base, production-adjacent, and Showplace-connected blocks. The residential hill is not an Industrial/Flex market.",
    character: "Smaller production, maker, studio, service-commercial, and office-production uses appear selectively at the district's lower commercial edges.",
    useCases: ["Smaller maker and production users", "Creative Flex and office-production teams", "Selective service-commercial operations"],
    strengths: ["Neighborhood character near production districts", "Smaller adaptive and hybrid commercial context", "Connections to Showplace Square, Dogpatch, and Mission Bay"],
    tradeoffs: ["Suitability is bounded to specific commercial edges", "Operational capability cannot be inferred from the Potrero Hill name", "Loading, power, ventilation, parking, use, and residential adjacency require property review"],
    access: "The eastern/base edge can connect to southeast roads and nearby production districts, but topography and mixed residential context make access highly property-specific.",
    related: related(["Central Waterfront", "central-waterfront", "Compare a more consistently operational production and PDR setting."], ["Showplace Square / Design District", "showplace-square", "Compare stronger showroom, trade, and customer-facing context."], ["Dogpatch", "dogpatch", "Compare adaptive mixed-use character and Mission Bay adjacency."]),
  },
];

const byPath = Object.freeze(Object.fromEntries(surfaces.map((surface) => [surface.path, Object.freeze(surface)])));

module.exports = Object.freeze({
  schemaVersion: "sf-public-decision-surfaces:v1",
  marketId: "san-francisco",
  status: "READY",
  surfaces: Object.freeze(surfaces),
  byPath,
});
