const ROLE = Object.freeze({ DECISION: "RECOMMENDATION_ELIGIBLE", PARENT: "PARENT_PRESENTATION", DEFERRED: "DEFERRED_UNVERIFIED" });

// Retail-only geography ownership. These records extend the shared SF graph
// without making corridor identities eligible for Office recommendations.
const approved = Object.freeze([
  { districtId: "sacramento-street", districtName: "Sacramento Street", parentDistrictId: "", role: ROLE.DECISION, classification: "SITUATIONAL_RETAIL", accessKnowledgeOwnerDistrictId: "marina-district", futurePublicPath: "/commercial-real-estate/CA/san-francisco/sacramento-street/", aliases: ["Sacramento Street retail corridor"], evidence: ["https://commissions.sfplanning.org/cpcpackets/2013.0077T.pdf"], reviewReason: "A formally recognized neighborhood-commercial district with a narrower premium, design, service, and destination-shopping role than Union Square or Hayes Valley." },
  { districtId: "fillmore-street", districtName: "Fillmore Street", parentDistrictId: "", role: ROLE.DECISION, classification: "CORE_RETAIL", accessKnowledgeOwnerDistrictId: "hayes-valley", futurePublicPath: "/commercial-real-estate/CA/san-francisco/fillmore-street/", aliases: ["Upper Fillmore", "Fillmore retail corridor"], evidence: ["https://sfplanning.org/index.php/event/planning-commission-26", "data/peter/research/neighborhoods.resolved-candidates.json"], reviewReason: "A formally recognized commercial district with neighborhood, lifestyle, dining, service, and premium customer context distinct from downtown and Hayes Valley." },
  { districtId: "union-street-cow-hollow", districtName: "Union Street / Cow Hollow", parentDistrictId: "marina-district", role: ROLE.DECISION, classification: "CORE_RETAIL", accessKnowledgeOwnerDistrictId: "marina-district", futurePublicPath: "/commercial-real-estate/CA/san-francisco/union-street-cow-hollow/", aliases: ["Union Street", "Cow Hollow"], evidence: ["https://sfplanning.org/sites/default/files/za/1823%20Union%20Street.pdf", "data/peter/research/neighborhoods.resolved-candidates.json"], reviewReason: "Specialty shops, dining, wellness, and wider-trade-area destination behavior distinguish Union Street from Chestnut's broader daily-use environment." },
  { districtId: "chestnut-street", districtName: "Chestnut Street", parentDistrictId: "marina-district", role: ROLE.DECISION, classification: "CORE_RETAIL", accessKnowledgeOwnerDistrictId: "marina-district", futurePublicPath: "/commercial-real-estate/CA/san-francisco/chestnut-street/", aliases: ["Chestnut retail corridor"], evidence: ["https://default.sfplanning.org/meetingarchive/planning_dept/commissions.sfplanning.org/cpcpackets/2013.0245C.pdf", "data/peter/research/neighborhoods.resolved-candidates.json"], reviewReason: "A dense neighborhood-commercial corridor with food, services, wellness, convenience, and storefront retail that is meaningfully different from Union Street's specialty/destination emphasis." },
  { districtId: "valencia-street", districtName: "Valencia Street", parentDistrictId: "mission-district", role: ROLE.DECISION, classification: "CORE_RETAIL", accessKnowledgeOwnerDistrictId: "mission-district", futurePublicPath: "/commercial-real-estate/CA/san-francisco/valencia-street/", aliases: ["Valencia retail corridor"], evidence: ["https://generalplan.sfplanning.org/Mission.htm", "https://commissions.sfplanning.org/cpcpackets/2011.0559TZ.pdf"], reviewReason: "A formally recognized pedestrian-oriented commercial district with food, furnishings, experiential, evening, and visible-storefront behavior that cannot be attributed uniformly to the broader Mission." },
  { districtId: "upper-market-castro", districtName: "Upper Market / Castro", parentDistrictId: "", role: ROLE.DECISION, classification: "CORE_RETAIL", accessKnowledgeOwnerDistrictId: "hayes-valley", futurePublicPath: "/commercial-real-estate/CA/san-francisco/upper-market-castro/", aliases: ["Upper Market", "Castro", "The Castro"], evidence: ["https://generalplan.sfplanning.org/Market_Octavia.htm", "data/peter/research/neighborhoods.resolved-candidates.json"], reviewReason: "A recognized neighborhood-commercial and transit corridor with local service, dining, nightlife, community, and destination demand distinct from the Mission and Hayes Valley." },
  { districtId: "north-beach", districtName: "North Beach", parentDistrictId: "", role: ROLE.DECISION, classification: "CORE_RETAIL", accessKnowledgeOwnerDistrictId: "jackson-square", futurePublicPath: "/commercial-real-estate/CA/san-francisco/north-beach/", aliases: ["Columbus Avenue", "North Beach retail district"], evidence: ["https://default.sfplanning.org/Citywide/publicspace/docs/2010_North_Beach_PLS_SFPlanning.pdf", "_data/commercialDistrictPublicIntegrations.js"], reviewReason: "A pedestrian-scaled, visitor-facing and neighborhood-serving food, specialty, and evening environment distinct from Jackson Square's design and boutique-office edge." },
  { districtId: "chinatown", districtName: "Chinatown", parentDistrictId: "", role: ROLE.DECISION, classification: "CORE_RETAIL", accessKnowledgeOwnerDistrictId: "union-square", futurePublicPath: "/commercial-real-estate/CA/san-francisco/chinatown/", aliases: ["Grant Avenue", "Chinatown Visitor Retail District"], evidence: ["https://generalplan.sfplanning.org/Chinatown.htm", "https://commissions.sfplanning.org/cpcpackets/2020-011581PCA.pdf"], reviewReason: "A distinct resident-serving and visitor-specialty retail environment with Grant Avenue destination demand that is not interchangeable with Union Square." },
]);

const parents = Object.freeze([
  { districtId: "marina-district", districtName: "Marina District", role: ROLE.PARENT, childDistrictIds: ["chestnut-street", "union-street-cow-hollow"], reason: "Umbrella and public identity; Retail competition occurs through its reviewed corridor children." },
  { districtId: "mission-district", districtName: "Mission District", role: ROLE.PARENT, childDistrictIds: ["valencia-street"], reason: "Umbrella and compatibility owner; Valencia is the reviewed ranked corridor while other Mission corridors remain unverified." },
]);

const deferred = Object.freeze([
  { districtId: "polk-street", districtName: "Polk Street", role: ROLE.DEFERRED, reason: "Commercial-district identity exists, but reviewed Rofo customer-environment and Access differentiation is incomplete." },
  { districtId: "divisadero", districtName: "Divisadero", role: ROLE.DEFERRED, reason: "Commercial-district identity exists, but the current repository does not support a complete independent Retail assessment." },
  { districtId: "clement-street", districtName: "Clement Street", parentDistrictId: "richmond", role: ROLE.DEFERRED, reason: "The Richmond public identity references Clement, but corridor-level Access and Retail intelligence remain incomplete." },
  { districtId: "irving-street", districtName: "Irving Street", parentDistrictId: "sunset", role: ROLE.DEFERRED, reason: "The Sunset public identity exists, but reviewed corridor-specific customer and Access evidence remains incomplete." },
  { districtId: "west-portal", districtName: "West Portal", role: ROLE.DEFERRED, reason: "A recognized commercial district, but the repository lacks a reviewed recommendation-grade environment and Access foundation." },
]);

module.exports = Object.freeze({
  schemaVersion: "sf-retail-decision-geographies:v1",
  marketId: "san-francisco",
  propertyType: "retail_service",
  role: ROLE,
  approved,
  parents,
  deferred,
  competitionFamilies: parents.map((parent) => ({ familyId: `sf-retail:${parent.districtId}`, parentDistrictId: parent.districtId, eligibleDistrictIds: parent.childDistrictIds.slice(), policy: "CHILDREN_COMPETE_PARENT_PRESENTS" })),
  completenessRule: "Every material candidate is explicitly approved, assigned a non-competing presentation role, or deferred with a review reason; approved decision geographies must clear all coverage hard gates.",
});
