from __future__ import annotations

import csv
import json
from collections import Counter
from pathlib import Path

from common import DERIVED_DIR, REPORTS_DIR, ensure_dirs


MATCH_REVIEW_CSV = DERIVED_DIR / "active_building_semantic_match_review.csv"
LOOKUP_JSON = DERIVED_DIR / "production_building_semantic_id_lookup.json"
REPORT_MD = REPORTS_DIR / "production_building_id_preservation_audit.md"


def clean(value) -> str:
    return "" if value is None else str(value).strip()


def load_review_rows() -> list[dict]:
    with MATCH_REVIEW_CSV.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def build_lookup(rows: list[dict]) -> dict:
    lookup = {}
    for row in rows:
        if row.get("risk_flag") != "low":
            continue
        path = clean(row.get("production_building_path"))
        building_id = clean(row.get("building_id"))
        if not path or not building_id:
            continue
        lookup[path] = {
            "semantic_source_building_id": building_id,
            "match_method": "reviewed_low_risk_address_match",
            "risk_flag": row.get("risk_flag", ""),
            "name_similarity_score": row.get("name_similarity_score", ""),
            "approved_signals": row.get("approved_signals", ""),
            "average_confidence": row.get("average_confidence", ""),
            "total_supporting_listing_count": row.get("total_supporting_listing_count", ""),
        }
    return lookup


def write_report(rows: list[dict], lookup: dict) -> None:
    risk_counts = Counter(row.get("risk_flag") for row in rows)
    lines = [
        "# Production Building ID Preservation Audit",
        "",
        "## Purpose",
        "",
        "This audit documents whether legacy Rofo building IDs exist in the current production building data pipeline and how a safe internal semantic ID bridge can be preserved without changing public templates or UI.",
        "",
        "## Source Files Inspected",
        "",
        "| Source | Current role | ID fields found | Notes |",
        "| --- | --- | --- | --- |",
        "| `data-sources/reference/buildings-live-before-merge.json` | Primary legacy production building source for `_data/buildings.js` | none | Already normalized. No `b_id`, `building_id`, or `legacy_building_id` fields remain. |",
        "| `data-sources/reference/buildings-legacy.json` | Legacy reference copy | none | Same normalized shape as `buildings-live-before-merge.json`. |",
        "| `data-sources/reference/company-buildings.json` | Company building source for `_data/buildings.js` | none | Already normalized. Company raw files have `property_id`, but not Rofo legacy `building_id`. |",
        "| `_data/approvedAvailabilityBuildings.js` | Approved Highwoods building-level enrichment source | none | Uses `merge_key`, not Rofo legacy building IDs. |",
        "| `data/peter/raw/rofo_buildings.csv` | Peter raw legacy export | `building_id` | This is the source of truth for historical semantic IDs. |",
        "| `data/peter/derived/building_signals.csv` | Derived Peter building signals | `building_id` | Good for semantic identity matching, but not currently connected to production building pages by ID. |",
        "",
        "## Where IDs Are Lost",
        "",
        "The current checked-in production building JSON files were generated by older normalization scripts that grouped rows by address and emitted page-ready building records. Those generated records do not include the original Rofo `building_id`. By the time `_data/buildings.js` imports them, there is no original ID to preserve.",
        "",
        "## Recommended Field Name",
        "",
        "`semantic_source_building_id`",
        "",
        "This name is intentionally internal and specific. It means the ID came from the reviewed semantic identity bridge, not necessarily from the active production source record itself.",
        "",
        "## Merge Behavior Added",
        "",
        f"- Reviewed low-risk semantic ID lookup records generated: {len(lookup):,}",
        f"- Source match review records: {len(rows):,}",
        f"- Low-risk rows: {risk_counts.get('low', 0):,}",
        f"- Medium-risk rows excluded from lookup: {risk_counts.get('medium', 0):,}",
        f"- High-risk rows excluded from lookup: {risk_counts.get('high', 0):,}",
        "",
        "Only low-risk audited matches are written to `production_building_semantic_id_lookup.json`. `_data/buildings.js` can attach `semantic_source_building_id` internally by `building_path` when a lookup record exists. Medium and high-risk address matches remain address-fallback only in the semantic bridge.",
        "",
        "## Risks and Caveats",
        "",
        "- This does not recover original IDs from the checked-in production source JSON. It preserves a reviewed semantic source ID for low-risk matched active pages.",
        "- Because the lookup was bootstrapped from address matching, it should remain limited to low-risk audited rows.",
        "- The safest long-term fix is to regenerate `data-sources/reference/buildings-live-before-merge.json` with original `building_id` preserved at source generation time.",
        "- This field should not be rendered publicly and should not be used for current availability, pricing, or listing claims.",
        "",
        "## Can This Enable Reliable Semantic Matching?",
        "",
        "Partially. Low-risk active pages can now match semantic identity by `semantic_source_building_id`, which is stronger than re-running address fallback every time. The remaining medium and high-risk pages still require address fallback or manual review. Broad production use still depends on preserving true legacy IDs in the upstream source generation process.",
    ]
    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ensure_dirs()
    rows = load_review_rows()
    lookup = build_lookup(rows)
    LOOKUP_JSON.write_text(json.dumps(lookup, indent=2, sort_keys=True), encoding="utf-8")
    write_report(rows, lookup)
    print(f"Match review rows loaded: {len(rows):,}")
    print(f"Low-risk semantic ID lookup records written: {len(lookup):,}")
    print(f"Wrote {LOOKUP_JSON}")
    print(f"Wrote {REPORT_MD}")


if __name__ == "__main__":
    main()
